/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SymbolOpenApi.Client.OpenAPIDateConverter;

namespace SymbolOpenApi.Model
{
    /// <summary>
    /// AggregateTransactionBodyExtendedDTO
    /// </summary>
    [DataContract]
    public partial class AggregateTransactionBodyExtendedDTO :  IEquatable<AggregateTransactionBodyExtendedDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregateTransactionBodyExtendedDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AggregateTransactionBodyExtendedDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregateTransactionBodyExtendedDTO" /> class.
        /// </summary>
        /// <param name="transactionsHash">transactionsHash (required).</param>
        /// <param name="cosignatures">Array of transaction cosignatures. (required).</param>
        /// <param name="transactions">Array of transactions initiated by different accounts. (required).</param>
        public AggregateTransactionBodyExtendedDTO(string transactionsHash = default(string), List<CosignatureDTO> cosignatures = default(List<CosignatureDTO>), List<EmbeddedTransactionInfoDTO> transactions = default(List<EmbeddedTransactionInfoDTO>))
        {
            // to ensure "transactionsHash" is required (not null)
            if (transactionsHash == null)
            {
                throw new InvalidDataException("transactionsHash is a required property for AggregateTransactionBodyExtendedDTO and cannot be null");
            }
            else
            {
                this.TransactionsHash = transactionsHash;
            }

            // to ensure "cosignatures" is required (not null)
            if (cosignatures == null)
            {
                throw new InvalidDataException("cosignatures is a required property for AggregateTransactionBodyExtendedDTO and cannot be null");
            }
            else
            {
                this.Cosignatures = cosignatures;
            }

            // to ensure "transactions" is required (not null)
            if (transactions == null)
            {
                throw new InvalidDataException("transactions is a required property for AggregateTransactionBodyExtendedDTO and cannot be null");
            }
            else
            {
                this.Transactions = transactions;
            }

        }

        /// <summary>
        /// Gets or Sets TransactionsHash
        /// </summary>
        [DataMember(Name="transactionsHash", EmitDefaultValue=true)]
        public string TransactionsHash { get; set; }

        /// <summary>
        /// Array of transaction cosignatures.
        /// </summary>
        /// <value>Array of transaction cosignatures.</value>
        [DataMember(Name="cosignatures", EmitDefaultValue=true)]
        public List<CosignatureDTO> Cosignatures { get; set; }

        /// <summary>
        /// Array of transactions initiated by different accounts.
        /// </summary>
        /// <value>Array of transactions initiated by different accounts.</value>
        [DataMember(Name="transactions", EmitDefaultValue=true)]
        public List<EmbeddedTransactionInfoDTO> Transactions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AggregateTransactionBodyExtendedDTO {\n");
            sb.Append("  TransactionsHash: ").Append(TransactionsHash).Append("\n");
            sb.Append("  Cosignatures: ").Append(Cosignatures).Append("\n");
            sb.Append("  Transactions: ").Append(Transactions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AggregateTransactionBodyExtendedDTO);
        }

        /// <summary>
        /// Returns true if AggregateTransactionBodyExtendedDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of AggregateTransactionBodyExtendedDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AggregateTransactionBodyExtendedDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransactionsHash == input.TransactionsHash ||
                    (this.TransactionsHash != null &&
                    this.TransactionsHash.Equals(input.TransactionsHash))
                ) && 
                (
                    this.Cosignatures == input.Cosignatures ||
                    this.Cosignatures != null &&
                    input.Cosignatures != null &&
                    this.Cosignatures.SequenceEqual(input.Cosignatures)
                ) && 
                (
                    this.Transactions == input.Transactions ||
                    this.Transactions != null &&
                    input.Transactions != null &&
                    this.Transactions.SequenceEqual(input.Transactions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionsHash != null)
                    hashCode = hashCode * 59 + this.TransactionsHash.GetHashCode();
                if (this.Cosignatures != null)
                    hashCode = hashCode * 59 + this.Cosignatures.GetHashCode();
                if (this.Transactions != null)
                    hashCode = hashCode * 59 + this.Transactions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
