/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SymbolOpenApi.Client.OpenAPIDateConverter;

namespace SymbolOpenApi.Model
{
    /// <summary>
    /// EmbeddedMosaicGlobalRestrictionTransactionDTO
    /// </summary>
    [DataContract]
    public partial class EmbeddedMosaicGlobalRestrictionTransactionDTO :  IEquatable<EmbeddedMosaicGlobalRestrictionTransactionDTO>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [DataMember(Name="network", EmitDefaultValue=true)]
        public NetworkTypeEnum Network { get; set; }
        /// <summary>
        /// Gets or Sets PreviousRestrictionType
        /// </summary>
        [DataMember(Name="previousRestrictionType", EmitDefaultValue=true)]
        public MosaicRestrictionTypeEnum PreviousRestrictionType { get; set; }
        /// <summary>
        /// Gets or Sets NewRestrictionType
        /// </summary>
        [DataMember(Name="newRestrictionType", EmitDefaultValue=true)]
        public MosaicRestrictionTypeEnum NewRestrictionType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedMosaicGlobalRestrictionTransactionDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmbeddedMosaicGlobalRestrictionTransactionDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmbeddedMosaicGlobalRestrictionTransactionDTO" /> class.
        /// </summary>
        /// <param name="signerPublicKey">Public key. (required).</param>
        /// <param name="version">Entity version. (required).</param>
        /// <param name="network">network (required).</param>
        /// <param name="type">type (required).</param>
        /// <param name="mosaicId">Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier.  (required).</param>
        /// <param name="referenceMosaicId">Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier.  (required).</param>
        /// <param name="restrictionKey">Restriction key. (required).</param>
        /// <param name="previousRestrictionValue">Restriction value. (required).</param>
        /// <param name="newRestrictionValue">Restriction value. (required).</param>
        /// <param name="previousRestrictionType">previousRestrictionType (required).</param>
        /// <param name="newRestrictionType">newRestrictionType (required).</param>
        public EmbeddedMosaicGlobalRestrictionTransactionDTO(string signerPublicKey = default(string), int version = default(int), NetworkTypeEnum network = default(NetworkTypeEnum), int type = default(int), string mosaicId = default(string), string referenceMosaicId = default(string), string restrictionKey = default(string), string previousRestrictionValue = default(string), string newRestrictionValue = default(string), MosaicRestrictionTypeEnum previousRestrictionType = default(MosaicRestrictionTypeEnum), MosaicRestrictionTypeEnum newRestrictionType = default(MosaicRestrictionTypeEnum))
        {
            // to ensure "signerPublicKey" is required (not null)
            if (signerPublicKey == null)
            {
                throw new InvalidDataException("signerPublicKey is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.SignerPublicKey = signerPublicKey;
            }

            // to ensure "version" is required (not null)
            if (version == null)
            {
                throw new InvalidDataException("version is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this._Version = version;
            }

            // to ensure "network" is required (not null)
            if (network == null)
            {
                throw new InvalidDataException("network is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.Network = network;
            }

            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.Type = type;
            }

            // to ensure "mosaicId" is required (not null)
            if (mosaicId == null)
            {
                throw new InvalidDataException("mosaicId is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.MosaicId = mosaicId;
            }

            // to ensure "referenceMosaicId" is required (not null)
            if (referenceMosaicId == null)
            {
                throw new InvalidDataException("referenceMosaicId is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.ReferenceMosaicId = referenceMosaicId;
            }

            // to ensure "restrictionKey" is required (not null)
            if (restrictionKey == null)
            {
                throw new InvalidDataException("restrictionKey is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.RestrictionKey = restrictionKey;
            }

            // to ensure "previousRestrictionValue" is required (not null)
            if (previousRestrictionValue == null)
            {
                throw new InvalidDataException("previousRestrictionValue is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.PreviousRestrictionValue = previousRestrictionValue;
            }

            // to ensure "newRestrictionValue" is required (not null)
            if (newRestrictionValue == null)
            {
                throw new InvalidDataException("newRestrictionValue is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.NewRestrictionValue = newRestrictionValue;
            }

            // to ensure "previousRestrictionType" is required (not null)
            if (previousRestrictionType == null)
            {
                throw new InvalidDataException("previousRestrictionType is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.PreviousRestrictionType = previousRestrictionType;
            }

            // to ensure "newRestrictionType" is required (not null)
            if (newRestrictionType == null)
            {
                throw new InvalidDataException("newRestrictionType is a required property for EmbeddedMosaicGlobalRestrictionTransactionDTO and cannot be null");
            }
            else
            {
                this.NewRestrictionType = newRestrictionType;
            }

        }

        /// <summary>
        /// Public key.
        /// </summary>
        /// <value>Public key.</value>
        [DataMember(Name="signerPublicKey", EmitDefaultValue=true)]
        public string SignerPublicKey { get; set; }

        /// <summary>
        /// Entity version.
        /// </summary>
        /// <value>Entity version.</value>
        [DataMember(Name="version", EmitDefaultValue=true)]
        public int _Version { get; set; }


        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=true)]
        public int Type { get; set; }

        /// <summary>
        /// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
        /// </summary>
        /// <value>Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. </value>
        [DataMember(Name="mosaicId", EmitDefaultValue=true)]
        public string MosaicId { get; set; }

        /// <summary>
        /// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
        /// </summary>
        /// <value>Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. </value>
        [DataMember(Name="referenceMosaicId", EmitDefaultValue=true)]
        public string ReferenceMosaicId { get; set; }

        /// <summary>
        /// Restriction key.
        /// </summary>
        /// <value>Restriction key.</value>
        [DataMember(Name="restrictionKey", EmitDefaultValue=true)]
        public string RestrictionKey { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        [DataMember(Name="previousRestrictionValue", EmitDefaultValue=true)]
        public string PreviousRestrictionValue { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        [DataMember(Name="newRestrictionValue", EmitDefaultValue=true)]
        public string NewRestrictionValue { get; set; }



        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EmbeddedMosaicGlobalRestrictionTransactionDTO {\n");
            sb.Append("  SignerPublicKey: ").Append(SignerPublicKey).Append("\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  MosaicId: ").Append(MosaicId).Append("\n");
            sb.Append("  ReferenceMosaicId: ").Append(ReferenceMosaicId).Append("\n");
            sb.Append("  RestrictionKey: ").Append(RestrictionKey).Append("\n");
            sb.Append("  PreviousRestrictionValue: ").Append(PreviousRestrictionValue).Append("\n");
            sb.Append("  NewRestrictionValue: ").Append(NewRestrictionValue).Append("\n");
            sb.Append("  PreviousRestrictionType: ").Append(PreviousRestrictionType).Append("\n");
            sb.Append("  NewRestrictionType: ").Append(NewRestrictionType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmbeddedMosaicGlobalRestrictionTransactionDTO);
        }

        /// <summary>
        /// Returns true if EmbeddedMosaicGlobalRestrictionTransactionDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EmbeddedMosaicGlobalRestrictionTransactionDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmbeddedMosaicGlobalRestrictionTransactionDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SignerPublicKey == input.SignerPublicKey ||
                    (this.SignerPublicKey != null &&
                    this.SignerPublicKey.Equals(input.SignerPublicKey))
                ) && 
                (
                    this._Version == input._Version ||
                    (this._Version != null &&
                    this._Version.Equals(input._Version))
                ) && 
                (
                    this.Network == input.Network ||
                    (this.Network != null &&
                    this.Network.Equals(input.Network))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.MosaicId == input.MosaicId ||
                    (this.MosaicId != null &&
                    this.MosaicId.Equals(input.MosaicId))
                ) && 
                (
                    this.ReferenceMosaicId == input.ReferenceMosaicId ||
                    (this.ReferenceMosaicId != null &&
                    this.ReferenceMosaicId.Equals(input.ReferenceMosaicId))
                ) && 
                (
                    this.RestrictionKey == input.RestrictionKey ||
                    (this.RestrictionKey != null &&
                    this.RestrictionKey.Equals(input.RestrictionKey))
                ) && 
                (
                    this.PreviousRestrictionValue == input.PreviousRestrictionValue ||
                    (this.PreviousRestrictionValue != null &&
                    this.PreviousRestrictionValue.Equals(input.PreviousRestrictionValue))
                ) && 
                (
                    this.NewRestrictionValue == input.NewRestrictionValue ||
                    (this.NewRestrictionValue != null &&
                    this.NewRestrictionValue.Equals(input.NewRestrictionValue))
                ) && 
                (
                    this.PreviousRestrictionType == input.PreviousRestrictionType ||
                    (this.PreviousRestrictionType != null &&
                    this.PreviousRestrictionType.Equals(input.PreviousRestrictionType))
                ) && 
                (
                    this.NewRestrictionType == input.NewRestrictionType ||
                    (this.NewRestrictionType != null &&
                    this.NewRestrictionType.Equals(input.NewRestrictionType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignerPublicKey != null)
                    hashCode = hashCode * 59 + this.SignerPublicKey.GetHashCode();
                if (this._Version != null)
                    hashCode = hashCode * 59 + this._Version.GetHashCode();
                if (this.Network != null)
                    hashCode = hashCode * 59 + this.Network.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.MosaicId != null)
                    hashCode = hashCode * 59 + this.MosaicId.GetHashCode();
                if (this.ReferenceMosaicId != null)
                    hashCode = hashCode * 59 + this.ReferenceMosaicId.GetHashCode();
                if (this.RestrictionKey != null)
                    hashCode = hashCode * 59 + this.RestrictionKey.GetHashCode();
                if (this.PreviousRestrictionValue != null)
                    hashCode = hashCode * 59 + this.PreviousRestrictionValue.GetHashCode();
                if (this.NewRestrictionValue != null)
                    hashCode = hashCode * 59 + this.NewRestrictionValue.GetHashCode();
                if (this.PreviousRestrictionType != null)
                    hashCode = hashCode * 59 + this.PreviousRestrictionType.GetHashCode();
                if (this.NewRestrictionType != null)
                    hashCode = hashCode * 59 + this.NewRestrictionType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
