/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MosaicAddressRestrictionTransactionBodyDTO
    /// </summary>
    [DataContract]
    public partial class MosaicAddressRestrictionTransactionBodyDTO :  IEquatable<MosaicAddressRestrictionTransactionBodyDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MosaicAddressRestrictionTransactionBodyDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MosaicAddressRestrictionTransactionBodyDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MosaicAddressRestrictionTransactionBodyDTO" /> class.
        /// </summary>
        /// <param name="mosaicId">Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier.  (required).</param>
        /// <param name="restrictionKey">Restriction key. (required).</param>
        /// <param name="previousRestrictionValue">Restriction value. (required).</param>
        /// <param name="newRestrictionValue">Restriction value. (required).</param>
        /// <param name="targetAddress">Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA  (required).</param>
        public MosaicAddressRestrictionTransactionBodyDTO(string mosaicId = default(string), string restrictionKey = default(string), string previousRestrictionValue = default(string), string newRestrictionValue = default(string), string targetAddress = default(string))
        {
            // to ensure "mosaicId" is required (not null)
            if (mosaicId == null)
            {
                throw new InvalidDataException("mosaicId is a required property for MosaicAddressRestrictionTransactionBodyDTO and cannot be null");
            }
            else
            {
                this.MosaicId = mosaicId;
            }

            // to ensure "restrictionKey" is required (not null)
            if (restrictionKey == null)
            {
                throw new InvalidDataException("restrictionKey is a required property for MosaicAddressRestrictionTransactionBodyDTO and cannot be null");
            }
            else
            {
                this.RestrictionKey = restrictionKey;
            }

            // to ensure "previousRestrictionValue" is required (not null)
            if (previousRestrictionValue == null)
            {
                throw new InvalidDataException("previousRestrictionValue is a required property for MosaicAddressRestrictionTransactionBodyDTO and cannot be null");
            }
            else
            {
                this.PreviousRestrictionValue = previousRestrictionValue;
            }

            // to ensure "newRestrictionValue" is required (not null)
            if (newRestrictionValue == null)
            {
                throw new InvalidDataException("newRestrictionValue is a required property for MosaicAddressRestrictionTransactionBodyDTO and cannot be null");
            }
            else
            {
                this.NewRestrictionValue = newRestrictionValue;
            }

            // to ensure "targetAddress" is required (not null)
            if (targetAddress == null)
            {
                throw new InvalidDataException("targetAddress is a required property for MosaicAddressRestrictionTransactionBodyDTO and cannot be null");
            }
            else
            {
                this.TargetAddress = targetAddress;
            }

        }

        /// <summary>
        /// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
        /// </summary>
        /// <value>Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. </value>
        [DataMember(Name="mosaicId", EmitDefaultValue=true)]
        public string MosaicId { get; set; }

        /// <summary>
        /// Restriction key.
        /// </summary>
        /// <value>Restriction key.</value>
        [DataMember(Name="restrictionKey", EmitDefaultValue=true)]
        public string RestrictionKey { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        [DataMember(Name="previousRestrictionValue", EmitDefaultValue=true)]
        public string PreviousRestrictionValue { get; set; }

        /// <summary>
        /// Restriction value.
        /// </summary>
        /// <value>Restriction value.</value>
        [DataMember(Name="newRestrictionValue", EmitDefaultValue=true)]
        public string NewRestrictionValue { get; set; }

        /// <summary>
        /// Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA 
        /// </summary>
        /// <value>Address expressed in Base32 format. If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Example: TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA.  Otherwise (e.g. 0x91) it represents a namespace id which starts at byte 1. Example: THBIMC3THGH5RUYAAAAAAAAAAAAAAAAAAAAAAAA </value>
        [DataMember(Name="targetAddress", EmitDefaultValue=true)]
        public string TargetAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MosaicAddressRestrictionTransactionBodyDTO {\n");
            sb.Append("  MosaicId: ").Append(MosaicId).Append("\n");
            sb.Append("  RestrictionKey: ").Append(RestrictionKey).Append("\n");
            sb.Append("  PreviousRestrictionValue: ").Append(PreviousRestrictionValue).Append("\n");
            sb.Append("  NewRestrictionValue: ").Append(NewRestrictionValue).Append("\n");
            sb.Append("  TargetAddress: ").Append(TargetAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MosaicAddressRestrictionTransactionBodyDTO);
        }

        /// <summary>
        /// Returns true if MosaicAddressRestrictionTransactionBodyDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of MosaicAddressRestrictionTransactionBodyDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MosaicAddressRestrictionTransactionBodyDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MosaicId == input.MosaicId ||
                    (this.MosaicId != null &&
                    this.MosaicId.Equals(input.MosaicId))
                ) && 
                (
                    this.RestrictionKey == input.RestrictionKey ||
                    (this.RestrictionKey != null &&
                    this.RestrictionKey.Equals(input.RestrictionKey))
                ) && 
                (
                    this.PreviousRestrictionValue == input.PreviousRestrictionValue ||
                    (this.PreviousRestrictionValue != null &&
                    this.PreviousRestrictionValue.Equals(input.PreviousRestrictionValue))
                ) && 
                (
                    this.NewRestrictionValue == input.NewRestrictionValue ||
                    (this.NewRestrictionValue != null &&
                    this.NewRestrictionValue.Equals(input.NewRestrictionValue))
                ) && 
                (
                    this.TargetAddress == input.TargetAddress ||
                    (this.TargetAddress != null &&
                    this.TargetAddress.Equals(input.TargetAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MosaicId != null)
                    hashCode = hashCode * 59 + this.MosaicId.GetHashCode();
                if (this.RestrictionKey != null)
                    hashCode = hashCode * 59 + this.RestrictionKey.GetHashCode();
                if (this.PreviousRestrictionValue != null)
                    hashCode = hashCode * 59 + this.PreviousRestrictionValue.GetHashCode();
                if (this.NewRestrictionValue != null)
                    hashCode = hashCode * 59 + this.NewRestrictionValue.GetHashCode();
                if (this.TargetAddress != null)
                    hashCode = hashCode * 59 + this.TargetAddress.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
