/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TransactionStatementDTO
    /// </summary>
    [DataContract]
    public partial class TransactionStatementDTO :  IEquatable<TransactionStatementDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatementDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionStatementDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatementDTO" /> class.
        /// </summary>
        /// <param name="height">Height of the blockchain. (required).</param>
        /// <param name="source">source (required).</param>
        /// <param name="receipts">Array of receipts. (required).</param>
        public TransactionStatementDTO(string height = default(string), SourceDTO source = default(SourceDTO), List<TransactionStatementDTOReceiptsInner> receipts = default(List<TransactionStatementDTOReceiptsInner>))
        {
            // to ensure "height" is required (not null)
            if (height == null)
            {
                throw new InvalidDataException("height is a required property for TransactionStatementDTO and cannot be null");
            }
            else
            {
                this.Height = height;
            }

            // to ensure "source" is required (not null)
            if (source == null)
            {
                throw new InvalidDataException("source is a required property for TransactionStatementDTO and cannot be null");
            }
            else
            {
                this.Source = source;
            }

            // to ensure "receipts" is required (not null)
            if (receipts == null)
            {
                throw new InvalidDataException("receipts is a required property for TransactionStatementDTO and cannot be null");
            }
            else
            {
                this.Receipts = receipts;
            }

        }

        /// <summary>
        /// Height of the blockchain.
        /// </summary>
        /// <value>Height of the blockchain.</value>
        [DataMember(Name="height", EmitDefaultValue=true)]
        public string Height { get; set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [DataMember(Name="source", EmitDefaultValue=true)]
        public SourceDTO Source { get; set; }

        /// <summary>
        /// Array of receipts.
        /// </summary>
        /// <value>Array of receipts.</value>
        [DataMember(Name="receipts", EmitDefaultValue=true)]
        public List<TransactionStatementDTOReceiptsInner> Receipts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionStatementDTO {\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Receipts: ").Append(Receipts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionStatementDTO);
        }

        /// <summary>
        /// Returns true if TransactionStatementDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionStatementDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionStatementDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                ) && 
                (
                    this.Source == input.Source ||
                    (this.Source != null &&
                    this.Source.Equals(input.Source))
                ) && 
                (
                    this.Receipts == input.Receipts ||
                    this.Receipts != null &&
                    input.Receipts != null &&
                    this.Receipts.SequenceEqual(input.Receipts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.Source != null)
                    hashCode = hashCode * 59 + this.Source.GetHashCode();
                if (this.Receipts != null)
                    hashCode = hashCode * 59 + this.Receipts.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
