/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TransactionInfoDTOMeta
    /// </summary>
    [DataContract]
    public partial class TransactionInfoDTOMeta :  IEquatable<TransactionInfoDTOMeta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionInfoDTOMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionInfoDTOMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionInfoDTOMeta" /> class.
        /// </summary>
        /// <param name="height">Height of the blockchain. (required).</param>
        /// <param name="hash">hash (required).</param>
        /// <param name="merkleComponentHash">merkleComponentHash (required).</param>
        /// <param name="index">Transaction index within the aggregate. (required).</param>
        /// <param name="timestamp">Number of milliseconds elapsed since the creation of the nemesis block. This value can be converted to epoch time by adding the network&#39;s &#39;epochAdjustment&#39;..</param>
        /// <param name="feeMultiplier">Fee multiplier applied to transactions contained in block..</param>
        /// <param name="aggregateHash">aggregateHash (required).</param>
        /// <param name="aggregateId">Identifier of the aggregate transaction. (required).</param>
        public TransactionInfoDTOMeta(string height = default(string), string hash = default(string), string merkleComponentHash = default(string), int index = default(int), string timestamp = default(string), long feeMultiplier = default(long), string aggregateHash = default(string), string aggregateId = default(string))
        {
            // to ensure "height" is required (not null)
            if (height == null)
            {
                throw new InvalidDataException("height is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.Height = height;
            }

            // to ensure "hash" is required (not null)
            if (hash == null)
            {
                throw new InvalidDataException("hash is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.Hash = hash;
            }

            // to ensure "merkleComponentHash" is required (not null)
            if (merkleComponentHash == null)
            {
                throw new InvalidDataException("merkleComponentHash is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.MerkleComponentHash = merkleComponentHash;
            }

            // to ensure "index" is required (not null)
            if (index == null)
            {
                throw new InvalidDataException("index is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.Index = index;
            }

            // to ensure "aggregateHash" is required (not null)
            if (aggregateHash == null)
            {
                throw new InvalidDataException("aggregateHash is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.AggregateHash = aggregateHash;
            }

            // to ensure "aggregateId" is required (not null)
            if (aggregateId == null)
            {
                throw new InvalidDataException("aggregateId is a required property for TransactionInfoDTOMeta and cannot be null");
            }
            else
            {
                this.AggregateId = aggregateId;
            }

            this.Timestamp = timestamp;
            this.FeeMultiplier = feeMultiplier;
        }

        /// <summary>
        /// Height of the blockchain.
        /// </summary>
        /// <value>Height of the blockchain.</value>
        [DataMember(Name="height", EmitDefaultValue=true)]
        public string Height { get; set; }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [DataMember(Name="hash", EmitDefaultValue=true)]
        public string Hash { get; set; }

        /// <summary>
        /// Gets or Sets MerkleComponentHash
        /// </summary>
        [DataMember(Name="merkleComponentHash", EmitDefaultValue=true)]
        public string MerkleComponentHash { get; set; }

        /// <summary>
        /// Transaction index within the aggregate.
        /// </summary>
        /// <value>Transaction index within the aggregate.</value>
        [DataMember(Name="index", EmitDefaultValue=true)]
        public int Index { get; set; }

        /// <summary>
        /// Number of milliseconds elapsed since the creation of the nemesis block. This value can be converted to epoch time by adding the network&#39;s &#39;epochAdjustment&#39;.
        /// </summary>
        /// <value>Number of milliseconds elapsed since the creation of the nemesis block. This value can be converted to epoch time by adding the network&#39;s &#39;epochAdjustment&#39;.</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public string Timestamp { get; set; }

        /// <summary>
        /// Fee multiplier applied to transactions contained in block.
        /// </summary>
        /// <value>Fee multiplier applied to transactions contained in block.</value>
        [DataMember(Name="feeMultiplier", EmitDefaultValue=false)]
        public long FeeMultiplier { get; set; }

        /// <summary>
        /// Gets or Sets AggregateHash
        /// </summary>
        [DataMember(Name="aggregateHash", EmitDefaultValue=true)]
        public string AggregateHash { get; set; }

        /// <summary>
        /// Identifier of the aggregate transaction.
        /// </summary>
        /// <value>Identifier of the aggregate transaction.</value>
        [DataMember(Name="aggregateId", EmitDefaultValue=true)]
        public string AggregateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionInfoDTOMeta {\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  MerkleComponentHash: ").Append(MerkleComponentHash).Append("\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  FeeMultiplier: ").Append(FeeMultiplier).Append("\n");
            sb.Append("  AggregateHash: ").Append(AggregateHash).Append("\n");
            sb.Append("  AggregateId: ").Append(AggregateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionInfoDTOMeta);
        }

        /// <summary>
        /// Returns true if TransactionInfoDTOMeta instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionInfoDTOMeta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionInfoDTOMeta input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Height == input.Height ||
                    (this.Height != null &&
                    this.Height.Equals(input.Height))
                ) && 
                (
                    this.Hash == input.Hash ||
                    (this.Hash != null &&
                    this.Hash.Equals(input.Hash))
                ) && 
                (
                    this.MerkleComponentHash == input.MerkleComponentHash ||
                    (this.MerkleComponentHash != null &&
                    this.MerkleComponentHash.Equals(input.MerkleComponentHash))
                ) && 
                (
                    this.Index == input.Index ||
                    (this.Index != null &&
                    this.Index.Equals(input.Index))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                ) && 
                (
                    this.FeeMultiplier == input.FeeMultiplier ||
                    (this.FeeMultiplier != null &&
                    this.FeeMultiplier.Equals(input.FeeMultiplier))
                ) && 
                (
                    this.AggregateHash == input.AggregateHash ||
                    (this.AggregateHash != null &&
                    this.AggregateHash.Equals(input.AggregateHash))
                ) && 
                (
                    this.AggregateId == input.AggregateId ||
                    (this.AggregateId != null &&
                    this.AggregateId.Equals(input.AggregateId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Height != null)
                    hashCode = hashCode * 59 + this.Height.GetHashCode();
                if (this.Hash != null)
                    hashCode = hashCode * 59 + this.Hash.GetHashCode();
                if (this.MerkleComponentHash != null)
                    hashCode = hashCode * 59 + this.MerkleComponentHash.GetHashCode();
                if (this.Index != null)
                    hashCode = hashCode * 59 + this.Index.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                if (this.FeeMultiplier != null)
                    hashCode = hashCode * 59 + this.FeeMultiplier.GetHashCode();
                if (this.AggregateHash != null)
                    hashCode = hashCode * 59 + this.AggregateHash.GetHashCode();
                if (this.AggregateId != null)
                    hashCode = hashCode * 59 + this.AggregateId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
