/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITransactionStatusRoutesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get transaction status
        /// </summary>
        /// <remarks>
        /// Returns the transaction status for a given hash.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <returns>TransactionStatusDTO</returns>
        TransactionStatusDTO GetTransactionStatus (string hash);

        /// <summary>
        /// Get transaction status
        /// </summary>
        /// <remarks>
        /// Returns the transaction status for a given hash.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <returns>ApiResponse of TransactionStatusDTO</returns>
        ApiResponse<TransactionStatusDTO> GetTransactionStatusWithHttpInfo (string hash);
        /// <summary>
        /// Get transaction statuses
        /// </summary>
        /// <remarks>
        /// Returns an array of transaction statuses for a given array of transaction hashes.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <returns>List<TransactionStatusDTO></returns>
        List<TransactionStatusDTO> GetTransactionStatuses (TransactionHashes transactionHashes);

        /// <summary>
        /// Get transaction statuses
        /// </summary>
        /// <remarks>
        /// Returns an array of transaction statuses for a given array of transaction hashes.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <returns>ApiResponse of List<TransactionStatusDTO></returns>
        ApiResponse<List<TransactionStatusDTO>> GetTransactionStatusesWithHttpInfo (TransactionHashes transactionHashes);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get transaction status
        /// </summary>
        /// <remarks>
        /// Returns the transaction status for a given hash.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TransactionStatusDTO</returns>
        System.Threading.Tasks.Task<TransactionStatusDTO> GetTransactionStatusAsync (string hash, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get transaction status
        /// </summary>
        /// <remarks>
        /// Returns the transaction status for a given hash.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TransactionStatusDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<TransactionStatusDTO>> GetTransactionStatusWithHttpInfoAsync (string hash, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get transaction statuses
        /// </summary>
        /// <remarks>
        /// Returns an array of transaction statuses for a given array of transaction hashes.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<TransactionStatusDTO></returns>
        System.Threading.Tasks.Task<List<TransactionStatusDTO>> GetTransactionStatusesAsync (TransactionHashes transactionHashes, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get transaction statuses
        /// </summary>
        /// <remarks>
        /// Returns an array of transaction statuses for a given array of transaction hashes.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;TransactionStatusDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TransactionStatusDTO>>> GetTransactionStatusesWithHttpInfoAsync (TransactionHashes transactionHashes, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TransactionStatusRoutesApi : ITransactionStatusRoutesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatusRoutesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TransactionStatusRoutesApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatusRoutesApi"/> class
        /// </summary>
        /// <returns></returns>
        public TransactionStatusRoutesApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionStatusRoutesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TransactionStatusRoutesApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get transaction status Returns the transaction status for a given hash.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <returns>TransactionStatusDTO</returns>
        public TransactionStatusDTO GetTransactionStatus (string hash)
        {
             ApiResponse<TransactionStatusDTO> localVarResponse = GetTransactionStatusWithHttpInfo(hash);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get transaction status Returns the transaction status for a given hash.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <returns>ApiResponse of TransactionStatusDTO</returns>
        public ApiResponse<TransactionStatusDTO> GetTransactionStatusWithHttpInfo (string hash)
        {
            // verify the required parameter 'hash' is set
            if (hash == null)
                throw new ApiException(400, "Missing required parameter 'hash' when calling TransactionStatusRoutesApi->GetTransactionStatus");

            var localVarPath = "/transactionStatus/{hash}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (hash != null) localVarPathParams.Add("hash", this.Configuration.ApiClient.ParameterToString(hash)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTransactionStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TransactionStatusDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TransactionStatusDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TransactionStatusDTO)));
        }

        /// <summary>
        /// Get transaction status Returns the transaction status for a given hash.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TransactionStatusDTO</returns>
        public async System.Threading.Tasks.Task<TransactionStatusDTO> GetTransactionStatusAsync (string hash, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<TransactionStatusDTO> localVarResponse = await GetTransactionStatusWithHttpInfoAsync(hash, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get transaction status Returns the transaction status for a given hash.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="hash">Transaction hash.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TransactionStatusDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TransactionStatusDTO>> GetTransactionStatusWithHttpInfoAsync (string hash, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'hash' is set
            if (hash == null)
                throw new ApiException(400, "Missing required parameter 'hash' when calling TransactionStatusRoutesApi->GetTransactionStatus");

            var localVarPath = "/transactionStatus/{hash}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (hash != null) localVarPathParams.Add("hash", this.Configuration.ApiClient.ParameterToString(hash)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTransactionStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TransactionStatusDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TransactionStatusDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TransactionStatusDTO)));
        }

        /// <summary>
        /// Get transaction statuses Returns an array of transaction statuses for a given array of transaction hashes.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <returns>List<TransactionStatusDTO></returns>
        public List<TransactionStatusDTO> GetTransactionStatuses (TransactionHashes transactionHashes)
        {
             ApiResponse<List<TransactionStatusDTO>> localVarResponse = GetTransactionStatusesWithHttpInfo(transactionHashes);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get transaction statuses Returns an array of transaction statuses for a given array of transaction hashes.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <returns>ApiResponse of List<TransactionStatusDTO></returns>
        public ApiResponse<List<TransactionStatusDTO>> GetTransactionStatusesWithHttpInfo (TransactionHashes transactionHashes)
        {
            // verify the required parameter 'transactionHashes' is set
            if (transactionHashes == null)
                throw new ApiException(400, "Missing required parameter 'transactionHashes' when calling TransactionStatusRoutesApi->GetTransactionStatuses");

            var localVarPath = "/transactionStatus";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (transactionHashes != null && transactionHashes.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(transactionHashes); // http body (model) parameter
            }
            else
            {
                localVarPostBody = transactionHashes; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTransactionStatuses", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TransactionStatusDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<TransactionStatusDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TransactionStatusDTO>)));
        }

        /// <summary>
        /// Get transaction statuses Returns an array of transaction statuses for a given array of transaction hashes.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<TransactionStatusDTO></returns>
        public async System.Threading.Tasks.Task<List<TransactionStatusDTO>> GetTransactionStatusesAsync (TransactionHashes transactionHashes, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<List<TransactionStatusDTO>> localVarResponse = await GetTransactionStatusesWithHttpInfoAsync(transactionHashes, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get transaction statuses Returns an array of transaction statuses for a given array of transaction hashes.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionHashes"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;TransactionStatusDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<TransactionStatusDTO>>> GetTransactionStatusesWithHttpInfoAsync (TransactionHashes transactionHashes, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'transactionHashes' is set
            if (transactionHashes == null)
                throw new ApiException(400, "Missing required parameter 'transactionHashes' when calling TransactionStatusRoutesApi->GetTransactionStatuses");

            var localVarPath = "/transactionStatus";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (transactionHashes != null && transactionHashes.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(transactionHashes); // http body (model) parameter
            }
            else
            {
                localVarPostBody = transactionHashes; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTransactionStatuses", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TransactionStatusDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<TransactionStatusDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TransactionStatusDTO>)));
        }

    }
}
