SymbolCsharpDualSDK: CatSdk.Nem.MultisigAccountModificationTransactionV1 Class Reference
CatSdk.Nem.MultisigAccountModificationTransactionV1 Class Reference
Public Member Functions
MultisigAccountModificationTransactionV1 ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MultisigAccountModificationTransactionV1 Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MULTISIG_ACCOUNT_MODIFICATION
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
SizePrefixedMultisigAccountModification[] Modifications [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get, set]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
Constructor & Destructor Documentation
MultisigAccountModificationTransactionV1()
CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1 () inline
References CatSdk.Nem.MultisigAccountModificationTransactionV1.Deadline, CatSdk.Nem.MultisigAccountModificationTransactionV1.EntityBodyReserved_1, CatSdk.Nem.MultisigAccountModificationTransactionV1.Fee, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.MultisigAccountModificationTransactionV1.Modifications, CatSdk.Nem.MultisigAccountModificationTransactionV1.Network, CatSdk.Nem.MultisigAccountModificationTransactionV1.Signature, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignatureSize, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKey, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKeySize, CatSdk.Nem.MultisigAccountModificationTransactionV1.Timestamp, CatSdk.Nem.MultisigAccountModificationTransactionV1.TRANSACTION_TYPE, CatSdk.Nem.MultisigAccountModificationTransactionV1.TRANSACTION_VERSION, CatSdk.Nem.MultisigAccountModificationTransactionV1.Type, and CatSdk.Nem.MultisigAccountModificationTransactionV1.Version.
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize().
Member Function Documentation
Deserialize()
static MultisigAccountModificationTransactionV1 CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MultisigAccountModificationTransactionV1.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.SizePrefixedMultisigAccountModification.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Fee, CatSdk.Nem.MultisigAccountModificationTransactionV1.Modifications, CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Network, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKey, CatSdk.Nem.MultisigAccountModificationTransactionV1.Type, and CatSdk.Nem.MultisigAccountModificationTransactionV1.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MultisigAccountModificationTransactionV1.Deadline, CatSdk.Nem.MultisigAccountModificationTransactionV1.EntityBodyReserved_1, CatSdk.Nem.MultisigAccountModificationTransactionV1.Fee, CatSdk.Nem.MultisigAccountModificationTransactionV1.Modifications, CatSdk.Nem.MultisigAccountModificationTransactionV1.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.SignatureSize, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKey, CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKeySize, CatSdk.Nem.MultisigAccountModificationTransactionV1.Type, and CatSdk.Nem.MultisigAccountModificationTransactionV1.Version.
ToString()
override string CatSdk.Nem.MultisigAccountModificationTransactionV1.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.MultisigAccountModificationTransactionV1.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
SignatureSize
readonly int CatSdk.Nem.MultisigAccountModificationTransactionV1.SignatureSize private
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKeySize private
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.MultisigAccountModificationTransactionV1.TRANSACTION_TYPE = TransactionType.MULTISIG_ACCOUNT_MODIFICATION static
Referenced by CatSdk.Nem.TransactionFactory.Deserialize(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1().
TRANSACTION_VERSION
const byte CatSdk.Nem.MultisigAccountModificationTransactionV1.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1().
Property Documentation
Deadline
Timestamp CatSdk.Nem.MultisigAccountModificationTransactionV1.Deadline get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
Fee
Amount CatSdk.Nem.MultisigAccountModificationTransactionV1.Fee get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
Modifications
SizePrefixedMultisigAccountModification [] CatSdk.Nem.MultisigAccountModificationTransactionV1.Modifications get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
Network
NetworkType CatSdk.Nem.MultisigAccountModificationTransactionV1.Network get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
Signature
Signature CatSdk.Nem.MultisigAccountModificationTransactionV1.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1().
SignerPublicKey
PublicKey CatSdk.Nem.MultisigAccountModificationTransactionV1.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
Size
uint CatSdk.Nem.MultisigAccountModificationTransactionV1.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.MultisigAccountModificationTransactionV1.Timestamp get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1().
Type
TransactionType CatSdk.Nem.MultisigAccountModificationTransactionV1.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MultisigAccountModificationTransactionV1.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"Modifications", "array[SizePrefixedMultisigAccountModification]"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.MultisigAccountModificationTransactionV1.Version get set
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), and CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs