SymbolCsharpDualSDK: CatSdk.Crypto.Crypto Class Reference
CatSdk.Crypto.Crypto Class Reference
Static Public Member Functions
static byte[] RandomBytes (byte length)
static byte[] Encrypt (string plainText, byte[] key, byte[] iv)
static ? byte[] Decrypt (byte[] encryptedMessage, byte[] key)
static string Encode (string senderPrivateKey, string recipientPub, string msg, bool isHexString=false)
static string Encode (byte[] senderPrivateKey, string recipientPub, string msg, bool isHexString=false)
static string Encode (string senderPrivateKey, byte[] recipientPub, string msg, bool isHexString=false)
static string Encode (byte[] senderPrivateKey, byte[] recipientPub, string msg, bool isHexString=false)
static ? string _Decode (byte[] recipientPrivateKey, byte[] senderPublic, byte[] payload)
static ? string Decode (string recipientPrivateKey, string senderPublic, string payload)
static ? string Decode (byte[] recipientPrivateKey, string senderPublic, string payload)
static ? string Decode (string recipientPrivateKey, byte[] senderPublic, string payload)
static ? string Decode (byte[] recipientPrivateKey, byte[] senderPublic, string payload)
static string Encrypt (string text, string key, string iv)
static string Decrypt (string text, string key, string iv)
static string EncryptString (string sourceString, string password, string salt)
static string DecryptString (string sourceString, string password, string salt)
Static Private Member Functions
static string _Encode (byte[] senderPrivateKey, byte[] recipientPub, string msg, byte[] iv)
static Aes CreateAesManaged (string key, string iv)
static void GenerateKeyFromPassword (string password, int keySize, out byte[] key, int blockSize, out byte[] iv, string salt)
Member Function Documentation
_Decode()
static ? string CatSdk.Crypto.Crypto._Decode (byte[] recipientPrivateKey, byte[] senderPublic, byte[] payload) inline static
Decode an encrypted message payload
Parameters
{string} recipientPrivate - A recipient private key
{string} senderPublic - A sender public key
{Uint8Array} payload - An encrypted message payload in bytes
{Uint8Array} tagAndIv - 16-bytes AES auth tag and 12-byte AES initialization vector
Returns
{string} - The decoded payload as hex
References CatSdk.Utils.Converter.BytesToHex(), CatSdk.Crypto.Crypto.Decrypt(), and CatSdk.Crypto.CatapultCrypto.DeriveSharedKey().
Referenced by CatSdk.Crypto.Crypto.Decode().
_Encode()
static string CatSdk.Crypto.Crypto._Encode (byte[] senderPrivateKey, byte[] recipientPub, string msg, byte[] iv) inline static private
References CatSdk.Utils.Converter.BytesToHex(), CatSdk.Crypto.CatapultCrypto.DeriveSharedKey(), and CatSdk.Crypto.Crypto.Encrypt().
Referenced by CatSdk.Crypto.Crypto.Encode().
CreateAesManaged()
static Aes CatSdk.Crypto.Crypto.CreateAesManaged (string key, string iv) inline static private
Referenced by CatSdk.Crypto.Crypto.Decrypt(), and CatSdk.Crypto.Crypto.Encrypt().
Decode() [1/4]
static ? string CatSdk.Crypto.Crypto.Decode (byte[] recipientPrivateKey, byte[] senderPublic, string payload) inline static
References CatSdk.Crypto.Crypto._Decode(), CatSdk.Utils.Converter.HexToBytes(), and CatSdk.Utils.Converter.HexToUtf8().
Decode() [2/4]
static ? string CatSdk.Crypto.Crypto.Decode (byte[] recipientPrivateKey, string senderPublic, string payload) inline static
References CatSdk.Crypto.Crypto._Decode(), CatSdk.Utils.Converter.HexToBytes(), and CatSdk.Utils.Converter.HexToUtf8().
Decode() [3/4]
static ? string CatSdk.Crypto.Crypto.Decode (string recipientPrivateKey, byte[] senderPublic, string payload) inline static
References CatSdk.Crypto.Crypto._Decode(), CatSdk.Utils.Converter.HexToBytes(), and CatSdk.Utils.Converter.HexToUtf8().
Decode() [4/4]
static ? string CatSdk.Crypto.Crypto.Decode (string recipientPrivateKey, string senderPublic, string payload) inline static
Decode an encrypted (AES-GCM algorithm) message payload
Parameters
{string} recipientPrivate - A recipient private key
{string} senderPublic - A sender public key
{string} payload - An encrypted message payload
Returns
{string?} - The decoded payload as hex
References CatSdk.Crypto.Crypto._Decode(), CatSdk.Utils.Converter.HexToBytes(), and CatSdk.Utils.Converter.HexToUtf8().
Decrypt() [1/2]
static ? byte[] CatSdk.Crypto.Crypto.Decrypt (byte[] encryptedMessage, byte[] key) inline static
Referenced by CatSdk.Crypto.Crypto._Decode().
Decrypt() [2/2]
static string CatSdk.Crypto.Crypto.Decrypt (string text, string key, string iv) inline static
References CatSdk.Crypto.Crypto.CreateAesManaged().
DecryptString()
static string CatSdk.Crypto.Crypto.DecryptString (string sourceString, string password, string salt) inline static
References CatSdk.Crypto.Crypto.GenerateKeyFromPassword().
Encode() [1/4]
static string CatSdk.Crypto.Crypto.Encode (byte[] senderPrivateKey, byte[] recipientPub, string msg, bool isHexString = false) inline static
References CatSdk.Crypto.Crypto._Encode(), CatSdk.Crypto.Crypto.RandomBytes(), and CatSdk.Utils.Converter.Utf8ToHex().
Encode() [2/4]
static string CatSdk.Crypto.Crypto.Encode (byte[] senderPrivateKey, string recipientPub, string msg, bool isHexString = false) inline static
References CatSdk.Crypto.Crypto._Encode(), CatSdk.Utils.Converter.HexToBytes(), CatSdk.Crypto.Crypto.RandomBytes(), and CatSdk.Utils.Converter.Utf8ToHex().
Encode() [3/4]
static string CatSdk.Crypto.Crypto.Encode (string senderPrivateKey, byte[] recipientPub, string msg, bool isHexString = false) inline static
References CatSdk.Crypto.Crypto._Encode(), CatSdk.Utils.Converter.HexToBytes(), CatSdk.Crypto.Crypto.RandomBytes(), and CatSdk.Utils.Converter.Utf8ToHex().
Encode() [4/4]
static string CatSdk.Crypto.Crypto.Encode (string senderPrivateKey, string recipientPub, string msg, bool isHexString = false) inline static
Encode a message using AES-GCM algorithm
Parameters
{string} senderPriv - A sender private key
{string} recipientPub - A recipient public key
{string} msg - A text message
{boolean} isHexString - Is payload string a hexadecimal string (default = false)
Returns
{string} - The encoded message
References CatSdk.Crypto.Crypto._Encode(), CatSdk.Utils.Converter.HexToBytes(), CatSdk.Crypto.Crypto.RandomBytes(), and CatSdk.Utils.Converter.Utf8ToHex().
Encrypt() [1/2]
static byte[] CatSdk.Crypto.Crypto.Encrypt (string plainText, byte[] key, byte[] iv) inline static
References CatSdk.Utils.Converter.HexToBytes().
Referenced by CatSdk.Crypto.Crypto._Encode().
Encrypt() [2/2]
static string CatSdk.Crypto.Crypto.Encrypt (string text, string key, string iv) inline static
References CatSdk.Crypto.Crypto.CreateAesManaged().
EncryptString()
static string CatSdk.Crypto.Crypto.EncryptString (string sourceString, string password, string salt) inline static
References CatSdk.Crypto.Crypto.GenerateKeyFromPassword().
GenerateKeyFromPassword()
static void CatSdk.Crypto.Crypto.GenerateKeyFromPassword (string password, int keySize, out byte[] key, int blockSize, out byte[] iv, string salt) inline static private
Referenced by CatSdk.Crypto.Crypto.DecryptString(), and CatSdk.Crypto.Crypto.EncryptString().
RandomBytes()
static byte[] CatSdk.Crypto.Crypto.RandomBytes (byte length) inline static
Generate random bytes by length
Parameters
{byte} length - The length of the random bytes
Returns
{byte[]}
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair(), and CatSdk.Crypto.Crypto.Encode().
The documentation for this class was generated from the following file:
Crypto.cs