SymbolCsharpDualSDK: CatSdk.Nem.SizePrefixedCosignature Class Reference
CatSdk.Nem.SizePrefixedCosignature Class Reference
Public Member Functions
SizePrefixedCosignature ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SizePrefixedCosignature Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
Cosignature Cosignature [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
SizePrefixedCosignature()
CatSdk.Nem.SizePrefixedCosignature.SizePrefixedCosignature () inline
References CatSdk.Nem.SizePrefixedCosignature.Cosignature.
Referenced by CatSdk.Nem.SizePrefixedCosignature.Deserialize().
Member Function Documentation
Deserialize()
static SizePrefixedCosignature CatSdk.Nem.SizePrefixedCosignature.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.SizePrefixedCosignature.SizePrefixedCosignature().
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.SizePrefixedCosignature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.Cosignature.Serialize(), and CatSdk.Nem.Cosignature.Size.
ToString()
override string CatSdk.Nem.SizePrefixedCosignature.ToString () inline
Property Documentation
Cosignature
Cosignature CatSdk.Nem.SizePrefixedCosignature.Cosignature get set
Referenced by CatSdk.Nem.SizePrefixedCosignature.SizePrefixedCosignature().
Size
uint CatSdk.Nem.SizePrefixedCosignature.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.SizePrefixedCosignature.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Cosignature", "struct:Cosignature"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs