SymbolCsharpDualSDK: CatSdk.Symbol.Cosignature Class Reference
CatSdk.Symbol.Cosignature Class Reference
Public Member Functions
Cosignature ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Cosignature Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
ulong Version [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Cosignature()
CatSdk.Symbol.Cosignature.Cosignature () inline
References CatSdk.Symbol.Cosignature.Signature, CatSdk.Symbol.Cosignature.SignerPublicKey, and CatSdk.Symbol.Cosignature.Version.
Referenced by CatSdk.Symbol.Cosignature.Deserialize().
Member Function Documentation
Deserialize()
static Cosignature CatSdk.Symbol.Cosignature.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Cosignature.Cosignature(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.Cosignature.SignerPublicKey, and CatSdk.Symbol.Cosignature.Version.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.Cosignature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.Cosignature.SignerPublicKey, and CatSdk.Symbol.Cosignature.Version.
ToString()
override string CatSdk.Symbol.Cosignature.ToString () inline
Property Documentation
Signature
Signature CatSdk.Symbol.Cosignature.Signature get set
Referenced by CatSdk.Symbol.Cosignature.Cosignature().
SignerPublicKey
PublicKey CatSdk.Symbol.Cosignature.SignerPublicKey get set
Referenced by CatSdk.Symbol.Cosignature.Cosignature(), CatSdk.Symbol.Cosignature.Deserialize(), and CatSdk.Symbol.Cosignature.Serialize().
Size
uint CatSdk.Symbol.Cosignature.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Symbol.Cosignature.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"}
    }
Implements CatSdk.IStruct.
Version
ulong CatSdk.Symbol.Cosignature.Version get set
Referenced by CatSdk.Symbol.Cosignature.Cosignature(), CatSdk.Symbol.Cosignature.Deserialize(), and CatSdk.Symbol.Cosignature.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs