SymbolCsharpDualSDK: CatSdk.Symbol.DetachedCosignature Class Reference
CatSdk.Symbol.DetachedCosignature Class Reference
Public Member Functions
DetachedCosignature ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static DetachedCosignature Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
ulong Version [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Hash256 ParentHash [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
DetachedCosignature()
CatSdk.Symbol.DetachedCosignature.DetachedCosignature () inline
References CatSdk.Symbol.DetachedCosignature.ParentHash, CatSdk.Symbol.DetachedCosignature.Signature, CatSdk.Symbol.DetachedCosignature.SignerPublicKey, and CatSdk.Symbol.DetachedCosignature.Version.
Referenced by CatSdk.Symbol.DetachedCosignature.Deserialize().
Member Function Documentation
Deserialize()
static DetachedCosignature CatSdk.Symbol.DetachedCosignature.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.DetachedCosignature.DetachedCosignature(), CatSdk.Symbol.DetachedCosignature.ParentHash, CatSdk.Symbol.DetachedCosignature.SignerPublicKey, and CatSdk.Symbol.DetachedCosignature.Version.
Serialize()
byte[] CatSdk.Symbol.DetachedCosignature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.DetachedCosignature.ParentHash, CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.DetachedCosignature.SignerPublicKey, and CatSdk.Symbol.DetachedCosignature.Version.
ToString()
override string CatSdk.Symbol.DetachedCosignature.ToString () inline
Property Documentation
ParentHash
Hash256 CatSdk.Symbol.DetachedCosignature.ParentHash get set
Referenced by CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.DetachedCosignature.DetachedCosignature(), and CatSdk.Symbol.DetachedCosignature.Serialize().
Signature
Signature CatSdk.Symbol.DetachedCosignature.Signature get set
Referenced by CatSdk.Symbol.DetachedCosignature.DetachedCosignature().
SignerPublicKey
PublicKey CatSdk.Symbol.DetachedCosignature.SignerPublicKey get set
Referenced by CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.DetachedCosignature.DetachedCosignature(), and CatSdk.Symbol.DetachedCosignature.Serialize().
Size
uint CatSdk.Symbol.DetachedCosignature.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Symbol.DetachedCosignature.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"ParentHash", "pod:Hash256"}
    }
Implements CatSdk.IStruct.
Version
ulong CatSdk.Symbol.DetachedCosignature.Version get set
Referenced by CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.DetachedCosignature.DetachedCosignature(), and CatSdk.Symbol.DetachedCosignature.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs