SymbolCsharpDualSDK: CatSdk.Symbol.MosaicFlags Class Reference
CatSdk.Symbol.MosaicFlags Class Reference
Public Member Functions
MosaicFlags (byte value=0)
bool Has (uint flag)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MosaicFlags Deserialize (BinaryReader br)
Static Public Attributes
static readonly MosaicFlags NONE = new MosaicFlags(0)
static readonly MosaicFlags SUPPLY_MUTABLE = new MosaicFlags(1)
static readonly MosaicFlags TRANSFERABLE = new MosaicFlags(2)
static readonly MosaicFlags RESTRICTABLE = new MosaicFlags(4)
static readonly MosaicFlags REVOKABLE = new MosaicFlags(8)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
MosaicFlags()
CatSdk.Symbol.MosaicFlags.MosaicFlags (byte value = 0) inline
References CatSdk.Symbol.MosaicFlags.Value.
Member Function Documentation
Deserialize()
static MosaicFlags CatSdk.Symbol.MosaicFlags.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize().
Has()
bool CatSdk.Symbol.MosaicFlags.Has (uint flag) inline
References CatSdk.Symbol.MosaicFlags.Value.
Serialize()
byte[] CatSdk.Symbol.MosaicFlags.Serialize () inline
References CatSdk.Symbol.MosaicFlags.Value.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize().
ToString()
override string CatSdk.Symbol.MosaicFlags.ToString () inline
References CatSdk.Symbol.MosaicFlags.Value.
Member Data Documentation
NONE
readonly MosaicFlags CatSdk.Symbol.MosaicFlags.NONE = new MosaicFlags(0) static
Referenced by CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.EmbeddedMosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
RESTRICTABLE
readonly MosaicFlags CatSdk.Symbol.MosaicFlags.RESTRICTABLE = new MosaicFlags(4) static
REVOKABLE
readonly MosaicFlags CatSdk.Symbol.MosaicFlags.REVOKABLE = new MosaicFlags(8) static
SUPPLY_MUTABLE
readonly MosaicFlags CatSdk.Symbol.MosaicFlags.SUPPLY_MUTABLE = new MosaicFlags(1) static
TRANSFERABLE
readonly MosaicFlags CatSdk.Symbol.MosaicFlags.TRANSFERABLE = new MosaicFlags(2) static
Property Documentation
Size
uint CatSdk.Symbol.MosaicFlags.Size get
Value
byte CatSdk.Symbol.MosaicFlags.Value get
Referenced by CatSdk.Symbol.MosaicFlags.Has(), CatSdk.Symbol.MosaicFlags.MosaicFlags(), CatSdk.Symbol.MosaicFlags.Serialize(), and CatSdk.Symbol.MosaicFlags.ToString().
The documentation for this class was generated from the following file:
Symbol/Models.cs