SymbolCsharpDualSDK: CatSdk.Symbol.NetworkType Class Reference
CatSdk.Symbol.NetworkType Class Reference
Public Member Functions
NetworkType (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static NetworkType Deserialize (BinaryReader br)
Static Public Attributes
static readonly NetworkType MAINNET = new NetworkType(104)
static readonly NetworkType TESTNET = new NetworkType(152)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
NetworkType()
CatSdk.Symbol.NetworkType.NetworkType (byte value = 0) inline
References CatSdk.Symbol.NetworkType.Value.
Member Function Documentation
Deserialize()
static NetworkType CatSdk.Symbol.NetworkType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.NetworkType.Serialize () inline
References CatSdk.Symbol.NetworkType.Value.
Referenced by CatSdk.Symbol.Transaction.Serialize(), CatSdk.Symbol.EmbeddedTransaction.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.TransferTransaction.Serialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Serialize().
ToString()
override string CatSdk.Symbol.NetworkType.ToString () inline
Member Data Documentation
MAINNET
readonly NetworkType CatSdk.Symbol.NetworkType.MAINNET = new NetworkType(104) static
Referenced by CatSdk.Symbol.AccountAddressRestrictionTransaction.AccountAddressRestrictionTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountMetadataTransaction.AccountMetadataTransaction(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.AccountMosaicRestrictionTransaction(), CatSdk.Symbol.AccountOperationRestrictionTransaction.AccountOperationRestrictionTransaction(), CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.EmbeddedAccountAddressRestrictionTransaction(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.EmbeddedAccountKeyLinkTransaction(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.EmbeddedAccountMetadataTransaction(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.EmbeddedAccountMosaicRestrictionTransaction(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.EmbeddedAccountOperationRestrictionTransaction(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.EmbeddedMosaicAddressRestrictionTransaction(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.EmbeddedMosaicDefinitionTransaction(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.EmbeddedMosaicGlobalRestrictionTransaction(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.EmbeddedMosaicMetadataTransaction(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.EmbeddedMultisigAccountModificationTransaction(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.EmbeddedNamespaceMetadataTransaction(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.EmbeddedNamespaceRegistrationTransaction(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.EmbeddedNodeKeyLinkTransaction(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), CatSdk.Symbol.EmbeddedSecretProofTransaction.EmbeddedSecretProofTransaction(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), CatSdk.Symbol.EmbeddedTransferTransaction.EmbeddedTransferTransaction(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.EmbeddedVrfKeyLinkTransaction(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.MosaicAddressRestrictionTransaction(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.MosaicGlobalRestrictionTransaction(), CatSdk.Symbol.MosaicMetadataTransaction.MosaicMetadataTransaction(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), CatSdk.Symbol.MultisigAccountModificationTransaction.MultisigAccountModificationTransaction(), CatSdk.Symbol.NamespaceMetadataTransaction.NamespaceMetadataTransaction(), CatSdk.Symbol.NamespaceRegistrationTransaction.NamespaceRegistrationTransaction(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), CatSdk.Symbol.Transaction.Transaction(), CatSdk.Symbol.TransferTransaction.TransferTransaction(), CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
TESTNET
readonly NetworkType CatSdk.Symbol.NetworkType.TESTNET = new NetworkType(152) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), and CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded().
Property Documentation
Size
uint CatSdk.Symbol.NetworkType.Size get
Value
byte CatSdk.Symbol.NetworkType.Value get
Referenced by CatSdk.Symbol.NetworkType.NetworkType(), and CatSdk.Symbol.NetworkType.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs