SymbolCsharpDualSDK: CatSdk.Symbol.SecretProofTransaction Class Reference
CatSdk.Symbol.SecretProofTransaction Class Reference
Public Member Functions
SecretProofTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SecretProofTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.SECRET_PROOF
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
UnresolvedAddress RecipientAddress [get, set]
Hash256 Secret [get, set]
LockHashAlgorithm HashAlgorithm [get, set]
byte[] Proof [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
SecretProofTransaction()
CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction () inline
References CatSdk.Symbol.SecretProofTransaction.Deadline, CatSdk.Symbol.SecretProofTransaction.EntityBodyReserved_1, CatSdk.Symbol.SecretProofTransaction.Fee, CatSdk.Symbol.SecretProofTransaction.HashAlgorithm, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.SecretProofTransaction.Network, CatSdk.Symbol.SecretProofTransaction.Proof, CatSdk.Symbol.SecretProofTransaction.RecipientAddress, CatSdk.Symbol.SecretProofTransaction.Secret, CatSdk.Symbol.LockHashAlgorithm.SHA3_256, CatSdk.Symbol.SecretProofTransaction.Signature, CatSdk.Symbol.SecretProofTransaction.SignerPublicKey, CatSdk.Symbol.SecretProofTransaction.TRANSACTION_TYPE, CatSdk.Symbol.SecretProofTransaction.TRANSACTION_VERSION, CatSdk.Symbol.SecretProofTransaction.Type, CatSdk.Symbol.SecretProofTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.SecretProofTransaction.Version.
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize().
Member Function Documentation
Deserialize()
static SecretProofTransaction CatSdk.Symbol.SecretProofTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.SecretProofTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.UnresolvedAddress.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.LockHashAlgorithm.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Fee, CatSdk.Symbol.SecretProofTransaction.HashAlgorithm, CatSdk.Symbol.SecretProofTransaction.Network, CatSdk.Symbol.SecretProofTransaction.Proof, CatSdk.Symbol.SecretProofTransaction.RecipientAddress, CatSdk.Symbol.SecretProofTransaction.Secret, CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), CatSdk.Symbol.SecretProofTransaction.SignerPublicKey, CatSdk.Symbol.SecretProofTransaction.Type, and CatSdk.Symbol.SecretProofTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.SecretProofTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.SecretProofTransaction.Deadline, CatSdk.Symbol.SecretProofTransaction.EntityBodyReserved_1, CatSdk.Symbol.SecretProofTransaction.Fee, CatSdk.Symbol.SecretProofTransaction.HashAlgorithm, CatSdk.Symbol.SecretProofTransaction.Network, CatSdk.Symbol.SecretProofTransaction.Proof, CatSdk.Symbol.SecretProofTransaction.RecipientAddress, CatSdk.Symbol.SecretProofTransaction.Secret, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.UnresolvedAddress.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.LockHashAlgorithm.Serialize(), CatSdk.Symbol.SecretProofTransaction.SignerPublicKey, CatSdk.Symbol.SecretProofTransaction.Size, CatSdk.Symbol.SecretProofTransaction.Type, CatSdk.Symbol.SecretProofTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.SecretProofTransaction.Version.
ToString()
override string CatSdk.Symbol.SecretProofTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.SecretProofTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.SecretProofTransaction.TRANSACTION_TYPE = TransactionType.SECRET_PROOF static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.SecretProofTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.SecretProofTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.SecretProofTransaction.Deadline get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Fee
Amount CatSdk.Symbol.SecretProofTransaction.Fee get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
HashAlgorithm
LockHashAlgorithm CatSdk.Symbol.SecretProofTransaction.HashAlgorithm get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.SecretProofTransaction.Network get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Proof
byte [] CatSdk.Symbol.SecretProofTransaction.Proof get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
RecipientAddress
UnresolvedAddress CatSdk.Symbol.SecretProofTransaction.RecipientAddress get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Secret
Hash256 CatSdk.Symbol.SecretProofTransaction.Secret get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Signature
Signature CatSdk.Symbol.SecretProofTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.SecretProofTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
Size
uint CatSdk.Symbol.SecretProofTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.SecretProofTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.SecretProofTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.SecretProofTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"RecipientAddress", "pod:UnresolvedAddress"},
        {"Secret", "pod:Hash256"},
        {"HashAlgorithm", "enum:LockHashAlgorithm"},
        {"Proof", "bytes_array"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.SecretProofTransaction.Version get set
Referenced by CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction(), and CatSdk.Symbol.SecretProofTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs