SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedMosaicAliasTransaction Class Reference
CatSdk.Symbol.EmbeddedMosaicAliasTransaction Class Reference
Public Member Functions
EmbeddedMosaicAliasTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedMosaicAliasTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_ALIAS
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
NamespaceId NamespaceId [get, set]
MosaicId MosaicId [get, set]
AliasAction AliasAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedMosaicAliasTransaction()
CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction () inline
References CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.MosaicId, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.NamespaceId, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Network, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Type, CatSdk.Symbol.AliasAction.UNLINK, and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedMosaicAliasTransaction CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.MosaicId.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.NamespaceId.Deserialize(), CatSdk.Symbol.AliasAction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Network, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Network, CatSdk.Symbol.MosaicId.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.NamespaceId.Serialize(), CatSdk.Symbol.AliasAction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Size, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedMosaicAliasTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_ALIAS static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction().
Property Documentation
AliasAction
AliasAction CatSdk.Symbol.EmbeddedMosaicAliasTransaction.AliasAction get set
MosaicId
MosaicId CatSdk.Symbol.EmbeddedMosaicAliasTransaction.MosaicId get set
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction().
NamespaceId
NamespaceId CatSdk.Symbol.EmbeddedMosaicAliasTransaction.NamespaceId get set
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction().
Network
NetworkType CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedMosaicAliasTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"NamespaceId", "pod:NamespaceId"},
        {"MosaicId", "pod:MosaicId"},
        {"AliasAction", "enum:AliasAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs