SymbolCsharpDualSDK: CatSdk.Nem.Message Class Reference
CatSdk.Nem.Message Class Reference
Public Member Functions
Message ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Message Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MessageType MessageType [get, set]
byte[] MessageField [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Message()
CatSdk.Nem.Message.Message () inline
References CatSdk.Nem.Message.MessageField, and CatSdk.Nem.MessageType.PLAIN.
Referenced by CatSdk.Nem.Message.Deserialize().
Member Function Documentation
Deserialize()
static Message CatSdk.Nem.Message.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MessageType.Deserialize(), CatSdk.Nem.Message.Message(), and CatSdk.Nem.Message.MessageField.
Referenced by CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.Message.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.Message.MessageField, and CatSdk.Nem.MessageType.Serialize().
Referenced by CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
ToString()
override string CatSdk.Nem.Message.ToString () inline
Property Documentation
MessageField
byte [] CatSdk.Nem.Message.MessageField get set
Referenced by CatSdk.Nem.Message.Deserialize(), CatSdk.Nem.Message.Message(), and CatSdk.Nem.Message.Serialize().
MessageType
MessageType CatSdk.Nem.Message.MessageType get set
Size
uint CatSdk.Nem.Message.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.Message.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"MessageType", "enum:MessageType"},
        {"Message", "bytes_array"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs