SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedTransaction Class Reference
CatSdk.Symbol.EmbeddedTransaction Class Reference
Public Member Functions
EmbeddedTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedTransaction Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedTransaction()
CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction () inline
References CatSdk.Symbol.TransactionType.ACCOUNT_KEY_LINK, CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedTransaction.EntityBodyReserved_1, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedTransaction.Network, CatSdk.Symbol.EmbeddedTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedTransaction.Type, and CatSdk.Symbol.EmbeddedTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedTransaction CatSdk.Symbol.EmbeddedTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), CatSdk.Symbol.EmbeddedTransaction.Network, CatSdk.Symbol.EmbeddedTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedTransaction.Type, and CatSdk.Symbol.EmbeddedTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedTransaction.Network, CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.EmbeddedTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedTransaction.Size, CatSdk.Symbol.EmbeddedTransaction.Type, and CatSdk.Symbol.EmbeddedTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
Property Documentation
Network
NetworkType CatSdk.Symbol.EmbeddedTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), and CatSdk.Symbol.EmbeddedTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs