SymbolCsharpDualSDK: CatSdk.Symbol.MosaicSupplyChangeTransaction Class Reference
CatSdk.Symbol.MosaicSupplyChangeTransaction Class Reference
Public Member Functions
MosaicSupplyChangeTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicSupplyChangeTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
UnresolvedMosaicId MosaicId [get, set]
Amount Delta [get, set]
MosaicSupplyChangeAction Action [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
MosaicSupplyChangeTransaction()
CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction () inline
References CatSdk.Symbol.MosaicSupplyChangeTransaction.Action, CatSdk.Symbol.MosaicSupplyChangeTransaction.Deadline, CatSdk.Symbol.MosaicSupplyChangeAction.DECREASE, CatSdk.Symbol.MosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.MosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicSupplyChangeTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.MosaicSupplyChangeTransaction.Network, CatSdk.Symbol.MosaicSupplyChangeTransaction.Signature, CatSdk.Symbol.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicSupplyChangeTransaction.TRANSACTION_VERSION, CatSdk.Symbol.MosaicSupplyChangeTransaction.Type, CatSdk.Symbol.MosaicSupplyChangeTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicSupplyChangeTransaction CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.MosaicSupplyChangeTransaction.Action, CatSdk.Symbol.MosaicSupplyChangeTransaction.Deadline, CatSdk.Symbol.MosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.UnresolvedMosaicId.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeAction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Fee, CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Network, CatSdk.Symbol.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyChangeTransaction.Type, and CatSdk.Symbol.MosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.MosaicSupplyChangeTransaction.Action, CatSdk.Symbol.MosaicSupplyChangeTransaction.Deadline, CatSdk.Symbol.MosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.MosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicSupplyChangeTransaction.Fee, CatSdk.Symbol.MosaicSupplyChangeTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.MosaicId.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.MosaicSupplyChangeAction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyChangeTransaction.Size, CatSdk.Symbol.MosaicSupplyChangeTransaction.Type, CatSdk.Symbol.MosaicSupplyChangeTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicSupplyChangeTransaction.Version.
ToString()
override string CatSdk.Symbol.MosaicSupplyChangeTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.MosaicSupplyChangeTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.MosaicSupplyChangeTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.MosaicSupplyChangeTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.MosaicSupplyChangeTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Property Documentation
Action
MosaicSupplyChangeAction CatSdk.Symbol.MosaicSupplyChangeTransaction.Action get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Deadline
Timestamp CatSdk.Symbol.MosaicSupplyChangeTransaction.Deadline get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Delta
Amount CatSdk.Symbol.MosaicSupplyChangeTransaction.Delta get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Fee
Amount CatSdk.Symbol.MosaicSupplyChangeTransaction.Fee get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
MosaicId
UnresolvedMosaicId CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicId get set
Network
NetworkType CatSdk.Symbol.MosaicSupplyChangeTransaction.Network get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Signature
Signature CatSdk.Symbol.MosaicSupplyChangeTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.MosaicSupplyChangeTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Size
uint CatSdk.Symbol.MosaicSupplyChangeTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.MosaicSupplyChangeTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.MosaicSupplyChangeTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"MosaicId", "pod:UnresolvedMosaicId"},
        {"Delta", "pod:Amount"},
        {"Action", "enum:MosaicSupplyChangeAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.MosaicSupplyChangeTransaction.Version get set
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs