SymbolCsharpDualSDK: CatSdk.Symbol.Signature Class Reference
CatSdk.Symbol.Signature Class Reference
Public Member Functions
Signature (byte[]? signature=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Signature Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 64
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Signature()
CatSdk.Symbol.Signature.Signature (byte?[] signature = null) inline
Member Function Documentation
Deserialize()
static Signature CatSdk.Symbol.Signature.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.Cosignature.Deserialize(), CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), and CatSdk.Symbol.TransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.Signature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Symbol.Transaction.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.Cosignature.Serialize(), CatSdk.Symbol.DetachedCosignature.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), and CatSdk.Symbol.TransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.Signature.SIZE = 64 static
The documentation for this class was generated from the following file:
Symbol/Models.cs