SymbolCsharpDualSDK: CatSdk.Nem.MosaicSupplyChangeTransaction Class Reference
CatSdk.Nem.MosaicSupplyChangeTransaction Class Reference
Public Member Functions
MosaicSupplyChangeTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicSupplyChangeTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
MosaicId MosaicId [get, set]
MosaicSupplyChangeAction Action [get, set]
Amount Delta [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get, set]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
Constructor & Destructor Documentation
MosaicSupplyChangeTransaction()
CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction () inline
References CatSdk.Nem.MosaicSupplyChangeTransaction.Action, CatSdk.Nem.MosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.MosaicSupplyChangeTransaction.Delta, CatSdk.Nem.MosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Nem.MosaicSupplyChangeTransaction.Fee, CatSdk.Nem.MosaicSupplyChangeAction.INCREASE, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicId, CatSdk.Nem.MosaicSupplyChangeTransaction.Network, CatSdk.Nem.MosaicSupplyChangeTransaction.Signature, CatSdk.Nem.MosaicSupplyChangeTransaction.SignatureSize, CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKeySize, CatSdk.Nem.MosaicSupplyChangeTransaction.Timestamp, CatSdk.Nem.MosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Nem.MosaicSupplyChangeTransaction.TRANSACTION_VERSION, CatSdk.Nem.MosaicSupplyChangeTransaction.Type, and CatSdk.Nem.MosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicSupplyChangeTransaction CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MosaicSupplyChangeTransaction.Action, CatSdk.Nem.MosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.MosaicSupplyChangeTransaction.Delta, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.MosaicId.Deserialize(), CatSdk.Nem.MosaicSupplyChangeAction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Fee, CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), CatSdk.Nem.MosaicSupplyChangeTransaction.Network, CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.MosaicSupplyChangeTransaction.Type, and CatSdk.Nem.MosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicSupplyChangeTransaction.Action, CatSdk.Nem.MosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.MosaicSupplyChangeTransaction.Delta, CatSdk.Nem.MosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Nem.MosaicSupplyChangeTransaction.Fee, CatSdk.Nem.MosaicSupplyChangeTransaction.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.MosaicId.Serialize(), CatSdk.Nem.MosaicSupplyChangeAction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.SignatureSize, CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKeySize, CatSdk.Nem.MosaicId.Size, CatSdk.Nem.MosaicSupplyChangeTransaction.Type, and CatSdk.Nem.MosaicSupplyChangeTransaction.Version.
ToString()
override string CatSdk.Nem.MosaicSupplyChangeTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.MosaicSupplyChangeTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
SignatureSize
readonly int CatSdk.Nem.MosaicSupplyChangeTransaction.SignatureSize private
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.MosaicSupplyChangeTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE static
Referenced by CatSdk.Nem.TransactionFactory.Deserialize(), and CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
TRANSACTION_VERSION
const byte CatSdk.Nem.MosaicSupplyChangeTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
Property Documentation
Action
MosaicSupplyChangeAction CatSdk.Nem.MosaicSupplyChangeTransaction.Action get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
Deadline
Timestamp CatSdk.Nem.MosaicSupplyChangeTransaction.Deadline get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
Delta
Amount CatSdk.Nem.MosaicSupplyChangeTransaction.Delta get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
Fee
Amount CatSdk.Nem.MosaicSupplyChangeTransaction.Fee get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
MosaicId
MosaicId CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicId get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
Network
NetworkType CatSdk.Nem.MosaicSupplyChangeTransaction.Network get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
Signature
Signature CatSdk.Nem.MosaicSupplyChangeTransaction.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
SignerPublicKey
PublicKey CatSdk.Nem.MosaicSupplyChangeTransaction.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
Size
uint CatSdk.Nem.MosaicSupplyChangeTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.MosaicSupplyChangeTransaction.Timestamp get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
Type
TransactionType CatSdk.Nem.MosaicSupplyChangeTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicSupplyChangeTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"MosaicId", "struct:MosaicId"},
        {"Action", "enum:MosaicSupplyChangeAction"},
        {"Delta", "pod:Amount"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.MosaicSupplyChangeTransaction.Version get set
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs