SymbolCsharpDualSDK: CatSdk.Symbol.MosaicSupplyRevocationTransaction Class Reference
CatSdk.Symbol.MosaicSupplyRevocationTransaction Class Reference
Public Member Functions
MosaicSupplyRevocationTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicSupplyRevocationTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_REVOCATION
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
UnresolvedAddress SourceAddress [get, set]
UnresolvedMosaic Mosaic [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
MosaicSupplyRevocationTransaction()
CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction () inline
References CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deadline, CatSdk.Symbol.MosaicSupplyRevocationTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Signature, CatSdk.Symbol.MosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.MosaicSupplyRevocationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicSupplyRevocationTransaction.TRANSACTION_VERSION, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Type, CatSdk.Symbol.MosaicSupplyRevocationTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Version.
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicSupplyRevocationTransaction CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.UnresolvedAddress.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Fee, CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.MosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Type, and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deadline, CatSdk.Symbol.MosaicSupplyRevocationTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Fee, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.UnresolvedAddress.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Size, CatSdk.Symbol.MosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.MosaicSupplyRevocationTransaction.Type, CatSdk.Symbol.MosaicSupplyRevocationTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Version.
ToString()
override string CatSdk.Symbol.MosaicSupplyRevocationTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.MosaicSupplyRevocationTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.MosaicSupplyRevocationTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_REVOCATION static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.MosaicSupplyRevocationTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.MosaicSupplyRevocationTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deadline get set
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Fee
Amount CatSdk.Symbol.MosaicSupplyRevocationTransaction.Fee get set
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Mosaic
UnresolvedMosaic CatSdk.Symbol.MosaicSupplyRevocationTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.MosaicSupplyRevocationTransaction.Network get set
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Signature
Signature CatSdk.Symbol.MosaicSupplyRevocationTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.MosaicSupplyRevocationTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Size
uint CatSdk.Symbol.MosaicSupplyRevocationTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
SourceAddress
UnresolvedAddress CatSdk.Symbol.MosaicSupplyRevocationTransaction.SourceAddress get set
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.MosaicSupplyRevocationTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.MosaicSupplyRevocationTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"SourceAddress", "pod:UnresolvedAddress"},
        {"Mosaic", "struct:UnresolvedMosaic"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.MosaicSupplyRevocationTransaction.Version get set
Referenced by CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.MosaicSupplyRevocationTransaction(), and CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs