SymbolCsharpDualSDK: CatSdk.Symbol.MosaicSupplyChangeAction Class Reference
CatSdk.Symbol.MosaicSupplyChangeAction Class Reference
Public Member Functions
MosaicSupplyChangeAction (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MosaicSupplyChangeAction Deserialize (BinaryReader br)
Static Public Attributes
static readonly MosaicSupplyChangeAction DECREASE = new MosaicSupplyChangeAction(0)
static readonly MosaicSupplyChangeAction INCREASE = new MosaicSupplyChangeAction(1)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
MosaicSupplyChangeAction()
CatSdk.Symbol.MosaicSupplyChangeAction.MosaicSupplyChangeAction (byte value = 0) inline
References CatSdk.Symbol.MosaicSupplyChangeAction.Value.
Member Function Documentation
Deserialize()
static MosaicSupplyChangeAction CatSdk.Symbol.MosaicSupplyChangeAction.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicSupplyChangeAction.Serialize () inline
References CatSdk.Symbol.MosaicSupplyChangeAction.Value.
Referenced by CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
ToString()
override string CatSdk.Symbol.MosaicSupplyChangeAction.ToString () inline
Member Data Documentation
DECREASE
readonly MosaicSupplyChangeAction CatSdk.Symbol.MosaicSupplyChangeAction.DECREASE = new MosaicSupplyChangeAction(0) static
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction().
INCREASE
readonly MosaicSupplyChangeAction CatSdk.Symbol.MosaicSupplyChangeAction.INCREASE = new MosaicSupplyChangeAction(1) static
Property Documentation
Size
uint CatSdk.Symbol.MosaicSupplyChangeAction.Size get
Value
byte CatSdk.Symbol.MosaicSupplyChangeAction.Value get
Referenced by CatSdk.Symbol.MosaicSupplyChangeAction.MosaicSupplyChangeAction(), and CatSdk.Symbol.MosaicSupplyChangeAction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs