SymbolCsharpDualSDK: CatSdk.Symbol.Factory.TransactionsFactory Class Reference
CatSdk.Symbol.Factory.TransactionsFactory Class Reference
Public Member Functions
TransactionsFactory (Network network, Dictionary< Type, Func< object, object > >? typeRuleOverrides=null)
ITransaction Create (Dictionary< string, object > transactionDescriptor)
IBaseTransaction CreateEmbedded (Dictionary< string, object > transactionDescriptor)
string AttachSignature (ITransaction transaction, Signature signature)
ITransaction AttachSignatureTransaction (ITransaction transaction, Signature signature)
Public Attributes
readonly Network Network
Static Private Member Functions
static ? UnresolvedAddress SymbolTypeConverter (object value)
static byte[] RawAddressToBytes (string rawAddress)
static RuleBasedTransactionFactory BuildRules (Dictionary< Type, Func< object, object > >? typeRuleOverrides)
static string TransactionTypeToString (TransactionType type)
Private Attributes
readonly RuleBasedTransactionFactory Factory
Detailed Description
Factory for creating Symbol transactions.
Constructor & Destructor Documentation
TransactionsFactory()
CatSdk.Symbol.Factory.TransactionsFactory.TransactionsFactory (Network network, Dictionary< Type, Func< object, object > >? typeRuleOverrides = null) inline
Creates a factory for the specified network.
Parameters
{Network} network Symbol network.
{Dictionary} typeRuleOverrides Type rule overrides.
References CatSdk.Symbol.Factory.TransactionsFactory.BuildRules(), and CatSdk.Symbol.Factory.TransactionsFactory.Factory.
Member Function Documentation
AttachSignature()
string CatSdk.Symbol.Factory.TransactionsFactory.AttachSignature (ITransaction transaction, Signature signature) inline
Attaches a signature to a transaction.
Parameters
{ITransaction} transaction Transaction object.
{Signature} signature Signature to attach.
Returns
{string} JSON transaction payload.
References CatSdk.Utils.Converter.BytesToHex(), and CatSdk.ISerializer.Serialize().
AttachSignatureTransaction()
ITransaction CatSdk.Symbol.Factory.TransactionsFactory.AttachSignatureTransaction (ITransaction transaction, Signature signature) inline
BuildRules()
static RuleBasedTransactionFactory CatSdk.Symbol.Factory.TransactionsFactory.BuildRules (Dictionary< Type, Func< object, object > >? typeRuleOverrides) inline static private
References CatSdk.Symbol.Factory.TransactionsFactory.RawAddressToBytes().
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionsFactory().
Create()
ITransaction CatSdk.Symbol.Factory.TransactionsFactory.Create (Dictionary< string, object > transactionDescriptor) inline
Creates a transaction from a transaction descriptor.
Parameters
{Dictionary} transactionDescriptor Transaction descriptor.
Returns
{ITransaction} Newly created transaction.
References CatSdk.Symbol.TransactionFactory.CreateByName(), CatSdk.Symbol.Factory.TransactionsFactory.Factory, CatSdk.Symbol.IdGenerator.GenerateNamespaceId(), CatSdk.Symbol.TransactionType.MOSAIC_DEFINITION, CatSdk.Symbol.TransactionType.NAMESPACE_REGISTRATION, CatSdk.BaseNetwork< T >.PublicKeyToAddress(), CatSdk.Symbol.NetworkType.TESTNET, and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
CreateEmbedded()
IBaseTransaction CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded (Dictionary< string, object > transactionDescriptor) inline
Creates an embedded transaction from a transaction descriptor.
Parameters
{Dictionary} transactionDescriptor Transaction descriptor.
Returns
{IBaseTransaction} Newly created transaction.
References CatSdk.Symbol.EmbeddedTransactionFactory.CreateByName(), CatSdk.Symbol.Factory.TransactionsFactory.Factory, CatSdk.Symbol.IdGenerator.GenerateNamespaceId(), CatSdk.Symbol.TransactionType.MOSAIC_DEFINITION, CatSdk.Symbol.TransactionType.NAMESPACE_REGISTRATION, CatSdk.BaseNetwork< T >.PublicKeyToAddress(), CatSdk.Symbol.NetworkType.TESTNET, and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
RawAddressToBytes()
static byte[] CatSdk.Symbol.Factory.TransactionsFactory.RawAddressToBytes (string rawAddress) inline static private
References CatSdk.Utils.Base32.Decode().
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.BuildRules().
SymbolTypeConverter()
static ? UnresolvedAddress CatSdk.Symbol.Factory.TransactionsFactory.SymbolTypeConverter (object value) inline static private
TransactionTypeToString()
static string CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString (TransactionType type) inline static private
References CatSdk.Symbol.TransactionType.ACCOUNT_ADDRESS_RESTRICTION, CatSdk.Symbol.TransactionType.ACCOUNT_KEY_LINK, CatSdk.Symbol.TransactionType.ACCOUNT_METADATA, CatSdk.Symbol.TransactionType.ACCOUNT_MOSAIC_RESTRICTION, CatSdk.Symbol.TransactionType.ACCOUNT_OPERATION_RESTRICTION, CatSdk.Symbol.TransactionType.ADDRESS_ALIAS, CatSdk.Symbol.TransactionType.AGGREGATE_BONDED, CatSdk.Symbol.TransactionType.AGGREGATE_COMPLETE, CatSdk.Symbol.TransactionType.HASH_LOCK, CatSdk.Symbol.TransactionType.MOSAIC_ADDRESS_RESTRICTION, CatSdk.Symbol.TransactionType.MOSAIC_ALIAS, CatSdk.Symbol.TransactionType.MOSAIC_DEFINITION, CatSdk.Symbol.TransactionType.MOSAIC_GLOBAL_RESTRICTION, CatSdk.Symbol.TransactionType.MOSAIC_METADATA, CatSdk.Symbol.TransactionType.MOSAIC_SUPPLY_CHANGE, CatSdk.Symbol.TransactionType.MOSAIC_SUPPLY_REVOCATION, CatSdk.Symbol.TransactionType.MULTISIG_ACCOUNT_MODIFICATION, CatSdk.Symbol.TransactionType.NAMESPACE_METADATA, CatSdk.Symbol.TransactionType.NAMESPACE_REGISTRATION, CatSdk.Symbol.TransactionType.NODE_KEY_LINK, CatSdk.Symbol.TransactionType.SECRET_LOCK, CatSdk.Symbol.TransactionType.SECRET_PROOF, CatSdk.Symbol.TransactionType.TRANSFER, CatSdk.Symbol.TransactionType.VOTING_KEY_LINK, and CatSdk.Symbol.TransactionType.VRF_KEY_LINK.
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), and CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded().
Member Data Documentation
Factory
readonly RuleBasedTransactionFactory CatSdk.Symbol.Factory.TransactionsFactory.Factory private
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionsFactory().
Network
readonly Network CatSdk.Symbol.Factory.TransactionsFactory.Network
The documentation for this class was generated from the following file:
Symbol/Factory/TransactionsFactory.cs