SymbolCsharpDualSDK: CatSdk.RuleBasedTransactionFactory Class Reference
CatSdk.RuleBasedTransactionFactory Class Reference
Public Member Functions
RuleBasedTransactionFactory (List< Type > module, Func< string, byte[]> rawAddressToBytes, Func< object, object?>? typeConverter=null, Dictionary< Type, Func< object, object > >? typeRuleOverrides=null)
T CreateFromFactory< T > (Func< string, T > factory, Dictionary< string, object > descriptor)
void AddPodParser (string name, Type podClass)
void AddArrayParser (string name)
void AddFlagsParser (string name)
void AddEnumParser (string name)
void AddStructParser (string name)
void Autodetect ()
Private Member Functions
TransactionDescriptorProcessor CreateProcessor (Dictionary< string, object > descriptor)
Static Private Member Functions
static ? object TypeConverterFactory (IEnumerable< Type > module, Func< object, object?>? customTypeConverter, object? value)
static Dictionary< string, string > BuildTypeHintsMap (IStruct structValue)
static Dictionary< string, int > BuildEnumStringToValueMap (Type enumClass)
static int NameToEnumValue (IReadOnlyDictionary< string, int > mapping, Type enumType, string enumValueName)
Private Attributes
readonly List< Type > Module
readonly Dictionary< string, Func< object, object > > Rules
readonly? Func< object, object?> TypeConverter
readonly? Dictionary< Type, Func< object, object > > TypeRuleOverrides
readonly Func< string, byte[]> RawAddressToBytes
Detailed Description
Rule based transaction factory.
Constructor & Destructor Documentation
RuleBasedTransactionFactory()
CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory (List< Type > module, Func< string, byte[]> rawAddressToBytes, Func< object, object?>? typeConverter = null, Dictionary< Type, Func< object, object > >? typeRuleOverrides = null) inline
Creates a rule based transaction factory for use with catbuffer generated code.
Parameters
{List&lt;Type&gt;} module Catbuffer generated module.
{Func} typeConverter Type converter.
{Dictionary} typeRuleOverrides Type rule overrides.
References CatSdk.RuleBasedTransactionFactory.Module, CatSdk.RuleBasedTransactionFactory.RawAddressToBytes, CatSdk.RuleBasedTransactionFactory.Rules, CatSdk.RuleBasedTransactionFactory.TypeConverter, CatSdk.RuleBasedTransactionFactory.TypeConverterFactory(), and CatSdk.RuleBasedTransactionFactory.TypeRuleOverrides.
Member Function Documentation
AddArrayParser()
void CatSdk.RuleBasedTransactionFactory.AddArrayParser (string name) inline
Creates array type parser, based on some existing element type parser.
Parameters
{string} name Class name.
References CatSdk.RuleBasedTransactionFactory.Module, and CatSdk.RuleBasedTransactionFactory.Rules.
AddEnumParser()
void CatSdk.RuleBasedTransactionFactory.AddEnumParser (string name) inline
Creates enum type parser.
Parameters
{string} name Class name.
References CatSdk.RuleBasedTransactionFactory.BuildEnumStringToValueMap(), CatSdk.RuleBasedTransactionFactory.Module, CatSdk.RuleBasedTransactionFactory.NameToEnumValue(), and CatSdk.RuleBasedTransactionFactory.Rules.
AddFlagsParser()
void CatSdk.RuleBasedTransactionFactory.AddFlagsParser (string name) inline
Creates flag type parser.
Parameters
{string} name Class name.
References CatSdk.RuleBasedTransactionFactory.BuildEnumStringToValueMap(), CatSdk.RuleBasedTransactionFactory.Module, CatSdk.RuleBasedTransactionFactory.NameToEnumValue(), and CatSdk.RuleBasedTransactionFactory.Rules.
AddPodParser()
void CatSdk.RuleBasedTransactionFactory.AddPodParser (string name, Type podClass) inline
Creates wrapper for SDK POD types.
Parameters
{string} name Class name.
{Type} PodClass Class type.
References CatSdk.Utils.Converter.HexToBytes(), CatSdk.Utils.Converter.IsHexString(), CatSdk.RuleBasedTransactionFactory.RawAddressToBytes, CatSdk.RuleBasedTransactionFactory.Rules, and CatSdk.RuleBasedTransactionFactory.TypeRuleOverrides.
Referenced by CatSdk.RuleBasedTransactionFactory.Autodetect().
AddStructParser()
void CatSdk.RuleBasedTransactionFactory.AddStructParser (string name) inline
Creates struct parser (to allow nested parsing).
Parameters
{string} name Class name.
References CatSdk.RuleBasedTransactionFactory.BuildTypeHintsMap(), CatSdk.TransactionDescriptorProcessor.CopyTo(), CatSdk.RuleBasedTransactionFactory.CreateProcessor(), CatSdk.RuleBasedTransactionFactory.Module, CatSdk.RuleBasedTransactionFactory.Rules, and CatSdk.TransactionDescriptorProcessor.SetTypeHints().
Autodetect()
void CatSdk.RuleBasedTransactionFactory.Autodetect () inline
Autodetects rules using reflection.
References CatSdk.RuleBasedTransactionFactory.AddPodParser(), and CatSdk.RuleBasedTransactionFactory.Module.
BuildEnumStringToValueMap()
static Dictionary< string, int > CatSdk.RuleBasedTransactionFactory.BuildEnumStringToValueMap (Type enumClass) inline static private
Referenced by CatSdk.RuleBasedTransactionFactory.AddEnumParser(), and CatSdk.RuleBasedTransactionFactory.AddFlagsParser().
BuildTypeHintsMap()
static Dictionary< string, string > CatSdk.RuleBasedTransactionFactory.BuildTypeHintsMap (IStruct structValue) inline static private
References CatSdk.IStruct.TypeHints.
Referenced by CatSdk.RuleBasedTransactionFactory.AddStructParser(), and CatSdk.RuleBasedTransactionFactory.CreateFromFactory< T >().
CreateFromFactory< T >()
T CatSdk.RuleBasedTransactionFactory.CreateFromFactory< T > (Func< string, T > factory, Dictionary< string, object > descriptor) inline
Creates an entity from a descriptor using a factory.
Parameters
{Func} factory Factory function.
{Dictionary} descriptor Entity descriptor.
Returns
{T} Newly created entity.
Type Constraints
T : IStruct
References CatSdk.RuleBasedTransactionFactory.BuildTypeHintsMap(), and CatSdk.RuleBasedTransactionFactory.CreateProcessor().
CreateProcessor()
TransactionDescriptorProcessor CatSdk.RuleBasedTransactionFactory.CreateProcessor (Dictionary< string, object > descriptor) inline private
References CatSdk.RuleBasedTransactionFactory.Rules, and CatSdk.RuleBasedTransactionFactory.TypeConverter.
Referenced by CatSdk.RuleBasedTransactionFactory.AddStructParser(), and CatSdk.RuleBasedTransactionFactory.CreateFromFactory< T >().
NameToEnumValue()
static int CatSdk.RuleBasedTransactionFactory.NameToEnumValue (IReadOnlyDictionary< string, int > mapping, Type enumType, string enumValueName) inline static private
Referenced by CatSdk.RuleBasedTransactionFactory.AddEnumParser(), and CatSdk.RuleBasedTransactionFactory.AddFlagsParser().
TypeConverterFactory()
static ? object CatSdk.RuleBasedTransactionFactory.TypeConverterFactory (IEnumerable< Type > module, Func< object, object?>? customTypeConverter, object? value) inline static private
Referenced by CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
Member Data Documentation
Module
readonly List<Type> CatSdk.RuleBasedTransactionFactory.Module private
Referenced by CatSdk.RuleBasedTransactionFactory.AddArrayParser(), CatSdk.RuleBasedTransactionFactory.AddEnumParser(), CatSdk.RuleBasedTransactionFactory.AddFlagsParser(), CatSdk.RuleBasedTransactionFactory.AddStructParser(), CatSdk.RuleBasedTransactionFactory.Autodetect(), and CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
RawAddressToBytes
readonly Func<string, byte[]> CatSdk.RuleBasedTransactionFactory.RawAddressToBytes private
Referenced by CatSdk.RuleBasedTransactionFactory.AddPodParser(), and CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
Rules
readonly Dictionary<string, Func<object, object> > CatSdk.RuleBasedTransactionFactory.Rules private
Referenced by CatSdk.RuleBasedTransactionFactory.AddArrayParser(), CatSdk.RuleBasedTransactionFactory.AddEnumParser(), CatSdk.RuleBasedTransactionFactory.AddFlagsParser(), CatSdk.RuleBasedTransactionFactory.AddPodParser(), CatSdk.RuleBasedTransactionFactory.AddStructParser(), CatSdk.RuleBasedTransactionFactory.CreateProcessor(), and CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
TypeConverter
readonly? Func<object, object?> CatSdk.RuleBasedTransactionFactory.TypeConverter private
Referenced by CatSdk.RuleBasedTransactionFactory.CreateProcessor(), and CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
TypeRuleOverrides
readonly? Dictionary<Type, Func<object, object> > CatSdk.RuleBasedTransactionFactory.TypeRuleOverrides private
Referenced by CatSdk.RuleBasedTransactionFactory.AddPodParser(), and CatSdk.RuleBasedTransactionFactory.RuleBasedTransactionFactory().
The documentation for this class was generated from the following file:
RuleBasedTransactionFactory.cs