SymbolCsharpDualSDK: CatSdk.Symbol.MosaicDefinitionTransaction Class Reference
CatSdk.Symbol.MosaicDefinitionTransaction Class Reference
Public Member Functions
MosaicDefinitionTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicDefinitionTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_DEFINITION
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
MosaicId Id [get, set]
BlockDuration Duration [get, set]
MosaicNonce Nonce [get, set]
MosaicFlags Flags [get, set]
byte Divisibility [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
MosaicDefinitionTransaction()
CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction () inline
References CatSdk.Symbol.MosaicDefinitionTransaction.Deadline, CatSdk.Symbol.MosaicDefinitionTransaction.Divisibility, CatSdk.Symbol.MosaicDefinitionTransaction.Duration, CatSdk.Symbol.MosaicDefinitionTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicDefinitionTransaction.Fee, CatSdk.Symbol.MosaicDefinitionTransaction.Flags, CatSdk.Symbol.MosaicDefinitionTransaction.Id, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.MosaicDefinitionTransaction.Network, CatSdk.Symbol.MosaicDefinitionTransaction.Nonce, CatSdk.Symbol.MosaicFlags.NONE, CatSdk.Symbol.MosaicDefinitionTransaction.Signature, CatSdk.Symbol.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Symbol.MosaicDefinitionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicDefinitionTransaction.TRANSACTION_VERSION, CatSdk.Symbol.MosaicDefinitionTransaction.Type, CatSdk.Symbol.MosaicDefinitionTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicDefinitionTransaction.Version.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicDefinitionTransaction CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.MosaicDefinitionTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.BlockDuration.Deserialize(), CatSdk.Symbol.MosaicId.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.MosaicNonce.Deserialize(), CatSdk.Symbol.MosaicFlags.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Divisibility, CatSdk.Symbol.MosaicDefinitionTransaction.Duration, CatSdk.Symbol.MosaicDefinitionTransaction.Fee, CatSdk.Symbol.MosaicDefinitionTransaction.Flags, CatSdk.Symbol.MosaicDefinitionTransaction.Id, CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), CatSdk.Symbol.MosaicDefinitionTransaction.Network, CatSdk.Symbol.MosaicDefinitionTransaction.Nonce, CatSdk.Symbol.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Symbol.MosaicDefinitionTransaction.Type, and CatSdk.Symbol.MosaicDefinitionTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicDefinitionTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.MosaicDefinitionTransaction.Deadline, CatSdk.Symbol.MosaicDefinitionTransaction.Divisibility, CatSdk.Symbol.MosaicDefinitionTransaction.Duration, CatSdk.Symbol.MosaicDefinitionTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicDefinitionTransaction.Fee, CatSdk.Symbol.MosaicDefinitionTransaction.Flags, CatSdk.Symbol.MosaicDefinitionTransaction.Id, CatSdk.Symbol.MosaicDefinitionTransaction.Network, CatSdk.Symbol.MosaicDefinitionTransaction.Nonce, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.BlockDuration.Serialize(), CatSdk.Symbol.MosaicId.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.MosaicNonce.Serialize(), CatSdk.Symbol.MosaicFlags.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Symbol.MosaicDefinitionTransaction.Size, CatSdk.Symbol.MosaicDefinitionTransaction.Type, CatSdk.Symbol.MosaicDefinitionTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicDefinitionTransaction.Version.
ToString()
override string CatSdk.Symbol.MosaicDefinitionTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.MosaicDefinitionTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.MosaicDefinitionTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_DEFINITION static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.MosaicDefinitionTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.MosaicDefinitionTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.MosaicDefinitionTransaction.Deadline get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Divisibility
byte CatSdk.Symbol.MosaicDefinitionTransaction.Divisibility get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Duration
BlockDuration CatSdk.Symbol.MosaicDefinitionTransaction.Duration get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Fee
Amount CatSdk.Symbol.MosaicDefinitionTransaction.Fee get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Flags
MosaicFlags CatSdk.Symbol.MosaicDefinitionTransaction.Flags get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Id
MosaicId CatSdk.Symbol.MosaicDefinitionTransaction.Id get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.MosaicDefinitionTransaction.Network get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Nonce
MosaicNonce CatSdk.Symbol.MosaicDefinitionTransaction.Nonce get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Signature
Signature CatSdk.Symbol.MosaicDefinitionTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.MosaicDefinitionTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Size
uint CatSdk.Symbol.MosaicDefinitionTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.MosaicDefinitionTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.MosaicDefinitionTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"Id", "pod:MosaicId"},
        {"Duration", "pod:BlockDuration"},
        {"Nonce", "pod:MosaicNonce"},
        {"Flags", "enum:MosaicFlags"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.MosaicDefinitionTransaction.Version get set
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Symbol.MosaicDefinitionTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs