SymbolCsharpDualSDK: CatSdk.Symbol.Timestamp Class Reference
CatSdk.Symbol.Timestamp Class Reference
Public Member Functions
Timestamp (ulong timestamp=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Timestamp Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 8
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Timestamp()
CatSdk.Symbol.Timestamp.Timestamp (ulong timestamp = 0) inline
Member Function Documentation
Deserialize()
static Timestamp CatSdk.Symbol.Timestamp.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), and CatSdk.Symbol.TransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.Timestamp.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.Transaction.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), and CatSdk.Symbol.TransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.Timestamp.SIZE = 8 static
The documentation for this class was generated from the following file:
Symbol/Models.cs