SymbolCsharpDualSDK: CatSdk.Symbol.LinkAction Class Reference
CatSdk.Symbol.LinkAction Class Reference
Public Member Functions
LinkAction (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static LinkAction Deserialize (BinaryReader br)
Static Public Attributes
static readonly LinkAction UNLINK = new LinkAction(0)
static readonly LinkAction LINK = new LinkAction(1)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
LinkAction()
CatSdk.Symbol.LinkAction.LinkAction (byte value = 0) inline
References CatSdk.Symbol.LinkAction.Value.
Member Function Documentation
Deserialize()
static LinkAction CatSdk.Symbol.LinkAction.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.LinkAction.Serialize () inline
References CatSdk.Symbol.LinkAction.Value.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Serialize().
ToString()
override string CatSdk.Symbol.LinkAction.ToString () inline
Member Data Documentation
LINK
readonly LinkAction CatSdk.Symbol.LinkAction.LINK = new LinkAction(1) static
UNLINK
readonly LinkAction CatSdk.Symbol.LinkAction.UNLINK = new LinkAction(0) static
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.EmbeddedAccountKeyLinkTransaction(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.EmbeddedNodeKeyLinkTransaction(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.EmbeddedVrfKeyLinkTransaction(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Property Documentation
Size
uint CatSdk.Symbol.LinkAction.Size get
Value
byte CatSdk.Symbol.LinkAction.Value get
Referenced by CatSdk.Symbol.LinkAction.LinkAction(), and CatSdk.Symbol.LinkAction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs