SymbolCsharpDualSDK: CatSdk.Symbol.HashLockTransaction Class Reference
CatSdk.Symbol.HashLockTransaction Class Reference
Public Member Functions
HashLockTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static HashLockTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.HASH_LOCK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
UnresolvedMosaic Mosaic [get, set]
BlockDuration Duration [get, set]
Hash256 Hash [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
HashLockTransaction()
CatSdk.Symbol.HashLockTransaction.HashLockTransaction () inline
References CatSdk.Symbol.HashLockTransaction.Deadline, CatSdk.Symbol.HashLockTransaction.Duration, CatSdk.Symbol.HashLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.HashLockTransaction.Fee, CatSdk.Symbol.HashLockTransaction.Hash, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.HashLockTransaction.Network, CatSdk.Symbol.HashLockTransaction.Signature, CatSdk.Symbol.HashLockTransaction.SignerPublicKey, CatSdk.Symbol.HashLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.HashLockTransaction.TRANSACTION_VERSION, CatSdk.Symbol.HashLockTransaction.Type, CatSdk.Symbol.HashLockTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.HashLockTransaction.Version.
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize().
Member Function Documentation
Deserialize()
static HashLockTransaction CatSdk.Symbol.HashLockTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.HashLockTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.BlockDuration.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.HashLockTransaction.Duration, CatSdk.Symbol.HashLockTransaction.Fee, CatSdk.Symbol.HashLockTransaction.Hash, CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), CatSdk.Symbol.HashLockTransaction.Network, CatSdk.Symbol.HashLockTransaction.SignerPublicKey, CatSdk.Symbol.HashLockTransaction.Type, and CatSdk.Symbol.HashLockTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.HashLockTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.HashLockTransaction.Deadline, CatSdk.Symbol.HashLockTransaction.Duration, CatSdk.Symbol.HashLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.HashLockTransaction.Fee, CatSdk.Symbol.HashLockTransaction.Hash, CatSdk.Symbol.HashLockTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.BlockDuration.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.HashLockTransaction.SignerPublicKey, CatSdk.Symbol.HashLockTransaction.Size, CatSdk.Symbol.HashLockTransaction.Type, CatSdk.Symbol.HashLockTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.HashLockTransaction.Version.
ToString()
override string CatSdk.Symbol.HashLockTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.HashLockTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.HashLockTransaction.TRANSACTION_TYPE = TransactionType.HASH_LOCK static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.HashLockTransaction.HashLockTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.HashLockTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.HashLockTransaction.HashLockTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.HashLockTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.HashLockTransaction.Deadline get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Duration
BlockDuration CatSdk.Symbol.HashLockTransaction.Duration get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Fee
Amount CatSdk.Symbol.HashLockTransaction.Fee get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Hash
Hash256 CatSdk.Symbol.HashLockTransaction.Hash get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Mosaic
UnresolvedMosaic CatSdk.Symbol.HashLockTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.HashLockTransaction.Network get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Signature
Signature CatSdk.Symbol.HashLockTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.HashLockTransaction.HashLockTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.HashLockTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
Size
uint CatSdk.Symbol.HashLockTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.HashLockTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.HashLockTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.HashLockTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"Mosaic", "struct:UnresolvedMosaic"},
        {"Duration", "pod:BlockDuration"},
        {"Hash", "pod:Hash256"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.HashLockTransaction.Version get set
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.HashLockTransaction(), and CatSdk.Symbol.HashLockTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs