SymbolCsharpDualSDK: CatSdk.Nem.Factory.TransactionsFactory Class Reference
CatSdk.Nem.Factory.TransactionsFactory Class Reference
Public Member Functions
TransactionsFactory (Network network, Dictionary< Type, Func< object, object > >? typeRuleOverrides=null)
ITransaction Create (Dictionary< string, object > transactionDescriptor)
IBaseTransaction ToNonVerifiableTransaction (IBaseTransaction transaction)
string AttachSignature (ITransaction transaction, Signature signature)
ITransaction AttachSignatureTransaction (ITransaction transaction, Signature signature)
Static Public Member Functions
static byte[] RawAddressToBytes (string rawAddress)
Static Private Member Functions
static ? Address NemTypeConverter (object value)
static RuleBasedTransactionFactory BuildRules (Dictionary< Type, Func< object, object > >? typeRuleOverrides)
Private Attributes
readonly RuleBasedTransactionFactory Factory
readonly Network Network
Constructor & Destructor Documentation
TransactionsFactory()
CatSdk.Nem.Factory.TransactionsFactory.TransactionsFactory (Network network, Dictionary< Type, Func< object, object > >? typeRuleOverrides = null) inline
References CatSdk.Nem.Factory.TransactionsFactory.BuildRules(), and CatSdk.Nem.Factory.TransactionsFactory.Factory.
Member Function Documentation
AttachSignature()
string CatSdk.Nem.Factory.TransactionsFactory.AttachSignature (ITransaction transaction, Signature signature) inline
References CatSdk.ByteArray.bytes, CatSdk.Utils.Converter.BytesToHex(), and CatSdk.ISerializer.Serialize().
AttachSignatureTransaction()
ITransaction CatSdk.Nem.Factory.TransactionsFactory.AttachSignatureTransaction (ITransaction transaction, Signature signature) inline
References CatSdk.ByteArray.bytes.
BuildRules()
static RuleBasedTransactionFactory CatSdk.Nem.Factory.TransactionsFactory.BuildRules (Dictionary< Type, Func< object, object > >? typeRuleOverrides) inline static private
References CatSdk.Nem.Factory.TransactionsFactory.RawAddressToBytes().
Referenced by CatSdk.Nem.Factory.TransactionsFactory.TransactionsFactory().
Create()
ITransaction CatSdk.Nem.Factory.TransactionsFactory.Create (Dictionary< string, object > transactionDescriptor) inline
References CatSdk.Nem.TransactionFactory.CreateByName(), CatSdk.Nem.Factory.TransactionsFactory.Factory, CatSdk.Nem.NetworkType.TESTNET, and CatSdk.Nem.TransactionType.TRANSFER.
NemTypeConverter()
static ? Address CatSdk.Nem.Factory.TransactionsFactory.NemTypeConverter (object value) inline static private
RawAddressToBytes()
static byte[] CatSdk.Nem.Factory.TransactionsFactory.RawAddressToBytes (string rawAddress) inline static
References CatSdk.Utils.Converter.Utf8ToBytes().
Referenced by CatSdk.Nem.Factory.TransactionsFactory.BuildRules().
ToNonVerifiableTransaction()
IBaseTransaction CatSdk.Nem.Factory.TransactionsFactory.ToNonVerifiableTransaction (IBaseTransaction transaction) inline
Member Data Documentation
Factory
readonly RuleBasedTransactionFactory CatSdk.Nem.Factory.TransactionsFactory.Factory private
Referenced by CatSdk.Nem.Factory.TransactionsFactory.Create(), and CatSdk.Nem.Factory.TransactionsFactory.TransactionsFactory().
Network
readonly Network CatSdk.Nem.Factory.TransactionsFactory.Network private
The documentation for this class was generated from the following file:
Nem/Factory/TransactionsFactory.cs