SymbolCsharpDualSDK: CatSdk.Nem.MultisigAccountModification Class Reference
CatSdk.Nem.MultisigAccountModification Class Reference
Public Member Functions
MultisigAccountModification ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MultisigAccountModification Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MultisigAccountModificationType ModificationType [get, set]
PublicKey CosignatoryPublicKey [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int CosignatoryPublicKeySize
Constructor & Destructor Documentation
MultisigAccountModification()
CatSdk.Nem.MultisigAccountModification.MultisigAccountModification () inline
References CatSdk.Nem.MultisigAccountModificationType.ADD_COSIGNATORY, CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKey, CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKeySize, and CatSdk.Nem.MultisigAccountModification.ModificationType.
Referenced by CatSdk.Nem.MultisigAccountModification.Deserialize().
Member Function Documentation
Deserialize()
static MultisigAccountModification CatSdk.Nem.MultisigAccountModification.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKey, CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.MultisigAccountModificationType.Deserialize(), CatSdk.Nem.MultisigAccountModification.ModificationType, and CatSdk.Nem.MultisigAccountModification.MultisigAccountModification().
Referenced by CatSdk.Nem.SizePrefixedMultisigAccountModification.Deserialize().
Serialize()
byte[] CatSdk.Nem.MultisigAccountModification.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKey, CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKeySize, CatSdk.Nem.MultisigAccountModification.ModificationType, CatSdk.Nem.PublicKey.Serialize(), and CatSdk.Nem.MultisigAccountModificationType.Serialize().
Referenced by CatSdk.Nem.SizePrefixedMultisigAccountModification.Serialize().
ToString()
override string CatSdk.Nem.MultisigAccountModification.ToString () inline
Member Data Documentation
CosignatoryPublicKeySize
readonly int CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKeySize private
Referenced by CatSdk.Nem.MultisigAccountModification.MultisigAccountModification(), and CatSdk.Nem.MultisigAccountModification.Serialize().
Property Documentation
CosignatoryPublicKey
PublicKey CatSdk.Nem.MultisigAccountModification.CosignatoryPublicKey get set
Referenced by CatSdk.Nem.MultisigAccountModification.Deserialize(), CatSdk.Nem.MultisigAccountModification.MultisigAccountModification(), and CatSdk.Nem.MultisigAccountModification.Serialize().
ModificationType
MultisigAccountModificationType CatSdk.Nem.MultisigAccountModification.ModificationType get set
Referenced by CatSdk.Nem.MultisigAccountModification.Deserialize(), CatSdk.Nem.MultisigAccountModification.MultisigAccountModification(), and CatSdk.Nem.MultisigAccountModification.Serialize().
Size
uint CatSdk.Nem.MultisigAccountModification.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Nem.SizePrefixedMultisigAccountModification.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MultisigAccountModification.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"ModificationType", "enum:MultisigAccountModificationType"},
        {"CosignatoryPublicKey", "pod:PublicKey"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs