SymbolCsharpDualSDK: CatSdk.Nem.MultisigAccountModificationType Class Reference
CatSdk.Nem.MultisigAccountModificationType Class Reference
Public Member Functions
MultisigAccountModificationType (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MultisigAccountModificationType Deserialize (BinaryReader br)
Static Public Attributes
static readonly MultisigAccountModificationType ADD_COSIGNATORY = new MultisigAccountModificationType(1)
static readonly MultisigAccountModificationType DELETE_COSIGNATORY = new MultisigAccountModificationType(2)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
MultisigAccountModificationType()
CatSdk.Nem.MultisigAccountModificationType.MultisigAccountModificationType (uint value = 0) inline
References CatSdk.Nem.MultisigAccountModificationType.Value.
Member Function Documentation
Deserialize()
static MultisigAccountModificationType CatSdk.Nem.MultisigAccountModificationType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.MultisigAccountModification.Deserialize().
Serialize()
byte[] CatSdk.Nem.MultisigAccountModificationType.Serialize () inline
References CatSdk.Nem.MultisigAccountModificationType.Value.
Referenced by CatSdk.Nem.MultisigAccountModification.Serialize().
ToString()
override string CatSdk.Nem.MultisigAccountModificationType.ToString () inline
Member Data Documentation
ADD_COSIGNATORY
readonly MultisigAccountModificationType CatSdk.Nem.MultisigAccountModificationType.ADD_COSIGNATORY = new MultisigAccountModificationType(1) static
Referenced by CatSdk.Nem.MultisigAccountModification.MultisigAccountModification().
DELETE_COSIGNATORY
readonly MultisigAccountModificationType CatSdk.Nem.MultisigAccountModificationType.DELETE_COSIGNATORY = new MultisigAccountModificationType(2) static
Property Documentation
Size
uint CatSdk.Nem.MultisigAccountModificationType.Size get
Value
uint CatSdk.Nem.MultisigAccountModificationType.Value get
Referenced by CatSdk.Nem.MultisigAccountModificationType.MultisigAccountModificationType(), and CatSdk.Nem.MultisigAccountModificationType.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs