SymbolCsharpDualSDK: CatSdk.Nem.MosaicLevy Class Reference
CatSdk.Nem.MosaicLevy Class Reference
Public Member Functions
MosaicLevy ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicLevy Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MosaicTransferFeeType TransferFeeType [get, set]
Address RecipientAddress [get, set]
MosaicId MosaicId [get, set]
Amount Fee [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int RecipientAddressSize
Constructor & Destructor Documentation
MosaicLevy()
CatSdk.Nem.MosaicLevy.MosaicLevy () inline
References CatSdk.Nem.MosaicTransferFeeType.ABSOLUTE, CatSdk.Nem.MosaicLevy.Fee, CatSdk.Nem.MosaicLevy.MosaicId, CatSdk.Nem.MosaicLevy.RecipientAddress, CatSdk.Nem.MosaicLevy.RecipientAddressSize, and CatSdk.Nem.MosaicLevy.TransferFeeType.
Referenced by CatSdk.Nem.MosaicLevy.Deserialize().
Member Function Documentation
Deserialize()
static MosaicLevy CatSdk.Nem.MosaicLevy.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Address.Deserialize(), CatSdk.Nem.MosaicId.Deserialize(), CatSdk.Nem.MosaicTransferFeeType.Deserialize(), CatSdk.Nem.MosaicLevy.Fee, CatSdk.Nem.MosaicLevy.MosaicLevy(), CatSdk.Nem.MosaicLevy.RecipientAddress, and CatSdk.Nem.MosaicLevy.TransferFeeType.
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicLevy.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicLevy.Fee, CatSdk.Nem.MosaicLevy.RecipientAddress, CatSdk.Nem.MosaicLevy.RecipientAddressSize, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Address.Serialize(), CatSdk.Nem.MosaicId.Serialize(), CatSdk.Nem.MosaicTransferFeeType.Serialize(), CatSdk.Nem.MosaicId.Size, and CatSdk.Nem.MosaicLevy.TransferFeeType.
Referenced by CatSdk.Nem.MosaicDefinition.Serialize().
ToString()
override string CatSdk.Nem.MosaicLevy.ToString () inline
Member Data Documentation
RecipientAddressSize
readonly int CatSdk.Nem.MosaicLevy.RecipientAddressSize private
Referenced by CatSdk.Nem.MosaicLevy.MosaicLevy(), and CatSdk.Nem.MosaicLevy.Serialize().
Property Documentation
Fee
Amount CatSdk.Nem.MosaicLevy.Fee get set
Referenced by CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.MosaicLevy.MosaicLevy(), and CatSdk.Nem.MosaicLevy.Serialize().
MosaicId
MosaicId CatSdk.Nem.MosaicLevy.MosaicId get set
Referenced by CatSdk.Nem.MosaicLevy.MosaicLevy().
RecipientAddress
Address CatSdk.Nem.MosaicLevy.RecipientAddress get set
Referenced by CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.MosaicLevy.MosaicLevy(), and CatSdk.Nem.MosaicLevy.Serialize().
Size
uint CatSdk.Nem.MosaicLevy.Size get
Implements CatSdk.ISerializer.
TransferFeeType
MosaicTransferFeeType CatSdk.Nem.MosaicLevy.TransferFeeType get set
Referenced by CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.MosaicLevy.MosaicLevy(), and CatSdk.Nem.MosaicLevy.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicLevy.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"TransferFeeType", "enum:MosaicTransferFeeType"},
        {"RecipientAddress", "pod:Address"},
        {"MosaicId", "struct:MosaicId"},
        {"Fee", "pod:Amount"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs