SymbolCsharpDualSDK: CatSdk.Utils.Converter Class Reference
CatSdk.Utils.Converter Class Reference
Static Public Member Functions
static byte[] HexToBytes (string hexString)
static string BytesToHex (byte[] bytes)
static byte[] StringToAddress (string encoded)
static string AddressToString (byte[] decoded)
static string Utf8ToHex (string input)
static byte[] Utf8ToBytes (string input)
static string HexToUtf8 (string input)
static byte[] Utf8ToPlainMessage (string input)
static byte[] Utf8ToEncryptoMessage (string input)
static string ToHex< T > (T value, byte i=0)
static string ToString< T > (T value)
static bool IsHexString (string s)
Static Private Member Functions
static string ToPascal (string text)
Static Private Attributes
static readonly Dictionary< string, Dictionary< string, byte > > _constants
Member Function Documentation
AddressToString()
static string CatSdk.Utils.Converter.AddressToString (byte[] decoded) inline static
References CatSdk.Utils.Converter._constants, CatSdk.Utils.Converter.BytesToHex(), and CatSdk.Utils.Base32.Encode().
Referenced by CatSdk.Symbol.Factory.SymbolAddress.ToString().
BytesToHex()
static string CatSdk.Utils.Converter.BytesToHex (byte[] bytes) inline static
Converts a uint8 array to a hex string.
Parameters
{byte[]} input A uint8 array.
Returns
{string} A hex encoded string corresponding to the input.
Referenced by CatSdk.Crypto.Crypto._Decode(), CatSdk.Crypto.Crypto._Encode(), CatSdk.Utils.Converter.AddressToString(), CatSdk.Nem.Factory.TransactionsFactory.AttachSignature(), CatSdk.Symbol.Factory.TransactionsFactory.AttachSignature(), and CatSdk.ByteArray.ToString().
HexToBytes()
static byte[] CatSdk.Utils.Converter.HexToBytes (string hexString) inline static
Converts a hex string to a uint8 array.
Parameters
{string} input A hex encoded string.
Returns
{byte[]} A uint8 array corresponding to the input.
Referenced by CatSdk.RuleBasedTransactionFactory.AddPodParser(), CatSdk.ByteArray.ByteArray(), CatSdk.TransactionDescriptorProcessor.CopyTo(), CatSdk.Crypto.Crypto.Decode(), CatSdk.Nem.TransactionFactory.Deserialize(), CatSdk.Nem.NonVerifiableTransactionFactory.Deserialize(), CatSdk.Symbol.TransactionFactory.Deserialize(), CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), CatSdk.Crypto.Crypto.Encode(), CatSdk.Crypto.Crypto.Encrypt(), CatSdk.Utils.Converter.HexToUtf8(), and CatSdk.BaseNetwork< T >.PublicKeyToAddress().
HexToUtf8()
static string CatSdk.Utils.Converter.HexToUtf8 (string input) inline static
References CatSdk.Utils.Converter.HexToBytes().
Referenced by CatSdk.Crypto.Crypto.Decode().
IsHexString()
static bool CatSdk.Utils.Converter.IsHexString (string s) inline static
Referenced by CatSdk.RuleBasedTransactionFactory.AddPodParser().
StringToAddress()
static byte[] CatSdk.Utils.Converter.StringToAddress (string encoded) inline static
Converts an encoded address string to a decoded address.
Parameters
{string} encoded The encoded address string.
Returns
{byte[]} The decoded address corresponding to the input.
References CatSdk.Utils.Converter._constants, and CatSdk.Utils.Base32.Decode().
ToHex< T >()
static string CatSdk.Utils.Converter.ToHex< T > (T value, byte i = 0) inline static
ToPascal()
static string CatSdk.Utils.Converter.ToPascal (string text) inline static private
ToString< T >()
static string CatSdk.Utils.Converter.ToString< T > (T value) inline static
Utf8ToBytes()
static byte[] CatSdk.Utils.Converter.Utf8ToBytes (string input) inline static
Referenced by CatSdk.Nem.Factory.TransactionsFactory.RawAddressToBytes().
Utf8ToEncryptoMessage()
static byte[] CatSdk.Utils.Converter.Utf8ToEncryptoMessage (string input) inline static
Utf8ToHex()
static string CatSdk.Utils.Converter.Utf8ToHex (string input) inline static
Convert UTF-8 to hex
Parameters
{string} input - An UTF-8 string
Returns
{string}
Referenced by CatSdk.Crypto.Crypto.Encode().
Utf8ToPlainMessage()
static byte[] CatSdk.Utils.Converter.Utf8ToPlainMessage (string input) inline static
Member Data Documentation
_constants
readonly Dictionary<string, Dictionary<string, byte> > CatSdk.Utils.Converter._constants static private
Initial value:
= new Dictionary<string, Dictionary<string, byte>>
        {
            {
                "sizes",
                new Dictionary<string, byte>{
                    {"ripemd160", 20},
                    {"symbolAddressDecoded", 24},
                    {"nemAddressDecoded", 40},
                    {"symbolAddressEncoded", 39},
                    {"nemAddressEncoded", 40},
                    {"key", 32},
                    {"checksum", 3},
                }
            }
        }
Referenced by CatSdk.Utils.Converter.AddressToString(), and CatSdk.Utils.Converter.StringToAddress().
The documentation for this class was generated from the following file:
Converter.cs