SymbolCsharpDualSDK: CatSdk.Symbol.Mosaic Class Reference
CatSdk.Symbol.Mosaic Class Reference
Public Member Functions
Mosaic ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Mosaic Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MosaicId MosaicId [get, set]
Amount Amount [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Mosaic()
CatSdk.Symbol.Mosaic.Mosaic () inline
References CatSdk.Symbol.Mosaic.Amount, and CatSdk.Symbol.Mosaic.MosaicId.
Referenced by CatSdk.Symbol.Mosaic.Deserialize().
Member Function Documentation
Deserialize()
static Mosaic CatSdk.Symbol.Mosaic.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.MosaicId.Deserialize(), and CatSdk.Symbol.Mosaic.Mosaic().
Serialize()
byte[] CatSdk.Symbol.Mosaic.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.Amount.Serialize(), and CatSdk.Symbol.MosaicId.Serialize().
Referenced by CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
ToString()
override string CatSdk.Symbol.Mosaic.ToString () inline
Property Documentation
Amount
Amount CatSdk.Symbol.Mosaic.Amount get set
Referenced by CatSdk.Symbol.Mosaic.Mosaic().
MosaicId
MosaicId CatSdk.Symbol.Mosaic.MosaicId get set
Referenced by CatSdk.Symbol.Mosaic.Mosaic().
Size
uint CatSdk.Symbol.Mosaic.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Symbol.Mosaic.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"MosaicId", "pod:MosaicId"},
        {"Amount", "pod:Amount"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Symbol/Models.cs