SymbolCsharpDualSDK: CatSdk.Crypto.NaclCatapult Class Reference
CatSdk.Crypto.NaclCatapult Class Reference
Static Public Member Functions
static long[] Gf (long[]? init=null)
static void A (long[] o, long[] a, long[] b)
static void Z (long[] o, long[] a, long[] b)
static void M (long[] o, long[] a, long[] b)
static void S (long[] o, long[] a)
static long Vn (long[] x, int xi, long[] y, int yi, int n)
static void Pow2523 (long[] o, long[] i)
static void Inv25519 (long[] o, long[] i)
static void Set25519 (long[] r, long[] a)
static void Car25519 (long[] o)
static void Sel25519 (long[] p, long[] q, long b)
static void Pack25519 (long[] o, long[] n)
static void Cswap (long[][] p, long[][] q, long b)
static long Neq25519 (long[] a, long[] b)
static long CryptoVerify32 (long[] x, int xi, long[] y, int yi)
static long Par25519 (long[] a)
static void Unpack25519 (long[] o, byte[] n)
static void Add (IReadOnlyList< long[]> p, IReadOnlyList< long[]> q)
static void Pack (long[] r, long[][] p)
static void Scalarmult (long[][] p, long[][] q, byte[] s)
static int Unpack (long[][] r, byte[] p)
Static Private Attributes
static readonly long[] gf0 = Gf()
static readonly long[] gf1 = Gf(new long[]{1})
static readonly long[] D
static readonly long[] D2
static long[] X
static long[] Y
static readonly long[] I
static long[] L
Member Function Documentation
A()
static void CatSdk.Crypto.NaclCatapult.A (long[] o, long[] a, long[] b) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Add()
static void CatSdk.Crypto.NaclCatapult.Add (IReadOnlyList< long[]> p, IReadOnlyList< long[]> q) inline static
References CatSdk.Crypto.NaclCatapult.A(), CatSdk.Crypto.NaclCatapult.D2, CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.M(), and CatSdk.Crypto.NaclCatapult.Z().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen(), and CatSdk.Crypto.NaclCatapult.Scalarmult().
Car25519()
static void CatSdk.Crypto.NaclCatapult.Car25519 (long[] o) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Pack25519().
CryptoVerify32()
static long CatSdk.Crypto.NaclCatapult.CryptoVerify32 (long[] x, int xi, long[] y, int yi) inline static
References CatSdk.Crypto.NaclCatapult.Vn().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen(), and CatSdk.Crypto.NaclCatapult.Neq25519().
Cswap()
static void CatSdk.Crypto.NaclCatapult.Cswap (long p[][], long q[][], long b) inline static
References CatSdk.Crypto.NaclCatapult.Sel25519().
Referenced by CatSdk.Crypto.NaclCatapult.Scalarmult().
Gf()
static long[] CatSdk.Crypto.NaclCatapult.Gf (long?[] init = null) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen(), CatSdk.Crypto.CatapultCrypto.DeriveSharedSecret(), CatSdk.Crypto.NaclCatapult.Inv25519(), CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Crypto.NaclCatapult.Pack25519(), CatSdk.Crypto.NaclCatapult.Pow2523(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Inv25519()
static void CatSdk.Crypto.NaclCatapult.Inv25519 (long[] o, long[] i) inline static
References CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.M(), and CatSdk.Crypto.NaclCatapult.S().
Referenced by CatSdk.Crypto.NaclCatapult.Pack().
M()
static void CatSdk.Crypto.NaclCatapult.M (long[] o, long[] a, long[] b) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Crypto.NaclCatapult.Inv25519(), CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Crypto.NaclCatapult.Pow2523(), CatSdk.Crypto.NaclCatapult.S(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Neq25519()
static long CatSdk.Crypto.NaclCatapult.Neq25519 (long[] a, long[] b) inline static
References CatSdk.Crypto.NaclCatapult.CryptoVerify32(), and CatSdk.Crypto.NaclCatapult.Pack25519().
Referenced by CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Pack()
static void CatSdk.Crypto.NaclCatapult.Pack (long[] r, long p[][]) inline static
References CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.Inv25519(), CatSdk.Crypto.NaclCatapult.M(), CatSdk.Crypto.NaclCatapult.Pack25519(), and CatSdk.Crypto.NaclCatapult.Par25519().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen(), and CatSdk.Crypto.CatapultCrypto.DeriveSharedSecret().
Pack25519()
static void CatSdk.Crypto.NaclCatapult.Pack25519 (long[] o, long[] n) inline static
References CatSdk.Crypto.NaclCatapult.Car25519(), CatSdk.Crypto.NaclCatapult.Gf(), and CatSdk.Crypto.NaclCatapult.Sel25519().
Referenced by CatSdk.Crypto.NaclCatapult.Neq25519(), CatSdk.Crypto.NaclCatapult.Pack(), and CatSdk.Crypto.NaclCatapult.Par25519().
Par25519()
static long CatSdk.Crypto.NaclCatapult.Par25519 (long[] a) inline static
References CatSdk.Crypto.NaclCatapult.Pack25519().
Referenced by CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Pow2523()
static void CatSdk.Crypto.NaclCatapult.Pow2523 (long[] o, long[] i) inline static
References CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.M(), and CatSdk.Crypto.NaclCatapult.S().
Referenced by CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
S()
static void CatSdk.Crypto.NaclCatapult.S (long[] o, long[] a) inline static
References CatSdk.Crypto.NaclCatapult.M().
Referenced by CatSdk.Crypto.NaclCatapult.Inv25519(), CatSdk.Crypto.NaclCatapult.Pow2523(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Scalarmult()
static void CatSdk.Crypto.NaclCatapult.Scalarmult (long p[][], long q[][], byte[] s) inline static
References CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Crypto.NaclCatapult.Cswap(), CatSdk.Crypto.NaclCatapult.gf0, CatSdk.Crypto.NaclCatapult.gf1, and CatSdk.Crypto.NaclCatapult.Set25519().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen(), CatSdk.Crypto.CatapultCrypto.DeriveSharedSecret(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase().
Sel25519()
static void CatSdk.Crypto.NaclCatapult.Sel25519 (long[] p, long[] q, long b) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Cswap(), and CatSdk.Crypto.NaclCatapult.Pack25519().
Set25519()
static void CatSdk.Crypto.NaclCatapult.Set25519 (long[] r, long[] a) inline static
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase(), CatSdk.Crypto.NaclCatapult.Scalarmult(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Unpack()
static int CatSdk.Crypto.NaclCatapult.Unpack (long r[][], byte[] p) inline static
References CatSdk.Crypto.NaclCatapult.A(), CatSdk.Crypto.NaclCatapult.D, CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.gf0, CatSdk.Crypto.NaclCatapult.gf1, CatSdk.Crypto.NaclCatapult.I, CatSdk.Crypto.NaclCatapult.M(), CatSdk.Crypto.NaclCatapult.Neq25519(), CatSdk.Crypto.NaclCatapult.Par25519(), CatSdk.Crypto.NaclCatapult.Pow2523(), CatSdk.Crypto.NaclCatapult.S(), CatSdk.Crypto.NaclCatapult.Set25519(), CatSdk.Crypto.NaclCatapult.Unpack25519(), and CatSdk.Crypto.NaclCatapult.Z().
Referenced by CatSdk.Crypto.CatapultCrypto.DeriveSharedSecret().
Unpack25519()
static void CatSdk.Crypto.NaclCatapult.Unpack25519 (long[] o, byte[] n) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Vn()
static long CatSdk.Crypto.NaclCatapult.Vn (long[] x, int xi, long[] y, int yi, int n) inline static
Referenced by CatSdk.Crypto.NaclCatapult.CryptoVerify32().
Z()
static void CatSdk.Crypto.NaclCatapult.Z (long[] o, long[] a, long[] b) inline static
Referenced by CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Crypto.NaclCatapult.Unpack(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Member Data Documentation
D
readonly long [] CatSdk.Crypto.NaclCatapult.D static private
Initial value:
= Gf(new long[]{
        0x78a3,
        0x1359,
        0x4dca,
        0x75eb,
        0xd8ab,
        0x4141,
        0x0a4d,
        0x0070,
        0xe898,
        0x7779,
        0x4079,
        0x8cc7,
        0xfe73,
        0x2b6f,
        0x6cee,
        0x5203})
Referenced by CatSdk.Crypto.NaclCatapult.Unpack().
D2
readonly long [] CatSdk.Crypto.NaclCatapult.D2 static private
Initial value:
= Gf(new long[]{
        0xf159,
        0x26b2,
        0x9b94,
        0xebd6,
        0xb156,
        0x8283,
        0x149a,
        0x00e0,
        0xd130,
        0xeef3,
        0x80f2,
        0x198e,
        0xfce7,
        0x56df,
        0xd9dc,
        0x2406})
Referenced by CatSdk.Crypto.NaclCatapult.Add().
gf0
readonly long [] CatSdk.Crypto.NaclCatapult.gf0 = Gf() static private
Referenced by CatSdk.Crypto.NaclCatapult.Scalarmult(), and CatSdk.Crypto.NaclCatapult.Unpack().
gf1
readonly long [] CatSdk.Crypto.NaclCatapult.gf1 = Gf(new long[]{1}) static private
Referenced by CatSdk.Crypto.NaclCatapult.Scalarmult(), and CatSdk.Crypto.NaclCatapult.Unpack().
I
readonly long [] CatSdk.Crypto.NaclCatapult.I static private
Initial value:
= Gf(new long[]{
        0xa0b0,
        0x4a0e,
        0x1b27,
        0xc4ee,
        0xe478,
        0xad2f,
        0x1806,
        0x2f43,
        0xd7a7,
        0x3dfb,
        0x0099,
        0x2b4d,
        0xdf0b,
        0x4fc1,
        0x2480,
        0x2b83})
Referenced by CatSdk.Crypto.NaclCatapult.Unpack().
L
long [] CatSdk.Crypto.NaclCatapult.L static private
X
long [] CatSdk.Crypto.NaclCatapult.X static private
Initial value:
= Gf(new long[]{
        0xd51a,
        0x8f25,
        0x2d60,
        0xc956,
        0xa7b2,
        0x9525,
        0xc760,
        0x692c,
        0xdc5c,
        0xfdd6,
        0xe231,
        0xc0a4,
        0x53fe,
        0xcd6e,
        0x36d3,
        0x2169})
Y
long [] CatSdk.Crypto.NaclCatapult.Y static private
Initial value:
= Gf(new long[]{
        0x6658,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666,
        0x6666})
The documentation for this class was generated from the following file:
NaclCatapult.cs