SymbolCsharpDualSDK: CatSdk.Nem.Signature Class Reference
CatSdk.Nem.Signature Class Reference
Public Member Functions
Signature (byte[]? signature=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Signature Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 64
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Signature()
CatSdk.Nem.Signature.Signature (byte?[] signature = null) inline
Member Function Documentation
Deserialize()
static Signature CatSdk.Nem.Signature.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), and CatSdk.Nem.TransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.Signature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Nem.Transaction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), and CatSdk.Nem.TransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Nem.Signature.SIZE = 64 static
The documentation for this class was generated from the following file:
Nem/Models.cs