SymbolCsharpDualSDK: CatSdk.Nem.MosaicId Class Reference
CatSdk.Nem.MosaicId Class Reference
Public Member Functions
MosaicId ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicId Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
NamespaceId NamespaceId [get, set]
byte[] Name [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
MosaicId()
CatSdk.Nem.MosaicId.MosaicId () inline
References CatSdk.Nem.MosaicId.Name, and CatSdk.Nem.MosaicId.NamespaceId.
Referenced by CatSdk.Nem.MosaicId.Deserialize().
Member Function Documentation
Deserialize()
static MosaicId CatSdk.Nem.MosaicId.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.NamespaceId.Deserialize(), CatSdk.Nem.MosaicId.MosaicId(), and CatSdk.Nem.MosaicId.Name.
Referenced by CatSdk.Nem.Mosaic.Deserialize(), CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicId.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicId.Name, and CatSdk.Nem.NamespaceId.Serialize().
Referenced by CatSdk.Nem.Mosaic.Serialize(), CatSdk.Nem.MosaicLevy.Serialize(), CatSdk.Nem.MosaicDefinition.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
ToString()
override string CatSdk.Nem.MosaicId.ToString () inline
Property Documentation
Name
byte [] CatSdk.Nem.MosaicId.Name get set
Referenced by CatSdk.Nem.MosaicId.Deserialize(), CatSdk.Nem.MosaicId.MosaicId(), and CatSdk.Nem.MosaicId.Serialize().
NamespaceId
NamespaceId CatSdk.Nem.MosaicId.NamespaceId get set
Referenced by CatSdk.Nem.MosaicId.MosaicId().
Size
uint CatSdk.Nem.MosaicId.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Nem.Mosaic.Serialize(), CatSdk.Nem.MosaicLevy.Serialize(), CatSdk.Nem.MosaicDefinition.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicId.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"NamespaceId", "struct:NamespaceId"},
        {"Name", "bytes_array"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs