SymbolCsharpDualSDK: CatSdk.Symbol.UnresolvedMosaicId Class Reference
CatSdk.Symbol.UnresolvedMosaicId Class Reference
Public Member Functions
UnresolvedMosaicId (ulong unresolvedMosaicId=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static UnresolvedMosaicId Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 8
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
UnresolvedMosaicId()
CatSdk.Symbol.UnresolvedMosaicId.UnresolvedMosaicId (ulong unresolvedMosaicId = 0) inline
Member Function Documentation
Deserialize()
static UnresolvedMosaicId CatSdk.Symbol.UnresolvedMosaicId.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.UnresolvedMosaicId.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.UnresolvedMosaicId.SIZE = 8 static
The documentation for this class was generated from the following file:
Symbol/Models.cs