SymbolCsharpDualSDK: CatSdk.Facade.SymbolFacade Class Reference
CatSdk.Facade.SymbolFacade Class Reference
Public Member Functions
SymbolFacade (Network network)
Hash256 HashTransaction (ITransaction transaction)
Signature SignTransaction (KeyPair keyPair, IBaseTransaction transaction)
bool VerifyTransaction (ITransaction transaction, Signature signature)
Public Attributes
Network Network
readonly TransactionsFactory TransactionFactory
Private Member Functions
bool IsAggregateTransaction (IReadOnlyList< byte > transactionBuffer)
byte[] TransactionDataBuffer (byte[] transactionBuffer)
Private Attributes
readonly int TRANSACTION_HEADER_SIZE = new List<int>{4, 4, Signature.SIZE, PublicKey.SIZE, 4}.Aggregate((x, y) => x + y)
readonly int AGGREGATE_HASHED_SIZE = new List<int>{4, 8, 8, Hash256.SIZE}.Aggregate((x, y) => x + y)
Detailed Description
Facade used to interact with Symbol blockchain.
Constructor & Destructor Documentation
SymbolFacade()
CatSdk.Facade.SymbolFacade.SymbolFacade (Network network) inline
Creates a Symbol facade.
Parameters
{Network} network Symbol network or network name.
Member Function Documentation
HashTransaction()
Hash256 CatSdk.Facade.SymbolFacade.HashTransaction (ITransaction transaction) inline
Hashes a Symbol transaction.
Parameters
{ITransaction} transaction Transaction object.
Returns
{Hash256} Transaction hash.
References CatSdk.ByteArray.bytes, CatSdk.Symbol.Factory.Network.GenerationHashSeed, CatSdk.Symbol.ITransaction.Signature, and CatSdk.Symbol.ITransaction.SignerPublicKey.
IsAggregateTransaction()
bool CatSdk.Facade.SymbolFacade.IsAggregateTransaction (IReadOnlyList< byte > transactionBuffer) inline private
References CatSdk.Symbol.TransactionType.AGGREGATE_BONDED, CatSdk.Symbol.TransactionType.AGGREGATE_COMPLETE, CatSdk.Facade.SymbolFacade.TRANSACTION_HEADER_SIZE, and CatSdk.Symbol.TransactionType.Value.
Referenced by CatSdk.Facade.SymbolFacade.TransactionDataBuffer().
SignTransaction()
Signature CatSdk.Facade.SymbolFacade.SignTransaction (KeyPair keyPair, IBaseTransaction transaction) inline
Signs a Symbol transaction.
Parameters
{KeyPair} keyPair Key pair.
{IBaseTransaction} transaction Transaction object.
Returns
{Signature} Transaction signature.
References CatSdk.ByteArray.bytes, CatSdk.Symbol.Factory.Network.GenerationHashSeed, CatSdk.ISerializer.Serialize(), CatSdk.Symbol.KeyPair.Sign(), and CatSdk.Facade.SymbolFacade.TransactionDataBuffer().
TransactionDataBuffer()
byte[] CatSdk.Facade.SymbolFacade.TransactionDataBuffer (byte[] transactionBuffer) inline private
References CatSdk.Facade.SymbolFacade.AGGREGATE_HASHED_SIZE, CatSdk.Facade.SymbolFacade.IsAggregateTransaction(), and CatSdk.Facade.SymbolFacade.TRANSACTION_HEADER_SIZE.
Referenced by CatSdk.Facade.SymbolFacade.SignTransaction(), and CatSdk.Facade.SymbolFacade.VerifyTransaction().
VerifyTransaction()
bool CatSdk.Facade.SymbolFacade.VerifyTransaction (ITransaction transaction, Signature signature) inline
Verifies a NEM transaction.
Parameters
{IBaseTransaction} transaction Transaction object.
{Signature} signature Signature to verify.
Returns
{bool} true if transaction signature is verified.
References CatSdk.ByteArray.bytes, CatSdk.Symbol.Factory.Network.GenerationHashSeed, CatSdk.ISerializer.Serialize(), CatSdk.Symbol.ITransaction.SignerPublicKey, CatSdk.Facade.SymbolFacade.TransactionDataBuffer(), and CatSdk.Symbol.Verifier.Verify().
Member Data Documentation
AGGREGATE_HASHED_SIZE
readonly int CatSdk.Facade.SymbolFacade.AGGREGATE_HASHED_SIZE = new List<int>{4, 8, 8, Hash256.SIZE}.Aggregate((x, y) => x + y) private
Referenced by CatSdk.Facade.SymbolFacade.TransactionDataBuffer().
Network
Network CatSdk.Facade.SymbolFacade.Network
TRANSACTION_HEADER_SIZE
readonly int CatSdk.Facade.SymbolFacade.TRANSACTION_HEADER_SIZE = new List<int>{4, 4, Signature.SIZE, PublicKey.SIZE, 4}.Aggregate((x, y) => x + y) private
Referenced by CatSdk.Facade.SymbolFacade.IsAggregateTransaction(), and CatSdk.Facade.SymbolFacade.TransactionDataBuffer().
TransactionFactory
readonly TransactionsFactory CatSdk.Facade.SymbolFacade.TransactionFactory
The documentation for this class was generated from the following file:
SymbolFacade.cs