SymbolCsharpDualSDK: CatSdk.TransactionDescriptorProcessor Class Reference
CatSdk.TransactionDescriptorProcessor Class Reference
Public Member Functions
TransactionDescriptorProcessor (Dictionary< string, object > transactionDescriptor, Dictionary< string, Func< object, object > > typeParsingRules, Func< object, object?>? typeConverter=null)
object LookupValue (string key)
void CopyTo (IStruct transaction, string[]? ignoreKeys=null)
void SetTypeHints (Dictionary< string, string >? typeHint)
Public Attributes
Dictionary< string, string >? TypeHints
Private Member Functions
object LookupValueAndApplyTypeHints (string key)
Private Attributes
readonly Dictionary< string, object > TransactionDescriptor
readonly Dictionary< string, Func< object, object > > TypeParsingRules
readonly? Func< object, object?> TypeConverter
Detailed Description
Processes and looks up transaction descriptor properties.
Constructor & Destructor Documentation
TransactionDescriptorProcessor()
CatSdk.TransactionDescriptorProcessor.TransactionDescriptorProcessor (Dictionary< string, object > transactionDescriptor, Dictionary< string, Func< object, object > > typeParsingRules, Func< object, object?>? typeConverter = null) inline
Creates a transaction descriptor processor.
Parameters
{object} transactionDescriptor Transaction descriptor.
{Map} typeParsingRules Type-dependent parsing rules.
{function} typeConverter Converts a generated type to an sdk type (optional).
References CatSdk.TransactionDescriptorProcessor.TransactionDescriptor, CatSdk.TransactionDescriptorProcessor.TypeConverter, CatSdk.TransactionDescriptorProcessor.TypeHints, and CatSdk.TransactionDescriptorProcessor.TypeParsingRules.
Member Function Documentation
CopyTo()
void CatSdk.TransactionDescriptorProcessor.CopyTo (IStruct transaction, string?[] ignoreKeys = null) inline
Copies all descriptor information to a transaction.
Parameters
{IStruct} transaction Transaction to which to copy keys.
{array&lt;string&gt;} ignoreKeys Keys of descriptor values not to copy (optional).
References CatSdk.Utils.Converter.HexToBytes(), CatSdk.TransactionDescriptorProcessor.LookupValue(), and CatSdk.TransactionDescriptorProcessor.TransactionDescriptor.
Referenced by CatSdk.RuleBasedTransactionFactory.AddStructParser().
LookupValue()
object CatSdk.TransactionDescriptorProcessor.LookupValue (string key) inline
Looks up the value for key.
Parameters
{string} key Key for which to retrieve value.
Returns
{object} Value corresponding to key.
References CatSdk.TransactionDescriptorProcessor.LookupValueAndApplyTypeHints().
Referenced by CatSdk.TransactionDescriptorProcessor.CopyTo().
LookupValueAndApplyTypeHints()
object CatSdk.TransactionDescriptorProcessor.LookupValueAndApplyTypeHints (string key) inline private
References CatSdk.TransactionDescriptorProcessor.TransactionDescriptor, CatSdk.TransactionDescriptorProcessor.TypeHints, and CatSdk.TransactionDescriptorProcessor.TypeParsingRules.
Referenced by CatSdk.TransactionDescriptorProcessor.LookupValue().
SetTypeHints()
void CatSdk.TransactionDescriptorProcessor.SetTypeHints (Dictionary< string, string >? typeHint) inline
Sets type hints.
Parameters
{Dictionary} typeHints New type hints.
References CatSdk.TransactionDescriptorProcessor.TypeHints.
Referenced by CatSdk.RuleBasedTransactionFactory.AddStructParser().
Member Data Documentation
TransactionDescriptor
readonly Dictionary<string, object> CatSdk.TransactionDescriptorProcessor.TransactionDescriptor private
Referenced by CatSdk.TransactionDescriptorProcessor.CopyTo(), CatSdk.TransactionDescriptorProcessor.LookupValueAndApplyTypeHints(), and CatSdk.TransactionDescriptorProcessor.TransactionDescriptorProcessor().
TypeConverter
readonly? Func<object, object?> CatSdk.TransactionDescriptorProcessor.TypeConverter private
Referenced by CatSdk.TransactionDescriptorProcessor.TransactionDescriptorProcessor().
TypeHints
Dictionary<string, string>? CatSdk.TransactionDescriptorProcessor.TypeHints
Referenced by CatSdk.TransactionDescriptorProcessor.LookupValueAndApplyTypeHints(), CatSdk.TransactionDescriptorProcessor.SetTypeHints(), and CatSdk.TransactionDescriptorProcessor.TransactionDescriptorProcessor().
TypeParsingRules
readonly Dictionary<string, Func<object, object> > CatSdk.TransactionDescriptorProcessor.TypeParsingRules private
Referenced by CatSdk.TransactionDescriptorProcessor.LookupValueAndApplyTypeHints(), and CatSdk.TransactionDescriptorProcessor.TransactionDescriptorProcessor().
The documentation for this class was generated from the following file:
TransactionDescriptorProcessor.cs