SymbolCsharpDualSDK: CatSdk.Nem.MosaicSupplyChangeAction Class Reference
CatSdk.Nem.MosaicSupplyChangeAction Class Reference
Public Member Functions
MosaicSupplyChangeAction (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MosaicSupplyChangeAction Deserialize (BinaryReader br)
Static Public Attributes
static readonly MosaicSupplyChangeAction INCREASE = new MosaicSupplyChangeAction(1)
static readonly MosaicSupplyChangeAction DECREASE = new MosaicSupplyChangeAction(2)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
MosaicSupplyChangeAction()
CatSdk.Nem.MosaicSupplyChangeAction.MosaicSupplyChangeAction (uint value = 0) inline
References CatSdk.Nem.MosaicSupplyChangeAction.Value.
Member Function Documentation
Deserialize()
static MosaicSupplyChangeAction CatSdk.Nem.MosaicSupplyChangeAction.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicSupplyChangeAction.Serialize () inline
References CatSdk.Nem.MosaicSupplyChangeAction.Value.
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
ToString()
override string CatSdk.Nem.MosaicSupplyChangeAction.ToString () inline
Member Data Documentation
DECREASE
readonly MosaicSupplyChangeAction CatSdk.Nem.MosaicSupplyChangeAction.DECREASE = new MosaicSupplyChangeAction(2) static
INCREASE
readonly MosaicSupplyChangeAction CatSdk.Nem.MosaicSupplyChangeAction.INCREASE = new MosaicSupplyChangeAction(1) static
Referenced by CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction().
Property Documentation
Size
uint CatSdk.Nem.MosaicSupplyChangeAction.Size get
Value
uint CatSdk.Nem.MosaicSupplyChangeAction.Value get
Referenced by CatSdk.Nem.MosaicSupplyChangeAction.MosaicSupplyChangeAction(), and CatSdk.Nem.MosaicSupplyChangeAction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs