SymbolCsharpDualSDK: CatSdk.Nem.Cosignature Class Reference
CatSdk.Nem.Cosignature Class Reference
Public Member Functions
Cosignature ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Cosignature Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MULTISIG_COSIGNATURE
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
Hash256 MultisigTransactionHash [get, set]
Address MultisigAccountAddress [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
readonly int MultisigTransactionHashOuterSize
readonly int MultisigTransactionHashSize
readonly int MultisigAccountAddressSize
Constructor & Destructor Documentation
Cosignature()
CatSdk.Nem.Cosignature.Cosignature () inline
References CatSdk.Nem.Cosignature.Deadline, CatSdk.Nem.Cosignature.EntityBodyReserved_1, CatSdk.Nem.Cosignature.Fee, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.Cosignature.MultisigAccountAddress, CatSdk.Nem.Cosignature.MultisigAccountAddressSize, CatSdk.Nem.Cosignature.MultisigTransactionHash, CatSdk.Nem.Cosignature.MultisigTransactionHashOuterSize, CatSdk.Nem.Cosignature.MultisigTransactionHashSize, CatSdk.Nem.Cosignature.Network, CatSdk.Nem.Cosignature.Signature, CatSdk.Nem.Cosignature.SignatureSize, CatSdk.Nem.Cosignature.SignerPublicKey, CatSdk.Nem.Cosignature.SignerPublicKeySize, CatSdk.Nem.Cosignature.Timestamp, CatSdk.Nem.Cosignature.TRANSACTION_TYPE, CatSdk.Nem.Cosignature.TRANSACTION_VERSION, CatSdk.Nem.Cosignature.Type, and CatSdk.Nem.Cosignature.Version.
Referenced by CatSdk.Nem.Cosignature.Deserialize().
Member Function Documentation
Deserialize()
static Cosignature CatSdk.Nem.Cosignature.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.Address.Deserialize(), CatSdk.Nem.Hash256.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.Cosignature.Fee, CatSdk.Nem.Cosignature.MultisigAccountAddress, CatSdk.Nem.Cosignature.MultisigTransactionHash, CatSdk.Nem.Cosignature.Network, CatSdk.Nem.Cosignature.SignerPublicKey, CatSdk.Nem.Cosignature.Type, and CatSdk.Nem.Cosignature.Version.
Referenced by CatSdk.Nem.SizePrefixedCosignature.Deserialize(), and CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.Cosignature.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.Cosignature.Deadline, CatSdk.Nem.Cosignature.EntityBodyReserved_1, CatSdk.Nem.Cosignature.Fee, CatSdk.Nem.Cosignature.MultisigAccountAddress, CatSdk.Nem.Cosignature.MultisigAccountAddressSize, CatSdk.Nem.Cosignature.MultisigTransactionHash, CatSdk.Nem.Cosignature.MultisigTransactionHashOuterSize, CatSdk.Nem.Cosignature.MultisigTransactionHashSize, CatSdk.Nem.Cosignature.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.Address.Serialize(), CatSdk.Nem.Hash256.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.Cosignature.SignatureSize, CatSdk.Nem.Cosignature.SignerPublicKey, CatSdk.Nem.Cosignature.SignerPublicKeySize, CatSdk.Nem.Cosignature.Type, and CatSdk.Nem.Cosignature.Version.
Referenced by CatSdk.Nem.SizePrefixedCosignature.Serialize().
ToString()
override string CatSdk.Nem.Cosignature.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.Cosignature.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
MultisigAccountAddressSize
readonly int CatSdk.Nem.Cosignature.MultisigAccountAddressSize private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
MultisigTransactionHashOuterSize
readonly int CatSdk.Nem.Cosignature.MultisigTransactionHashOuterSize private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
MultisigTransactionHashSize
readonly int CatSdk.Nem.Cosignature.MultisigTransactionHashSize private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
SignatureSize
readonly int CatSdk.Nem.Cosignature.SignatureSize private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.Cosignature.SignerPublicKeySize private
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.Cosignature.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.Cosignature.TRANSACTION_TYPE = TransactionType.MULTISIG_COSIGNATURE static
Referenced by CatSdk.Nem.Cosignature.Cosignature(), and CatSdk.Nem.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Nem.Cosignature.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.Cosignature.Cosignature().
Property Documentation
Deadline
Timestamp CatSdk.Nem.Cosignature.Deadline get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
Fee
Amount CatSdk.Nem.Cosignature.Fee get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
MultisigAccountAddress
Address CatSdk.Nem.Cosignature.MultisigAccountAddress get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
MultisigTransactionHash
Hash256 CatSdk.Nem.Cosignature.MultisigTransactionHash get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
Network
NetworkType CatSdk.Nem.Cosignature.Network get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
Signature
Signature CatSdk.Nem.Cosignature.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.Cosignature.Cosignature().
SignerPublicKey
PublicKey CatSdk.Nem.Cosignature.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
Size
uint CatSdk.Nem.Cosignature.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Nem.SizePrefixedCosignature.Serialize().
Timestamp
Timestamp CatSdk.Nem.Cosignature.Timestamp get set
Referenced by CatSdk.Nem.Cosignature.Cosignature().
Type
TransactionType CatSdk.Nem.Cosignature.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.Cosignature.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"MultisigTransactionHash", "pod:Hash256"},
        {"MultisigAccountAddress", "pod:Address"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.Cosignature.Version get set
Referenced by CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.Cosignature.Deserialize(), and CatSdk.Nem.Cosignature.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs