SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction Class Reference
CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction Class Reference
Public Member Functions
EmbeddedMosaicSupplyRevocationTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedMosaicSupplyRevocationTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_REVOCATION
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
UnresolvedAddress SourceAddress [get, set]
UnresolvedMosaic Mosaic [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedMosaicSupplyRevocationTransaction()
CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction () inline
References CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EntityBodyReserved_1, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedMosaicSupplyRevocationTransaction CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.UnresolvedAddress.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Network, CatSdk.Symbol.UnresolvedAddress.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Size, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SourceAddress, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_REVOCATION static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction().
Property Documentation
Mosaic
UnresolvedMosaic CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
SourceAddress
UnresolvedAddress CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.SourceAddress get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"SourceAddress", "pod:UnresolvedAddress"},
        {"Mosaic", "struct:UnresolvedMosaic"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.EmbeddedMosaicSupplyRevocationTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs