SymbolCsharpDualSDK: CatSdk.Nem.PublicKey Class Reference
CatSdk.Nem.PublicKey Class Reference
Public Member Functions
PublicKey (byte[]? publicKey=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static PublicKey Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 32
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
PublicKey()
CatSdk.Nem.PublicKey.PublicKey (byte?[] publicKey = null) inline
Member Function Documentation
Deserialize()
static PublicKey CatSdk.Nem.PublicKey.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MultisigAccountModification.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.PublicKey.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Nem.Transaction.Serialize(), CatSdk.Nem.NonVerifiableTransaction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Serialize(), CatSdk.Nem.MosaicDefinition.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.MultisigAccountModification.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Nem.PublicKey.SIZE = 32 static
The documentation for this class was generated from the following file:
Nem/Models.cs