SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction Class Reference
CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction Class Reference
Public Member Functions
EmbeddedVotingKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedVotingKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.VOTING_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
VotingPublicKey LinkedPublicKey [get, set]
FinalizationEpoch StartEpoch [get, set]
FinalizationEpoch EndEpoch [get, set]
LinkAction LinkAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedVotingKeyLinkTransaction()
CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction () inline
References CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Network, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Type, CatSdk.Symbol.LinkAction.UNLINK, and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedVotingKeyLinkTransaction CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.FinalizationEpoch.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.VotingPublicKey.Deserialize(), CatSdk.Symbol.LinkAction.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Network, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Type, and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Network, CatSdk.Symbol.FinalizationEpoch.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.VotingPublicKey.Serialize(), CatSdk.Symbol.LinkAction.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Size, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Type, and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.VOTING_KEY_LINK static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction().
Property Documentation
EndEpoch
FinalizationEpoch CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EndEpoch get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
LinkAction
LinkAction CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.LinkAction get set
LinkedPublicKey
VotingPublicKey CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.LinkedPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
StartEpoch
FinalizationEpoch CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.StartEpoch get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"LinkedPublicKey", "pod:VotingPublicKey"},
        {"StartEpoch", "pod:FinalizationEpoch"},
        {"EndEpoch", "pod:FinalizationEpoch"},
        {"LinkAction", "enum:LinkAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.EmbeddedVotingKeyLinkTransaction(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs