SymbolCsharpDualSDK: CatSdk.Symbol.VotingKeyLinkTransaction Class Reference
CatSdk.Symbol.VotingKeyLinkTransaction Class Reference
Public Member Functions
VotingKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static VotingKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.VOTING_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
VotingPublicKey LinkedPublicKey [get, set]
FinalizationEpoch StartEpoch [get, set]
FinalizationEpoch EndEpoch [get, set]
LinkAction LinkAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
VotingKeyLinkTransaction()
CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction () inline
References CatSdk.Symbol.VotingKeyLinkTransaction.Deadline, CatSdk.Symbol.VotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.VotingKeyLinkTransaction.Fee, CatSdk.Symbol.VotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.VotingKeyLinkTransaction.Network, CatSdk.Symbol.VotingKeyLinkTransaction.Signature, CatSdk.Symbol.VotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.VotingKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Symbol.VotingKeyLinkTransaction.Type, CatSdk.Symbol.LinkAction.UNLINK, CatSdk.Symbol.VotingKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.VotingKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static VotingKeyLinkTransaction CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.VotingKeyLinkTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.FinalizationEpoch.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.VotingPublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.LinkAction.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.Fee, CatSdk.Symbol.VotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.VotingKeyLinkTransaction.Network, CatSdk.Symbol.VotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.Type, CatSdk.Symbol.VotingKeyLinkTransaction.Version, and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.VotingKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.VotingKeyLinkTransaction.Deadline, CatSdk.Symbol.VotingKeyLinkTransaction.EndEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.VotingKeyLinkTransaction.Fee, CatSdk.Symbol.VotingKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.VotingKeyLinkTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.FinalizationEpoch.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.VotingPublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.LinkAction.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VotingKeyLinkTransaction.Size, CatSdk.Symbol.VotingKeyLinkTransaction.StartEpoch, CatSdk.Symbol.VotingKeyLinkTransaction.Type, CatSdk.Symbol.VotingKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.VotingKeyLinkTransaction.Version.
ToString()
override string CatSdk.Symbol.VotingKeyLinkTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.VotingKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.VotingKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.VOTING_KEY_LINK static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.VotingKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.VotingKeyLinkTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.VotingKeyLinkTransaction.Deadline get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
EndEpoch
FinalizationEpoch CatSdk.Symbol.VotingKeyLinkTransaction.EndEpoch get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Fee
Amount CatSdk.Symbol.VotingKeyLinkTransaction.Fee get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
LinkAction
LinkAction CatSdk.Symbol.VotingKeyLinkTransaction.LinkAction get set
LinkedPublicKey
VotingPublicKey CatSdk.Symbol.VotingKeyLinkTransaction.LinkedPublicKey get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Network
NetworkType CatSdk.Symbol.VotingKeyLinkTransaction.Network get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Signature
Signature CatSdk.Symbol.VotingKeyLinkTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.VotingKeyLinkTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Size
uint CatSdk.Symbol.VotingKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Serialize().
StartEpoch
FinalizationEpoch CatSdk.Symbol.VotingKeyLinkTransaction.StartEpoch get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
Type
TransactionType CatSdk.Symbol.VotingKeyLinkTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
TypeHints
Dictionary<string, string> CatSdk.Symbol.VotingKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"LinkedPublicKey", "pod:VotingPublicKey"},
        {"StartEpoch", "pod:FinalizationEpoch"},
        {"EndEpoch", "pod:FinalizationEpoch"},
        {"LinkAction", "enum:LinkAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.VotingKeyLinkTransaction.Version get set
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VotingKeyLinkTransaction.VotingKeyLinkTransaction().
The documentation for this class was generated from the following file:
Symbol/Models.cs