SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedTransactionFactory Class Reference
CatSdk.Symbol.EmbeddedTransactionFactory Class Reference
Static Public Member Functions
static IBaseTransaction Deserialize (BinaryReader br)
static IBaseTransaction Deserialize (string payload)
static IBaseTransaction CreateByName (string entityName)
Member Function Documentation
CreateByName()
static IBaseTransaction CatSdk.Symbol.EmbeddedTransactionFactory.CreateByName (string entityName) inline static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded().
Deserialize() [1/2]
static IBaseTransaction CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedHashLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedSecretLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedSecretProofTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAccountMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAddressAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.TRANSACTION_TYPE, and CatSdk.Symbol.EmbeddedTransferTransaction.TRANSACTION_TYPE.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Deserialize() [2/2]
static IBaseTransaction CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize (string payload) inline static
References CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Utils.Converter.HexToBytes().
The documentation for this class was generated from the following file:
Symbol/Models.cs