SymbolCsharpDualSDK: CatSdk.Utils.ArrayHelpers Class Reference
CatSdk.Utils.ArrayHelpers Class Reference
Static Public Member Functions
static void WriteArray< T > (BinaryWriter bw, IEnumerable< T > elements)
static uint Size< T > (T[] elements, uint alignment=0, bool skipLastElementPadding=false)
static void WriteVariableSizeElements< T > (BinaryWriter bw, T[] elements, uint alignment, bool skipLastElementPadding=false)
static T[] ReadVariableSizeElements< T > (BinaryReader br, Func< BinaryReader, T > factory, uint payloadSize, int alignment, bool skipLastElementPadding=false)
static T[] ReadArray< T > (BinaryReader br, Func< BinaryReader, T > factory)
static T[] ReadArrayCount< T > (BinaryReader br, Func< BinaryReader, T > factory, byte count)
Static Private Member Functions
static void AddPadding (int size, BinaryWriter bw, int alignment)
static int GetPadding (int size, int alignment)
static void SkipPadding (int size, BinaryReader dataInputStream, int alignment)
static uint AlignUp (uint size, uint alignment)
Member Function Documentation
AddPadding()
static void CatSdk.Utils.ArrayHelpers.AddPadding (int size, BinaryWriter bw, int alignment) inline static private
References CatSdk.Utils.ArrayHelpers.GetPadding().
Referenced by CatSdk.Utils.ArrayHelpers.WriteArray< T >().
AlignUp()
static uint CatSdk.Utils.ArrayHelpers.AlignUp (uint size, uint alignment) inline static private
Calculates aligned size.
Parameters
{uint} size Size.
{uint} alignment Alignment.
Returns
{uint} Size rounded up to alignment.
Referenced by CatSdk.Utils.ArrayHelpers.Size< T >(), and CatSdk.Utils.ArrayHelpers.WriteVariableSizeElements< T >().
GetPadding()
static int CatSdk.Utils.ArrayHelpers.GetPadding (int size, int alignment) inline static private
Referenced by CatSdk.Utils.ArrayHelpers.AddPadding(), CatSdk.Utils.ArrayHelpers.ReadVariableSizeElements< T >(), and CatSdk.Utils.ArrayHelpers.SkipPadding().
ReadArray< T >()
static T[] CatSdk.Utils.ArrayHelpers.ReadArray< T > (BinaryReader br, Func< BinaryReader, T > factory) inline static
Reads array of objects.
Parameters
{BinaryReader} bufferInput Input buffer.
{Func} accessor Optional accessor used to check objects order.
Returns
{array<T>} Array of deserialized objects.
Type Constraints
T : ISerializer
ReadArrayCount< T >()
static T[] CatSdk.Utils.ArrayHelpers.ReadArrayCount< T > (BinaryReader br, Func< BinaryReader, T > factory, byte count) inline static
Reads array of deterministic number of objects.
Parameters
{BinaryReader} bufferInput A uint8 array.
{Func} accessor Optional accessor used to check objects order.
{byte} count Number of object to deserialize.
Returns
{array<T>} Array of deserialized objects.
Type Constraints
T : ISerializer
ReadVariableSizeElements< T >()
static T[] CatSdk.Utils.ArrayHelpers.ReadVariableSizeElements< T > (BinaryReader br, Func< BinaryReader, T > factory, uint payloadSize, int alignment, bool skipLastElementPadding = false) inline static
Reads array of variable size objects.
Parameters
{BinaryReader} bufferInput A uint8 array.
{Func} FactoryClass Factory used to deserialize objects.
{uint} alignment Alignment used to make sure each object is at boundary.
{bool} skipLastElementPadding true if last element is not aligned/padded.
Returns
{array<T>} Array of deserialized objects.
Type Constraints
T : ISerializer
References CatSdk.Utils.ArrayHelpers.GetPadding(), and CatSdk.Utils.ArrayHelpers.SkipPadding().
Size< T >()
static uint CatSdk.Utils.ArrayHelpers.Size< T > (T[] elements, uint alignment = 0, bool skipLastElementPadding = false) inline static
Calculates size of variable size objects.
Parameters
{array&lt;T&gt;} elements Serializable elements.
{uint} alignment Alignment used for calculations.
{bool} skipLastElementPadding true if last element should not be aligned.
Returns
{uint} Computed size.
Type Constraints
T : ISerializer
References CatSdk.Utils.ArrayHelpers.AlignUp().
SkipPadding()
static void CatSdk.Utils.ArrayHelpers.SkipPadding (int size, BinaryReader dataInputStream, int alignment) inline static private
References CatSdk.Utils.ArrayHelpers.GetPadding().
Referenced by CatSdk.Utils.ArrayHelpers.ReadVariableSizeElements< T >().
WriteArray< T >()
static void CatSdk.Utils.ArrayHelpers.WriteArray< T > (BinaryWriter bw, IEnumerable< T > elements) inline static
Type Constraints
T : ISerializer
References CatSdk.Utils.ArrayHelpers.AddPadding().
WriteVariableSizeElements< T >()
static void CatSdk.Utils.ArrayHelpers.WriteVariableSizeElements< T > (BinaryWriter bw, T[] elements, uint alignment, bool skipLastElementPadding = false) inline static
Writes array of variable size objects.
Parameters
{BinaryWriter} output An output sink.
{array&lt;T&gt;} elements Serializable elements.
{uint} alignment Alignment used to make sure each object is at boundary.
{bool} skipLastElementPadding true if last element should not be aligned/padded.
Type Constraints
T : ISerializer
References CatSdk.Utils.ArrayHelpers.AlignUp().
The documentation for this class was generated from the following file:
ArrayHelpers.cs