SymbolCsharpDualSDK: CatSdk.Nem.SizePrefixedMosaic Class Reference
CatSdk.Nem.SizePrefixedMosaic Class Reference
Public Member Functions
SizePrefixedMosaic ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SizePrefixedMosaic Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
Mosaic Mosaic [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
SizePrefixedMosaic()
CatSdk.Nem.SizePrefixedMosaic.SizePrefixedMosaic () inline
References CatSdk.Nem.SizePrefixedMosaic.Mosaic.
Referenced by CatSdk.Nem.SizePrefixedMosaic.Deserialize().
Member Function Documentation
Deserialize()
static SizePrefixedMosaic CatSdk.Nem.SizePrefixedMosaic.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.Mosaic.Deserialize(), and CatSdk.Nem.SizePrefixedMosaic.SizePrefixedMosaic().
Referenced by CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.SizePrefixedMosaic.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.Mosaic.Serialize(), and CatSdk.Nem.Mosaic.Size.
ToString()
override string CatSdk.Nem.SizePrefixedMosaic.ToString () inline
Property Documentation
Mosaic
Mosaic CatSdk.Nem.SizePrefixedMosaic.Mosaic get set
Referenced by CatSdk.Nem.SizePrefixedMosaic.SizePrefixedMosaic().
Size
uint CatSdk.Nem.SizePrefixedMosaic.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.SizePrefixedMosaic.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Mosaic", "struct:Mosaic"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs