SymbolCsharpDualSDK: CatSdk.Nem.KeyPair Class Reference
CatSdk.Nem.KeyPair Class Reference
Public Member Functions
KeyPair (PrivateKey privateKey)
Signature Sign (byte[] data)
Properties
Dictionary< string, byte[]> _keypair [get]
PrivateKey PrivateKey [get]
PublicKey PublicKey [get]
Detailed Description
Represents an ED25519 private and public key.
Constructor & Destructor Documentation
KeyPair()
CatSdk.Nem.KeyPair.KeyPair (PrivateKey privateKey) inline
Creates a key pair from a private key.
Parameters
{PrivateKey} privateKey Private key.
References CatSdk.Nem.KeyPair._keypair, CatSdk.ByteArray.bytes, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed().
Member Function Documentation
Sign()
Signature CatSdk.Nem.KeyPair.Sign (byte[] data) inline
Signs a message with the private key.
Parameters
{byte[]} message Message to sign.
Returns
{CryptoTypes.Signature} Message signature.
References CatSdk.Nem.KeyPair._keypair, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Detached().
Referenced by CatSdk.Facade.NemFacade.SignTransaction().
Property Documentation
_keypair
Dictionary<string, byte[]> CatSdk.Nem.KeyPair._keypair get private
Referenced by CatSdk.Nem.KeyPair.KeyPair(), and CatSdk.Nem.KeyPair.Sign().
PrivateKey
PrivateKey CatSdk.Nem.KeyPair.PrivateKey get
Gets the private key.
Returns
{PrivateKey} Private key.
PublicKey
PublicKey CatSdk.Nem.KeyPair.PublicKey get
Gets the public key.
Returns
{PublicKey} Public key.
The documentation for this class was generated from the following file:
Nem/KeyPair.cs