SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedAddressAliasTransaction Class Reference
CatSdk.Symbol.EmbeddedAddressAliasTransaction Class Reference
Public Member Functions
EmbeddedAddressAliasTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedAddressAliasTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.ADDRESS_ALIAS
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
NamespaceId NamespaceId [get, set]
Address Address [get, set]
AliasAction AliasAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedAddressAliasTransaction()
CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction () inline
References CatSdk.Symbol.EmbeddedAddressAliasTransaction.Address, CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedAddressAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedAddressAliasTransaction.NamespaceId, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Network, CatSdk.Symbol.EmbeddedAddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedAddressAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedAddressAliasTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Type, CatSdk.Symbol.AliasAction.UNLINK, and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedAddressAliasTransaction CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Address.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.NamespaceId.Deserialize(), CatSdk.Symbol.AliasAction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Network, CatSdk.Symbol.EmbeddedAddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Type, and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedAddressAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Network, CatSdk.Symbol.Address.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.NamespaceId.Serialize(), CatSdk.Symbol.AliasAction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Size, CatSdk.Symbol.EmbeddedAddressAliasTransaction.Type, and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedAddressAliasTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedAddressAliasTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedAddressAliasTransaction.TRANSACTION_TYPE = TransactionType.ADDRESS_ALIAS static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedAddressAliasTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction().
Property Documentation
Address
Address CatSdk.Symbol.EmbeddedAddressAliasTransaction.Address get set
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction().
AliasAction
AliasAction CatSdk.Symbol.EmbeddedAddressAliasTransaction.AliasAction get set
NamespaceId
NamespaceId CatSdk.Symbol.EmbeddedAddressAliasTransaction.NamespaceId get set
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction().
Network
NetworkType CatSdk.Symbol.EmbeddedAddressAliasTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedAddressAliasTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedAddressAliasTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedAddressAliasTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedAddressAliasTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"NamespaceId", "pod:NamespaceId"},
        {"Address", "pod:Address"},
        {"AliasAction", "enum:AliasAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedAddressAliasTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), and CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs