SymbolCsharpDualSDK: CatSdk.Symbol.AliasAction Class Reference
CatSdk.Symbol.AliasAction Class Reference
Public Member Functions
AliasAction (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static AliasAction Deserialize (BinaryReader br)
Static Public Attributes
static readonly AliasAction UNLINK = new AliasAction(0)
static readonly AliasAction LINK = new AliasAction(1)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
AliasAction()
CatSdk.Symbol.AliasAction.AliasAction (byte value = 0) inline
References CatSdk.Symbol.AliasAction.Value.
Member Function Documentation
Deserialize()
static AliasAction CatSdk.Symbol.AliasAction.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.AliasAction.Serialize () inline
References CatSdk.Symbol.AliasAction.Value.
Referenced by CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize().
ToString()
override string CatSdk.Symbol.AliasAction.ToString () inline
Member Data Documentation
LINK
readonly AliasAction CatSdk.Symbol.AliasAction.LINK = new AliasAction(1) static
UNLINK
readonly AliasAction CatSdk.Symbol.AliasAction.UNLINK = new AliasAction(0) static
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.EmbeddedAddressAliasTransaction(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.EmbeddedMosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
Property Documentation
Size
uint CatSdk.Symbol.AliasAction.Size get
Value
byte CatSdk.Symbol.AliasAction.Value get
Referenced by CatSdk.Symbol.AliasAction.AliasAction(), and CatSdk.Symbol.AliasAction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs