SymbolCsharpDualSDK: CatSdk.Nem.MosaicDefinition Class Reference
CatSdk.Nem.MosaicDefinition Class Reference
Public Member Functions
MosaicDefinition ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicDefinition Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
PublicKey OwnerPublicKey [get, set]
MosaicId Id [get, set]
byte[] Description [get, set]
SizePrefixedMosaicProperty[] Properties [get, set]
uint LevySize [get, set]
MosaicLevy Levy [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int OwnerPublicKeySize
Constructor & Destructor Documentation
MosaicDefinition()
CatSdk.Nem.MosaicDefinition.MosaicDefinition () inline
References CatSdk.Nem.MosaicDefinition.Description, CatSdk.Nem.MosaicDefinition.Id, CatSdk.Nem.MosaicDefinition.Levy, CatSdk.Nem.MosaicDefinition.LevySize, CatSdk.Nem.MosaicDefinition.OwnerPublicKey, CatSdk.Nem.MosaicDefinition.OwnerPublicKeySize, and CatSdk.Nem.MosaicDefinition.Properties.
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize().
Member Function Documentation
Deserialize()
static MosaicDefinition CatSdk.Nem.MosaicDefinition.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MosaicDefinition.Description, CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.MosaicId.Deserialize(), CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.SizePrefixedMosaicProperty.Deserialize(), CatSdk.Nem.MosaicDefinition.Id, CatSdk.Nem.MosaicDefinition.Levy, CatSdk.Nem.MosaicDefinition.LevySize, CatSdk.Nem.MosaicDefinition.MosaicDefinition(), CatSdk.Nem.MosaicDefinition.OwnerPublicKey, and CatSdk.Nem.MosaicDefinition.Properties.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicDefinition.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicDefinition.Description, CatSdk.Nem.MosaicDefinition.Id, CatSdk.Nem.MosaicDefinition.Levy, CatSdk.Nem.MosaicDefinition.LevySize, CatSdk.Nem.MosaicDefinition.OwnerPublicKey, CatSdk.Nem.MosaicDefinition.OwnerPublicKeySize, CatSdk.Nem.MosaicDefinition.Properties, CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.MosaicId.Serialize(), CatSdk.Nem.MosaicLevy.Serialize(), and CatSdk.Nem.MosaicId.Size.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), and CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize().
ToString()
override string CatSdk.Nem.MosaicDefinition.ToString () inline
References CatSdk.Nem.MosaicDefinition.LevySize.
Member Data Documentation
OwnerPublicKeySize
readonly int CatSdk.Nem.MosaicDefinition.OwnerPublicKeySize private
Referenced by CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
Property Documentation
Description
byte [] CatSdk.Nem.MosaicDefinition.Description get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
Id
MosaicId CatSdk.Nem.MosaicDefinition.Id get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
Levy
MosaicLevy CatSdk.Nem.MosaicDefinition.Levy get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
LevySize
uint CatSdk.Nem.MosaicDefinition.LevySize get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), CatSdk.Nem.MosaicDefinition.Serialize(), and CatSdk.Nem.MosaicDefinition.ToString().
OwnerPublicKey
PublicKey CatSdk.Nem.MosaicDefinition.OwnerPublicKey get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
Properties
SizePrefixedMosaicProperty [] CatSdk.Nem.MosaicDefinition.Properties get set
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinition.MosaicDefinition(), and CatSdk.Nem.MosaicDefinition.Serialize().
Size
uint CatSdk.Nem.MosaicDefinition.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), and CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicDefinition.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"OwnerPublicKey", "pod:PublicKey"},
        {"Id", "struct:MosaicId"},
        {"Description", "bytes_array"},
        {"Properties", "array[SizePrefixedMosaicProperty]"},
        {"Levy", "struct:MosaicLevy"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs