SymbolCsharpDualSDK: CatSdk.Symbol.VrfKeyLinkTransaction Class Reference
CatSdk.Symbol.VrfKeyLinkTransaction Class Reference
Public Member Functions
VrfKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static VrfKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.VRF_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
PublicKey LinkedPublicKey [get, set]
LinkAction LinkAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
VrfKeyLinkTransaction()
CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction () inline
References CatSdk.Symbol.VrfKeyLinkTransaction.Deadline, CatSdk.Symbol.VrfKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.VrfKeyLinkTransaction.Fee, CatSdk.Symbol.VrfKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.VrfKeyLinkTransaction.Network, CatSdk.Symbol.VrfKeyLinkTransaction.Signature, CatSdk.Symbol.VrfKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VrfKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.VrfKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Symbol.VrfKeyLinkTransaction.Type, CatSdk.Symbol.LinkAction.UNLINK, CatSdk.Symbol.VrfKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.VrfKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static VrfKeyLinkTransaction CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.VrfKeyLinkTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.LinkAction.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Fee, CatSdk.Symbol.VrfKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.VrfKeyLinkTransaction.Network, CatSdk.Symbol.VrfKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VrfKeyLinkTransaction.Type, CatSdk.Symbol.VrfKeyLinkTransaction.Version, and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.VrfKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.VrfKeyLinkTransaction.Deadline, CatSdk.Symbol.VrfKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.VrfKeyLinkTransaction.Fee, CatSdk.Symbol.VrfKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.VrfKeyLinkTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.LinkAction.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.VrfKeyLinkTransaction.Size, CatSdk.Symbol.VrfKeyLinkTransaction.Type, CatSdk.Symbol.VrfKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.VrfKeyLinkTransaction.Version.
ToString()
override string CatSdk.Symbol.VrfKeyLinkTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.VrfKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.VrfKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.VRF_KEY_LINK static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.VrfKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.VrfKeyLinkTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.VrfKeyLinkTransaction.Deadline get set
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Fee
Amount CatSdk.Symbol.VrfKeyLinkTransaction.Fee get set
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
LinkAction
LinkAction CatSdk.Symbol.VrfKeyLinkTransaction.LinkAction get set
LinkedPublicKey
PublicKey CatSdk.Symbol.VrfKeyLinkTransaction.LinkedPublicKey get set
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Network
NetworkType CatSdk.Symbol.VrfKeyLinkTransaction.Network get set
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Signature
Signature CatSdk.Symbol.VrfKeyLinkTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.VrfKeyLinkTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
Size
uint CatSdk.Symbol.VrfKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.VrfKeyLinkTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
TypeHints
Dictionary<string, string> CatSdk.Symbol.VrfKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"LinkedPublicKey", "pod:PublicKey"},
        {"LinkAction", "enum:LinkAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.VrfKeyLinkTransaction.Version get set
Referenced by CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), and CatSdk.Symbol.VrfKeyLinkTransaction.VrfKeyLinkTransaction().
The documentation for this class was generated from the following file:
Symbol/Models.cs