SymbolCsharpDualSDK: CatSdk.Nem.MosaicDefinitionTransaction Class Reference
CatSdk.Nem.MosaicDefinitionTransaction Class Reference
Public Member Functions
MosaicDefinitionTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicDefinitionTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_DEFINITION
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
MosaicDefinition MosaicDefinition [get, set]
Address RentalFeeSink [get, set]
Amount RentalFee [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
readonly int RentalFeeSinkSize
Constructor & Destructor Documentation
MosaicDefinitionTransaction()
CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction () inline
References CatSdk.Nem.MosaicDefinitionTransaction.Deadline, CatSdk.Nem.MosaicDefinitionTransaction.EntityBodyReserved_1, CatSdk.Nem.MosaicDefinitionTransaction.Fee, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinition, CatSdk.Nem.MosaicDefinitionTransaction.Network, CatSdk.Nem.MosaicDefinitionTransaction.RentalFee, CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSink, CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSinkSize, CatSdk.Nem.MosaicDefinitionTransaction.Signature, CatSdk.Nem.MosaicDefinitionTransaction.SignatureSize, CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKeySize, CatSdk.Nem.MosaicDefinitionTransaction.Timestamp, CatSdk.Nem.MosaicDefinitionTransaction.TRANSACTION_TYPE, CatSdk.Nem.MosaicDefinitionTransaction.TRANSACTION_VERSION, CatSdk.Nem.MosaicDefinitionTransaction.Type, and CatSdk.Nem.MosaicDefinitionTransaction.Version.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicDefinitionTransaction CatSdk.Nem.MosaicDefinitionTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MosaicDefinitionTransaction.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.Address.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.MosaicDefinition.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Fee, CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), CatSdk.Nem.MosaicDefinitionTransaction.Network, CatSdk.Nem.MosaicDefinitionTransaction.RentalFee, CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSink, CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Nem.MosaicDefinitionTransaction.Type, and CatSdk.Nem.MosaicDefinitionTransaction.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicDefinitionTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicDefinitionTransaction.Deadline, CatSdk.Nem.MosaicDefinitionTransaction.EntityBodyReserved_1, CatSdk.Nem.MosaicDefinitionTransaction.Fee, CatSdk.Nem.MosaicDefinitionTransaction.Network, CatSdk.Nem.MosaicDefinitionTransaction.RentalFee, CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSink, CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSinkSize, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.Address.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.MosaicDefinition.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.SignatureSize, CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKey, CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKeySize, CatSdk.Nem.MosaicDefinition.Size, CatSdk.Nem.MosaicDefinitionTransaction.Type, and CatSdk.Nem.MosaicDefinitionTransaction.Version.
ToString()
override string CatSdk.Nem.MosaicDefinitionTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.MosaicDefinitionTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
RentalFeeSinkSize
readonly int CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSinkSize private
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
SignatureSize
readonly int CatSdk.Nem.MosaicDefinitionTransaction.SignatureSize private
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.MosaicDefinitionTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_DEFINITION static
Referenced by CatSdk.Nem.TransactionFactory.Deserialize(), and CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
TRANSACTION_VERSION
const byte CatSdk.Nem.MosaicDefinitionTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
Property Documentation
Deadline
Timestamp CatSdk.Nem.MosaicDefinitionTransaction.Deadline get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
Fee
Amount CatSdk.Nem.MosaicDefinitionTransaction.Fee get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
MosaicDefinition
MosaicDefinition CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinition get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
Network
NetworkType CatSdk.Nem.MosaicDefinitionTransaction.Network get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
RentalFee
Amount CatSdk.Nem.MosaicDefinitionTransaction.RentalFee get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
RentalFeeSink
Address CatSdk.Nem.MosaicDefinitionTransaction.RentalFeeSink get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
Signature
Signature CatSdk.Nem.MosaicDefinitionTransaction.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
SignerPublicKey
PublicKey CatSdk.Nem.MosaicDefinitionTransaction.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
Size
uint CatSdk.Nem.MosaicDefinitionTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.MosaicDefinitionTransaction.Timestamp get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction().
Type
TransactionType CatSdk.Nem.MosaicDefinitionTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicDefinitionTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"MosaicDefinition", "struct:MosaicDefinition"},
        {"RentalFeeSink", "pod:Address"},
        {"RentalFee", "pod:Amount"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.MosaicDefinitionTransaction.Version get set
Referenced by CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), and CatSdk.Nem.MosaicDefinitionTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs