SymbolCsharpDualSDK: CatSdk.Symbol.AccountRestrictionFlags Class Reference
CatSdk.Symbol.AccountRestrictionFlags Class Reference
Public Member Functions
AccountRestrictionFlags (ushort value=0)
bool Has (uint flag)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static AccountRestrictionFlags Deserialize (BinaryReader br)
Static Public Attributes
static readonly AccountRestrictionFlags ADDRESS = new AccountRestrictionFlags(1)
static readonly AccountRestrictionFlags MOSAIC_ID = new AccountRestrictionFlags(2)
static readonly AccountRestrictionFlags TRANSACTION_TYPE = new AccountRestrictionFlags(4)
static readonly AccountRestrictionFlags OUTGOING = new AccountRestrictionFlags(16384)
static readonly AccountRestrictionFlags BLOCK = new AccountRestrictionFlags(32768)
Properties
ushort Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< ushort >
T Value [get]
Constructor & Destructor Documentation
AccountRestrictionFlags()
CatSdk.Symbol.AccountRestrictionFlags.AccountRestrictionFlags (ushort value = 0) inline
References CatSdk.Symbol.AccountRestrictionFlags.Value.
Member Function Documentation
Deserialize()
static AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Deserialize().
Has()
bool CatSdk.Symbol.AccountRestrictionFlags.Has (uint flag) inline
References CatSdk.Symbol.AccountRestrictionFlags.Value.
Serialize()
byte[] CatSdk.Symbol.AccountRestrictionFlags.Serialize () inline
References CatSdk.Symbol.AccountRestrictionFlags.Value.
Referenced by CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Serialize().
ToString()
override string CatSdk.Symbol.AccountRestrictionFlags.ToString () inline
References CatSdk.Symbol.AccountRestrictionFlags.Value.
Member Data Documentation
ADDRESS
readonly AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.ADDRESS = new AccountRestrictionFlags(1) static
Referenced by CatSdk.Symbol.AccountAddressRestrictionTransaction.AccountAddressRestrictionTransaction(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.AccountMosaicRestrictionTransaction(), CatSdk.Symbol.AccountOperationRestrictionTransaction.AccountOperationRestrictionTransaction(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.EmbeddedAccountAddressRestrictionTransaction(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.EmbeddedAccountMosaicRestrictionTransaction(), and CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.EmbeddedAccountOperationRestrictionTransaction().
BLOCK
readonly AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.BLOCK = new AccountRestrictionFlags(32768) static
MOSAIC_ID
readonly AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.MOSAIC_ID = new AccountRestrictionFlags(2) static
OUTGOING
readonly AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.OUTGOING = new AccountRestrictionFlags(16384) static
TRANSACTION_TYPE
readonly AccountRestrictionFlags CatSdk.Symbol.AccountRestrictionFlags.TRANSACTION_TYPE = new AccountRestrictionFlags(4) static
Property Documentation
Size
uint CatSdk.Symbol.AccountRestrictionFlags.Size get
Value
ushort CatSdk.Symbol.AccountRestrictionFlags.Value get
Referenced by CatSdk.Symbol.AccountRestrictionFlags.AccountRestrictionFlags(), CatSdk.Symbol.AccountRestrictionFlags.Has(), CatSdk.Symbol.AccountRestrictionFlags.Serialize(), and CatSdk.Symbol.AccountRestrictionFlags.ToString().
The documentation for this class was generated from the following file:
Symbol/Models.cs