SymbolCsharpDualSDK: CatSdk.Nem.MosaicTransferFeeType Class Reference
CatSdk.Nem.MosaicTransferFeeType Class Reference
Public Member Functions
MosaicTransferFeeType (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MosaicTransferFeeType Deserialize (BinaryReader br)
Static Public Attributes
static readonly MosaicTransferFeeType ABSOLUTE = new MosaicTransferFeeType(1)
static readonly MosaicTransferFeeType PERCENTILE = new MosaicTransferFeeType(2)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
MosaicTransferFeeType()
CatSdk.Nem.MosaicTransferFeeType.MosaicTransferFeeType (uint value = 0) inline
References CatSdk.Nem.MosaicTransferFeeType.Value.
Member Function Documentation
Deserialize()
static MosaicTransferFeeType CatSdk.Nem.MosaicTransferFeeType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.MosaicLevy.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicTransferFeeType.Serialize () inline
References CatSdk.Nem.MosaicTransferFeeType.Value.
Referenced by CatSdk.Nem.MosaicLevy.Serialize().
ToString()
override string CatSdk.Nem.MosaicTransferFeeType.ToString () inline
Member Data Documentation
ABSOLUTE
readonly MosaicTransferFeeType CatSdk.Nem.MosaicTransferFeeType.ABSOLUTE = new MosaicTransferFeeType(1) static
Referenced by CatSdk.Nem.MosaicLevy.MosaicLevy().
PERCENTILE
readonly MosaicTransferFeeType CatSdk.Nem.MosaicTransferFeeType.PERCENTILE = new MosaicTransferFeeType(2) static
Property Documentation
Size
uint CatSdk.Nem.MosaicTransferFeeType.Size get
Value
uint CatSdk.Nem.MosaicTransferFeeType.Value get
Referenced by CatSdk.Nem.MosaicTransferFeeType.MosaicTransferFeeType(), and CatSdk.Nem.MosaicTransferFeeType.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs