SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction Class Reference
CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction Class Reference
Public Member Functions
EmbeddedMosaicSupplyChangeTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedMosaicSupplyChangeTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
UnresolvedMosaicId MosaicId [get, set]
Amount Delta [get, set]
MosaicSupplyChangeAction Action [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedMosaicSupplyChangeTransaction()
CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction () inline
References CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Action, CatSdk.Symbol.MosaicSupplyChangeAction.DECREASE, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Network, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedMosaicSupplyChangeTransaction CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Action, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.UnresolvedMosaicId.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeAction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Network, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Action, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Delta, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.MosaicId.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.MosaicSupplyChangeAction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Size, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Type, and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction().
Property Documentation
Action
MosaicSupplyChangeAction CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Action get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
Delta
Amount CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Delta get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
MosaicId
UnresolvedMosaicId CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.MosaicId get set
Network
NetworkType CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"MosaicId", "pod:UnresolvedMosaicId"},
        {"Delta", "pod:Amount"},
        {"Action", "enum:MosaicSupplyChangeAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.EmbeddedMosaicSupplyChangeTransaction(), and CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs