SymbolCsharpDualSDK: CatSdk.Symbol.VotingPublicKey Class Reference
CatSdk.Symbol.VotingPublicKey Class Reference
Public Member Functions
VotingPublicKey (byte[]? votingPublicKey=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static VotingPublicKey Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 32
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
VotingPublicKey()
CatSdk.Symbol.VotingPublicKey.VotingPublicKey (byte?[] votingPublicKey = null) inline
Member Function Documentation
Deserialize()
static VotingPublicKey CatSdk.Symbol.VotingPublicKey.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.VotingPublicKey.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.VotingPublicKey.SIZE = 32 static
The documentation for this class was generated from the following file:
Symbol/Models.cs