SymbolCsharpDualSDK: CatSdk.Nem.TransactionType Class Reference
CatSdk.Nem.TransactionType Class Reference
Public Member Functions
TransactionType (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static TransactionType Deserialize (BinaryReader br)
Static Public Attributes
static readonly TransactionType TRANSFER = new TransactionType(257)
static readonly TransactionType ACCOUNT_KEY_LINK = new TransactionType(2049)
static readonly TransactionType MULTISIG_ACCOUNT_MODIFICATION = new TransactionType(4097)
static readonly TransactionType MULTISIG_COSIGNATURE = new TransactionType(4098)
static readonly TransactionType MULTISIG_TRANSACTION = new TransactionType(4100)
static readonly TransactionType NAMESPACE_REGISTRATION = new TransactionType(8193)
static readonly TransactionType MOSAIC_DEFINITION = new TransactionType(16385)
static readonly TransactionType MOSAIC_SUPPLY_CHANGE = new TransactionType(16386)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
TransactionType()
CatSdk.Nem.TransactionType.TransactionType (uint value = 0) inline
References CatSdk.Nem.TransactionType.Value.
Member Function Documentation
Deserialize()
static TransactionType CatSdk.Nem.TransactionType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.TransactionType.Serialize () inline
References CatSdk.Nem.TransactionType.Value.
Referenced by CatSdk.Nem.Transaction.Serialize(), CatSdk.Nem.NonVerifiableTransaction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
ToString()
override string CatSdk.Nem.TransactionType.ToString () inline
Member Data Documentation
ACCOUNT_KEY_LINK
readonly TransactionType CatSdk.Nem.TransactionType.ACCOUNT_KEY_LINK = new TransactionType(2049) static
MOSAIC_DEFINITION
readonly TransactionType CatSdk.Nem.TransactionType.MOSAIC_DEFINITION = new TransactionType(16385) static
MOSAIC_SUPPLY_CHANGE
readonly TransactionType CatSdk.Nem.TransactionType.MOSAIC_SUPPLY_CHANGE = new TransactionType(16386) static
MULTISIG_ACCOUNT_MODIFICATION
readonly TransactionType CatSdk.Nem.TransactionType.MULTISIG_ACCOUNT_MODIFICATION = new TransactionType(4097) static
MULTISIG_COSIGNATURE
readonly TransactionType CatSdk.Nem.TransactionType.MULTISIG_COSIGNATURE = new TransactionType(4098) static
MULTISIG_TRANSACTION
readonly TransactionType CatSdk.Nem.TransactionType.MULTISIG_TRANSACTION = new TransactionType(4100) static
NAMESPACE_REGISTRATION
readonly TransactionType CatSdk.Nem.TransactionType.NAMESPACE_REGISTRATION = new TransactionType(8193) static
TRANSFER
readonly TransactionType CatSdk.Nem.TransactionType.TRANSFER = new TransactionType(257) static
Referenced by CatSdk.Nem.Factory.TransactionsFactory.Create(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.Transaction.Transaction().
Property Documentation
Size
uint CatSdk.Nem.TransactionType.Size get
Value
uint CatSdk.Nem.TransactionType.Value get
Referenced by CatSdk.Nem.TransactionType.Serialize(), and CatSdk.Nem.TransactionType.TransactionType().
The documentation for this class was generated from the following file:
Nem/Models.cs