SymbolCsharpDualSDK: CatSdk.Nem.NetworkType Class Reference
CatSdk.Nem.NetworkType Class Reference
Public Member Functions
NetworkType (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static NetworkType Deserialize (BinaryReader br)
Static Public Attributes
static readonly NetworkType MAINNET = new NetworkType(104)
static readonly NetworkType TESTNET = new NetworkType(152)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
NetworkType()
CatSdk.Nem.NetworkType.NetworkType (byte value = 0) inline
References CatSdk.Nem.NetworkType.Value.
Member Function Documentation
Deserialize()
static NetworkType CatSdk.Nem.NetworkType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.NetworkType.Serialize () inline
References CatSdk.Nem.NetworkType.Value.
Referenced by CatSdk.Nem.Transaction.Serialize(), CatSdk.Nem.NonVerifiableTransaction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
ToString()
override string CatSdk.Nem.NetworkType.ToString () inline
Member Data Documentation
MAINNET
readonly NetworkType CatSdk.Nem.NetworkType.MAINNET = new NetworkType(104) static
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.Cosignature.Cosignature(), CatSdk.Nem.MosaicDefinitionTransaction.MosaicDefinitionTransaction(), CatSdk.Nem.MosaicSupplyChangeTransaction.MosaicSupplyChangeTransaction(), CatSdk.Nem.MultisigAccountModificationTransaction.MultisigAccountModificationTransaction(), CatSdk.Nem.MultisigAccountModificationTransactionV1.MultisigAccountModificationTransactionV1(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), CatSdk.Nem.NamespaceRegistrationTransaction.NamespaceRegistrationTransaction(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.NonVerifiableAccountKeyLinkTransaction(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.NonVerifiableMosaicDefinitionTransaction(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.NonVerifiableMultisigAccountModificationTransaction(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.NonVerifiableMultisigAccountModificationTransactionV1(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.NonVerifiableNamespaceRegistrationTransaction(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), CatSdk.Nem.NonVerifiableTransferTransaction.NonVerifiableTransferTransaction(), CatSdk.Nem.NonVerifiableTransferTransactionV1.NonVerifiableTransferTransactionV1(), CatSdk.Nem.Transaction.Transaction(), CatSdk.Nem.TransferTransaction.TransferTransaction(), and CatSdk.Nem.TransferTransactionV1.TransferTransactionV1().
TESTNET
readonly NetworkType CatSdk.Nem.NetworkType.TESTNET = new NetworkType(152) static
Referenced by CatSdk.Nem.Factory.TransactionsFactory.Create().
Property Documentation
Size
uint CatSdk.Nem.NetworkType.Size get
Value
byte CatSdk.Nem.NetworkType.Value get
Referenced by CatSdk.Nem.NetworkType.NetworkType(), and CatSdk.Nem.NetworkType.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs