SymbolCsharpDualSDK: CatSdk.Symbol.KeyPair Class Reference
CatSdk.Symbol.KeyPair Class Reference
Public Member Functions
KeyPair (PrivateKey privateKey)
Signature Sign (byte[] data)
Properties
PrivateKey PrivateKey [get]
PublicKey PublicKey [get]
Static Private Member Functions
static PublicKey CreatePublicKey (PrivateKey privateKey)
Detailed Description
Represents an ED25519 private and public key.
Constructor & Destructor Documentation
KeyPair()
CatSdk.Symbol.KeyPair.KeyPair (PrivateKey privateKey) inline
Creates a key pair from a private key.
Parameters
{PrivateKey} privateKey Private key.
References CatSdk.Symbol.KeyPair.CreatePublicKey().
Member Function Documentation
CreatePublicKey()
static PublicKey CatSdk.Symbol.KeyPair.CreatePublicKey (PrivateKey privateKey) inline static private
References CatSdk.ByteArray.bytes, and CatSdk.Symbol.KeyPair.PublicKey.
Referenced by CatSdk.Symbol.KeyPair.KeyPair().
Sign()
Signature CatSdk.Symbol.KeyPair.Sign (byte[] data) inline
Signs a message with the private key.
Parameters
{byte[]} message Message to sign.
Returns
{Signature} Message signature.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Facade.SymbolFacade.SignTransaction().
Property Documentation
PrivateKey
PrivateKey CatSdk.Symbol.KeyPair.PrivateKey get
Gets the private key.
Returns
{PrivateKey} Private key.
PublicKey
PublicKey CatSdk.Symbol.KeyPair.PublicKey get
Gets the public key.
Returns
{PublicKey} Public key.
Referenced by CatSdk.Symbol.KeyPair.CreatePublicKey().
The documentation for this class was generated from the following file:
Symbol/KeyPair.cs