SymbolCsharpDualSDK: CatSdk.Symbol.MosaicAliasTransaction Class Reference
CatSdk.Symbol.MosaicAliasTransaction Class Reference
Public Member Functions
MosaicAliasTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicAliasTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_ALIAS
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
NamespaceId NamespaceId [get, set]
MosaicId MosaicId [get, set]
AliasAction AliasAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
MosaicAliasTransaction()
CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction () inline
References CatSdk.Symbol.MosaicAliasTransaction.Deadline, CatSdk.Symbol.MosaicAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicAliasTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.MosaicAliasTransaction.MosaicId, CatSdk.Symbol.MosaicAliasTransaction.NamespaceId, CatSdk.Symbol.MosaicAliasTransaction.Network, CatSdk.Symbol.MosaicAliasTransaction.Signature, CatSdk.Symbol.MosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.MosaicAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicAliasTransaction.TRANSACTION_VERSION, CatSdk.Symbol.MosaicAliasTransaction.Type, CatSdk.Symbol.AliasAction.UNLINK, CatSdk.Symbol.MosaicAliasTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicAliasTransaction.Version.
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MosaicAliasTransaction CatSdk.Symbol.MosaicAliasTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.MosaicAliasTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.MosaicId.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.NamespaceId.Deserialize(), CatSdk.Symbol.AliasAction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Fee, CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), CatSdk.Symbol.MosaicAliasTransaction.Network, CatSdk.Symbol.MosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.MosaicAliasTransaction.Type, and CatSdk.Symbol.MosaicAliasTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicAliasTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.MosaicAliasTransaction.Deadline, CatSdk.Symbol.MosaicAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.MosaicAliasTransaction.Fee, CatSdk.Symbol.MosaicAliasTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.MosaicId.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.NamespaceId.Serialize(), CatSdk.Symbol.AliasAction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.SignerPublicKey, CatSdk.Symbol.MosaicAliasTransaction.Size, CatSdk.Symbol.MosaicAliasTransaction.Type, CatSdk.Symbol.MosaicAliasTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.MosaicAliasTransaction.Version.
ToString()
override string CatSdk.Symbol.MosaicAliasTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.MosaicAliasTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.MosaicAliasTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_ALIAS static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.MosaicAliasTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.MosaicAliasTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
Property Documentation
AliasAction
AliasAction CatSdk.Symbol.MosaicAliasTransaction.AliasAction get set
Deadline
Timestamp CatSdk.Symbol.MosaicAliasTransaction.Deadline get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
Fee
Amount CatSdk.Symbol.MosaicAliasTransaction.Fee get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
MosaicId
MosaicId CatSdk.Symbol.MosaicAliasTransaction.MosaicId get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
NamespaceId
NamespaceId CatSdk.Symbol.MosaicAliasTransaction.NamespaceId get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
Network
NetworkType CatSdk.Symbol.MosaicAliasTransaction.Network get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
Signature
Signature CatSdk.Symbol.MosaicAliasTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.MosaicAliasTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
Size
uint CatSdk.Symbol.MosaicAliasTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.MosaicAliasTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.MosaicAliasTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"NamespaceId", "pod:NamespaceId"},
        {"MosaicId", "pod:MosaicId"},
        {"AliasAction", "enum:AliasAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.MosaicAliasTransaction.Version get set
Referenced by CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.MosaicAliasTransaction(), and CatSdk.Symbol.MosaicAliasTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs