SymbolCsharpDualSDK: CatSdk.Symbol.SecretLockTransaction Class Reference
CatSdk.Symbol.SecretLockTransaction Class Reference
Public Member Functions
SecretLockTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SecretLockTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.SECRET_LOCK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
UnresolvedAddress RecipientAddress [get, set]
Hash256 Secret [get, set]
UnresolvedMosaic Mosaic [get, set]
BlockDuration Duration [get, set]
LockHashAlgorithm HashAlgorithm [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
SecretLockTransaction()
CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction () inline
References CatSdk.Symbol.SecretLockTransaction.Deadline, CatSdk.Symbol.SecretLockTransaction.Duration, CatSdk.Symbol.SecretLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.SecretLockTransaction.Fee, CatSdk.Symbol.SecretLockTransaction.HashAlgorithm, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.SecretLockTransaction.Network, CatSdk.Symbol.SecretLockTransaction.RecipientAddress, CatSdk.Symbol.SecretLockTransaction.Secret, CatSdk.Symbol.LockHashAlgorithm.SHA3_256, CatSdk.Symbol.SecretLockTransaction.Signature, CatSdk.Symbol.SecretLockTransaction.SignerPublicKey, CatSdk.Symbol.SecretLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.SecretLockTransaction.TRANSACTION_VERSION, CatSdk.Symbol.SecretLockTransaction.Type, CatSdk.Symbol.SecretLockTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.SecretLockTransaction.Version.
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize().
Member Function Documentation
Deserialize()
static SecretLockTransaction CatSdk.Symbol.SecretLockTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.SecretLockTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.BlockDuration.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.UnresolvedAddress.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.LockHashAlgorithm.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Duration, CatSdk.Symbol.SecretLockTransaction.Fee, CatSdk.Symbol.SecretLockTransaction.HashAlgorithm, CatSdk.Symbol.SecretLockTransaction.Network, CatSdk.Symbol.SecretLockTransaction.RecipientAddress, CatSdk.Symbol.SecretLockTransaction.Secret, CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), CatSdk.Symbol.SecretLockTransaction.SignerPublicKey, CatSdk.Symbol.SecretLockTransaction.Type, and CatSdk.Symbol.SecretLockTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.SecretLockTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.SecretLockTransaction.Deadline, CatSdk.Symbol.SecretLockTransaction.Duration, CatSdk.Symbol.SecretLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.SecretLockTransaction.Fee, CatSdk.Symbol.SecretLockTransaction.HashAlgorithm, CatSdk.Symbol.SecretLockTransaction.Network, CatSdk.Symbol.SecretLockTransaction.RecipientAddress, CatSdk.Symbol.SecretLockTransaction.Secret, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.BlockDuration.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.UnresolvedAddress.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.LockHashAlgorithm.Serialize(), CatSdk.Symbol.SecretLockTransaction.SignerPublicKey, CatSdk.Symbol.SecretLockTransaction.Size, CatSdk.Symbol.SecretLockTransaction.Type, CatSdk.Symbol.SecretLockTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.SecretLockTransaction.Version.
ToString()
override string CatSdk.Symbol.SecretLockTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.SecretLockTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.SecretLockTransaction.TRANSACTION_TYPE = TransactionType.SECRET_LOCK static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.SecretLockTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.SecretLockTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.SecretLockTransaction.Deadline get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Duration
BlockDuration CatSdk.Symbol.SecretLockTransaction.Duration get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Fee
Amount CatSdk.Symbol.SecretLockTransaction.Fee get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
HashAlgorithm
LockHashAlgorithm CatSdk.Symbol.SecretLockTransaction.HashAlgorithm get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Mosaic
UnresolvedMosaic CatSdk.Symbol.SecretLockTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.SecretLockTransaction.Network get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
RecipientAddress
UnresolvedAddress CatSdk.Symbol.SecretLockTransaction.RecipientAddress get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Secret
Hash256 CatSdk.Symbol.SecretLockTransaction.Secret get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Signature
Signature CatSdk.Symbol.SecretLockTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.SecretLockTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
Size
uint CatSdk.Symbol.SecretLockTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.SecretLockTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.SecretLockTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.SecretLockTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"RecipientAddress", "pod:UnresolvedAddress"},
        {"Secret", "pod:Hash256"},
        {"Mosaic", "struct:UnresolvedMosaic"},
        {"Duration", "pod:BlockDuration"},
        {"HashAlgorithm", "enum:LockHashAlgorithm"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.SecretLockTransaction.Version get set
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretLockTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs