SymbolCsharpDualSDK: CatSdk.Nem.LinkAction Class Reference
CatSdk.Nem.LinkAction Class Reference
Public Member Functions
LinkAction (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static LinkAction Deserialize (BinaryReader br)
Static Public Attributes
static readonly LinkAction LINK = new LinkAction(1)
static readonly LinkAction UNLINK = new LinkAction(2)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
LinkAction()
CatSdk.Nem.LinkAction.LinkAction (uint value = 0) inline
References CatSdk.Nem.LinkAction.Value.
Member Function Documentation
Deserialize()
static LinkAction CatSdk.Nem.LinkAction.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.LinkAction.Serialize () inline
References CatSdk.Nem.LinkAction.Value.
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), and CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Serialize().
ToString()
override string CatSdk.Nem.LinkAction.ToString () inline
Member Data Documentation
LINK
readonly LinkAction CatSdk.Nem.LinkAction.LINK = new LinkAction(1) static
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.NonVerifiableAccountKeyLinkTransaction().
UNLINK
readonly LinkAction CatSdk.Nem.LinkAction.UNLINK = new LinkAction(2) static
Property Documentation
Size
uint CatSdk.Nem.LinkAction.Size get
Value
uint CatSdk.Nem.LinkAction.Value get
Referenced by CatSdk.Nem.LinkAction.LinkAction(), and CatSdk.Nem.LinkAction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs