SymbolCsharpDualSDK: CatSdk.Nem.MosaicProperty Class Reference
CatSdk.Nem.MosaicProperty Class Reference
Public Member Functions
MosaicProperty ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicProperty Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
byte[] Name [get, set]
byte[] Value [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
MosaicProperty()
CatSdk.Nem.MosaicProperty.MosaicProperty () inline
References CatSdk.Nem.MosaicProperty.Name, and CatSdk.Nem.MosaicProperty.Value.
Referenced by CatSdk.Nem.MosaicProperty.Deserialize().
Member Function Documentation
Deserialize()
static MosaicProperty CatSdk.Nem.MosaicProperty.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MosaicProperty.MosaicProperty(), CatSdk.Nem.MosaicProperty.Name, and CatSdk.Nem.MosaicProperty.Value.
Referenced by CatSdk.Nem.SizePrefixedMosaicProperty.Deserialize().
Serialize()
byte[] CatSdk.Nem.MosaicProperty.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MosaicProperty.Name, and CatSdk.Nem.MosaicProperty.Value.
Referenced by CatSdk.Nem.SizePrefixedMosaicProperty.Serialize().
ToString()
override string CatSdk.Nem.MosaicProperty.ToString () inline
Property Documentation
Name
byte [] CatSdk.Nem.MosaicProperty.Name get set
Referenced by CatSdk.Nem.MosaicProperty.Deserialize(), CatSdk.Nem.MosaicProperty.MosaicProperty(), and CatSdk.Nem.MosaicProperty.Serialize().
Size
uint CatSdk.Nem.MosaicProperty.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Nem.SizePrefixedMosaicProperty.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MosaicProperty.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Name", "bytes_array"},
        {"Value", "bytes_array"}
    }
Implements CatSdk.IStruct.
Value
byte [] CatSdk.Nem.MosaicProperty.Value get set
Referenced by CatSdk.Nem.MosaicProperty.Deserialize(), CatSdk.Nem.MosaicProperty.MosaicProperty(), and CatSdk.Nem.MosaicProperty.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs