SymbolCsharpDualSDK: CatSdk.Symbol.MosaicRestrictionType Class Reference
CatSdk.Symbol.MosaicRestrictionType Class Reference
Public Member Functions
MosaicRestrictionType (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MosaicRestrictionType Deserialize (BinaryReader br)
Static Public Attributes
static readonly MosaicRestrictionType NONE = new MosaicRestrictionType(0)
static readonly MosaicRestrictionType EQ = new MosaicRestrictionType(1)
static readonly MosaicRestrictionType NE = new MosaicRestrictionType(2)
static readonly MosaicRestrictionType LT = new MosaicRestrictionType(3)
static readonly MosaicRestrictionType LE = new MosaicRestrictionType(4)
static readonly MosaicRestrictionType GT = new MosaicRestrictionType(5)
static readonly MosaicRestrictionType GE = new MosaicRestrictionType(6)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
MosaicRestrictionType()
CatSdk.Symbol.MosaicRestrictionType.MosaicRestrictionType (byte value = 0) inline
References CatSdk.Symbol.MosaicRestrictionType.Value.
Member Function Documentation
Deserialize()
static MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicRestrictionType.Serialize () inline
References CatSdk.Symbol.MosaicRestrictionType.Value.
Referenced by CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize().
ToString()
override string CatSdk.Symbol.MosaicRestrictionType.ToString () inline
Member Data Documentation
EQ
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.EQ = new MosaicRestrictionType(1) static
GE
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.GE = new MosaicRestrictionType(6) static
GT
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.GT = new MosaicRestrictionType(5) static
LE
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.LE = new MosaicRestrictionType(4) static
LT
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.LT = new MosaicRestrictionType(3) static
NE
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.NE = new MosaicRestrictionType(2) static
NONE
readonly MosaicRestrictionType CatSdk.Symbol.MosaicRestrictionType.NONE = new MosaicRestrictionType(0) static
Referenced by CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.EmbeddedMosaicGlobalRestrictionTransaction(), and CatSdk.Symbol.MosaicGlobalRestrictionTransaction.MosaicGlobalRestrictionTransaction().
Property Documentation
Size
uint CatSdk.Symbol.MosaicRestrictionType.Size get
Value
byte CatSdk.Symbol.MosaicRestrictionType.Value get
Referenced by CatSdk.Symbol.MosaicRestrictionType.MosaicRestrictionType(), and CatSdk.Symbol.MosaicRestrictionType.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs