SymbolCsharpDualSDK: CatSdk.Nem.AccountKeyLinkTransaction Class Reference
CatSdk.Nem.AccountKeyLinkTransaction Class Reference
Public Member Functions
AccountKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static AccountKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.ACCOUNT_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
LinkAction LinkAction [get, set]
PublicKey RemotePublicKey [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
readonly int RemotePublicKeySize
Constructor & Destructor Documentation
AccountKeyLinkTransaction()
CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction () inline
References CatSdk.Nem.AccountKeyLinkTransaction.Deadline, CatSdk.Nem.AccountKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Nem.AccountKeyLinkTransaction.Fee, CatSdk.Nem.LinkAction.LINK, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.AccountKeyLinkTransaction.Network, CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKey, CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKeySize, CatSdk.Nem.AccountKeyLinkTransaction.Signature, CatSdk.Nem.AccountKeyLinkTransaction.SignatureSize, CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKeySize, CatSdk.Nem.AccountKeyLinkTransaction.Timestamp, CatSdk.Nem.AccountKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Nem.AccountKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Nem.AccountKeyLinkTransaction.Type, and CatSdk.Nem.AccountKeyLinkTransaction.Version.
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static AccountKeyLinkTransaction CatSdk.Nem.AccountKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.LinkAction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Fee, CatSdk.Nem.AccountKeyLinkTransaction.Network, CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKey, CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Nem.AccountKeyLinkTransaction.Type, and CatSdk.Nem.AccountKeyLinkTransaction.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.AccountKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.AccountKeyLinkTransaction.Deadline, CatSdk.Nem.AccountKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Nem.AccountKeyLinkTransaction.Fee, CatSdk.Nem.AccountKeyLinkTransaction.Network, CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKey, CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKeySize, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.LinkAction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.SignatureSize, CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKeySize, CatSdk.Nem.AccountKeyLinkTransaction.Type, and CatSdk.Nem.AccountKeyLinkTransaction.Version.
ToString()
override string CatSdk.Nem.AccountKeyLinkTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.AccountKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
RemotePublicKeySize
readonly int CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKeySize private
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
SignatureSize
readonly int CatSdk.Nem.AccountKeyLinkTransaction.SignatureSize private
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.AccountKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.ACCOUNT_KEY_LINK static
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Nem.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Nem.AccountKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction().
Property Documentation
Deadline
Timestamp CatSdk.Nem.AccountKeyLinkTransaction.Deadline get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
Fee
Amount CatSdk.Nem.AccountKeyLinkTransaction.Fee get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
LinkAction
LinkAction CatSdk.Nem.AccountKeyLinkTransaction.LinkAction get set
Network
NetworkType CatSdk.Nem.AccountKeyLinkTransaction.Network get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
RemotePublicKey
PublicKey CatSdk.Nem.AccountKeyLinkTransaction.RemotePublicKey get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
Signature
Signature CatSdk.Nem.AccountKeyLinkTransaction.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction().
SignerPublicKey
PublicKey CatSdk.Nem.AccountKeyLinkTransaction.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
Size
uint CatSdk.Nem.AccountKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.AccountKeyLinkTransaction.Timestamp get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction().
Type
TransactionType CatSdk.Nem.AccountKeyLinkTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.AccountKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"LinkAction", "enum:LinkAction"},
        {"RemotePublicKey", "pod:PublicKey"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.AccountKeyLinkTransaction.Version get set
Referenced by CatSdk.Nem.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Nem.AccountKeyLinkTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs