SymbolCsharpDualSDK: CatSdk.Symbol.NamespaceRegistrationType Class Reference
CatSdk.Symbol.NamespaceRegistrationType Class Reference
Public Member Functions
NamespaceRegistrationType (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static NamespaceRegistrationType Deserialize (BinaryReader br)
Static Public Attributes
static readonly NamespaceRegistrationType ROOT = new NamespaceRegistrationType(0)
static readonly NamespaceRegistrationType CHILD = new NamespaceRegistrationType(1)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
NamespaceRegistrationType()
CatSdk.Symbol.NamespaceRegistrationType.NamespaceRegistrationType (byte value = 0) inline
References CatSdk.Symbol.NamespaceRegistrationType.Value.
Member Function Documentation
Deserialize()
static NamespaceRegistrationType CatSdk.Symbol.NamespaceRegistrationType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.NamespaceRegistrationType.Serialize () inline
References CatSdk.Symbol.NamespaceRegistrationType.Value.
Referenced by CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize().
ToString()
override string CatSdk.Symbol.NamespaceRegistrationType.ToString () inline
Member Data Documentation
CHILD
readonly NamespaceRegistrationType CatSdk.Symbol.NamespaceRegistrationType.CHILD = new NamespaceRegistrationType(1) static
Referenced by CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.ToString(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.ToString().
ROOT
readonly NamespaceRegistrationType CatSdk.Symbol.NamespaceRegistrationType.ROOT = new NamespaceRegistrationType(0) static
Referenced by CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.EmbeddedNamespaceRegistrationTransaction(), CatSdk.Symbol.NamespaceRegistrationTransaction.NamespaceRegistrationTransaction(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.ToString(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.ToString().
Property Documentation
Size
uint CatSdk.Symbol.NamespaceRegistrationType.Size get
Value
byte CatSdk.Symbol.NamespaceRegistrationType.Value get
Referenced by CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationType.NamespaceRegistrationType(), CatSdk.Symbol.NamespaceRegistrationType.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.ToString(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.ToString().
The documentation for this class was generated from the following file:
Symbol/Models.cs