SymbolCsharpDualSDK: CatSdk.Nem.SizePrefixedMultisigAccountModification Class Reference
CatSdk.Nem.SizePrefixedMultisigAccountModification Class Reference
Public Member Functions
SizePrefixedMultisigAccountModification ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SizePrefixedMultisigAccountModification Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MultisigAccountModification Modification [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
SizePrefixedMultisigAccountModification()
CatSdk.Nem.SizePrefixedMultisigAccountModification.SizePrefixedMultisigAccountModification () inline
References CatSdk.Nem.SizePrefixedMultisigAccountModification.Modification.
Referenced by CatSdk.Nem.SizePrefixedMultisigAccountModification.Deserialize().
Member Function Documentation
Deserialize()
static SizePrefixedMultisigAccountModification CatSdk.Nem.SizePrefixedMultisigAccountModification.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MultisigAccountModification.Deserialize(), CatSdk.Nem.SizePrefixedMultisigAccountModification.Modification, and CatSdk.Nem.SizePrefixedMultisigAccountModification.SizePrefixedMultisigAccountModification().
Referenced by CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.SizePrefixedMultisigAccountModification.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.SizePrefixedMultisigAccountModification.Modification, CatSdk.Nem.MultisigAccountModification.Serialize(), and CatSdk.Nem.MultisigAccountModification.Size.
ToString()
override string CatSdk.Nem.SizePrefixedMultisigAccountModification.ToString () inline
Property Documentation
Modification
MultisigAccountModification CatSdk.Nem.SizePrefixedMultisigAccountModification.Modification get set
Referenced by CatSdk.Nem.SizePrefixedMultisigAccountModification.Deserialize(), CatSdk.Nem.SizePrefixedMultisigAccountModification.Serialize(), and CatSdk.Nem.SizePrefixedMultisigAccountModification.SizePrefixedMultisigAccountModification().
Size
uint CatSdk.Nem.SizePrefixedMultisigAccountModification.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.SizePrefixedMultisigAccountModification.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Modification", "struct:MultisigAccountModification"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs