SymbolCsharpDualSDK: CatSdk.Symbol.TransactionType Class Reference
CatSdk.Symbol.TransactionType Class Reference
Public Member Functions
TransactionType (ushort value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static TransactionType Deserialize (BinaryReader br)
Static Public Attributes
static readonly TransactionType ACCOUNT_KEY_LINK = new TransactionType(16716)
static readonly TransactionType NODE_KEY_LINK = new TransactionType(16972)
static readonly TransactionType AGGREGATE_COMPLETE = new TransactionType(16705)
static readonly TransactionType AGGREGATE_BONDED = new TransactionType(16961)
static readonly TransactionType VOTING_KEY_LINK = new TransactionType(16707)
static readonly TransactionType VRF_KEY_LINK = new TransactionType(16963)
static readonly TransactionType HASH_LOCK = new TransactionType(16712)
static readonly TransactionType SECRET_LOCK = new TransactionType(16722)
static readonly TransactionType SECRET_PROOF = new TransactionType(16978)
static readonly TransactionType ACCOUNT_METADATA = new TransactionType(16708)
static readonly TransactionType MOSAIC_METADATA = new TransactionType(16964)
static readonly TransactionType NAMESPACE_METADATA = new TransactionType(17220)
static readonly TransactionType MOSAIC_DEFINITION = new TransactionType(16717)
static readonly TransactionType MOSAIC_SUPPLY_CHANGE = new TransactionType(16973)
static readonly TransactionType MOSAIC_SUPPLY_REVOCATION = new TransactionType(17229)
static readonly TransactionType MULTISIG_ACCOUNT_MODIFICATION = new TransactionType(16725)
static readonly TransactionType ADDRESS_ALIAS = new TransactionType(16974)
static readonly TransactionType MOSAIC_ALIAS = new TransactionType(17230)
static readonly TransactionType NAMESPACE_REGISTRATION = new TransactionType(16718)
static readonly TransactionType ACCOUNT_ADDRESS_RESTRICTION = new TransactionType(16720)
static readonly TransactionType ACCOUNT_MOSAIC_RESTRICTION = new TransactionType(16976)
static readonly TransactionType ACCOUNT_OPERATION_RESTRICTION = new TransactionType(17232)
static readonly TransactionType MOSAIC_ADDRESS_RESTRICTION = new TransactionType(16977)
static readonly TransactionType MOSAIC_GLOBAL_RESTRICTION = new TransactionType(16721)
static readonly TransactionType TRANSFER = new TransactionType(16724)
Properties
ushort Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< ushort >
T Value [get]
Constructor & Destructor Documentation
TransactionType()
CatSdk.Symbol.TransactionType.TransactionType (ushort value = 0) inline
References CatSdk.Symbol.TransactionType.Value.
Member Function Documentation
Deserialize()
static TransactionType CatSdk.Symbol.TransactionType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.TransactionType.Serialize () inline
References CatSdk.Symbol.TransactionType.Value.
Referenced by CatSdk.Symbol.Transaction.Serialize(), CatSdk.Symbol.EmbeddedTransaction.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.TransferTransaction.Serialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Serialize().
ToString()
override string CatSdk.Symbol.TransactionType.ToString () inline
Member Data Documentation
ACCOUNT_ADDRESS_RESTRICTION
readonly TransactionType CatSdk.Symbol.TransactionType.ACCOUNT_ADDRESS_RESTRICTION = new TransactionType(16720) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
ACCOUNT_KEY_LINK
readonly TransactionType CatSdk.Symbol.TransactionType.ACCOUNT_KEY_LINK = new TransactionType(16716) static
Referenced by CatSdk.Symbol.EmbeddedTransaction.EmbeddedTransaction(), CatSdk.Symbol.Transaction.Transaction(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
ACCOUNT_METADATA
readonly TransactionType CatSdk.Symbol.TransactionType.ACCOUNT_METADATA = new TransactionType(16708) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
ACCOUNT_MOSAIC_RESTRICTION
readonly TransactionType CatSdk.Symbol.TransactionType.ACCOUNT_MOSAIC_RESTRICTION = new TransactionType(16976) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
ACCOUNT_OPERATION_RESTRICTION
readonly TransactionType CatSdk.Symbol.TransactionType.ACCOUNT_OPERATION_RESTRICTION = new TransactionType(17232) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
ADDRESS_ALIAS
readonly TransactionType CatSdk.Symbol.TransactionType.ADDRESS_ALIAS = new TransactionType(16974) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
AGGREGATE_BONDED
readonly TransactionType CatSdk.Symbol.TransactionType.AGGREGATE_BONDED = new TransactionType(16961) static
Referenced by CatSdk.Facade.SymbolFacade.IsAggregateTransaction(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
AGGREGATE_COMPLETE
readonly TransactionType CatSdk.Symbol.TransactionType.AGGREGATE_COMPLETE = new TransactionType(16705) static
Referenced by CatSdk.Facade.SymbolFacade.IsAggregateTransaction(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
HASH_LOCK
readonly TransactionType CatSdk.Symbol.TransactionType.HASH_LOCK = new TransactionType(16712) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_ADDRESS_RESTRICTION
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_ADDRESS_RESTRICTION = new TransactionType(16977) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_ALIAS
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_ALIAS = new TransactionType(17230) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_DEFINITION
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_DEFINITION = new TransactionType(16717) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_GLOBAL_RESTRICTION
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_GLOBAL_RESTRICTION = new TransactionType(16721) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_METADATA
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_METADATA = new TransactionType(16964) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_SUPPLY_CHANGE
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_SUPPLY_CHANGE = new TransactionType(16973) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MOSAIC_SUPPLY_REVOCATION
readonly TransactionType CatSdk.Symbol.TransactionType.MOSAIC_SUPPLY_REVOCATION = new TransactionType(17229) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
MULTISIG_ACCOUNT_MODIFICATION
readonly TransactionType CatSdk.Symbol.TransactionType.MULTISIG_ACCOUNT_MODIFICATION = new TransactionType(16725) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
NAMESPACE_METADATA
readonly TransactionType CatSdk.Symbol.TransactionType.NAMESPACE_METADATA = new TransactionType(17220) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
NAMESPACE_REGISTRATION
readonly TransactionType CatSdk.Symbol.TransactionType.NAMESPACE_REGISTRATION = new TransactionType(16718) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create(), CatSdk.Symbol.Factory.TransactionsFactory.CreateEmbedded(), and CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
NODE_KEY_LINK
readonly TransactionType CatSdk.Symbol.TransactionType.NODE_KEY_LINK = new TransactionType(16972) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
SECRET_LOCK
readonly TransactionType CatSdk.Symbol.TransactionType.SECRET_LOCK = new TransactionType(16722) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
SECRET_PROOF
readonly TransactionType CatSdk.Symbol.TransactionType.SECRET_PROOF = new TransactionType(16978) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
TRANSFER
readonly TransactionType CatSdk.Symbol.TransactionType.TRANSFER = new TransactionType(16724) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
VOTING_KEY_LINK
readonly TransactionType CatSdk.Symbol.TransactionType.VOTING_KEY_LINK = new TransactionType(16707) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
VRF_KEY_LINK
readonly TransactionType CatSdk.Symbol.TransactionType.VRF_KEY_LINK = new TransactionType(16963) static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.TransactionTypeToString().
Property Documentation
Size
uint CatSdk.Symbol.TransactionType.Size get
Value
ushort CatSdk.Symbol.TransactionType.Value get
Referenced by CatSdk.Facade.SymbolFacade.IsAggregateTransaction(), CatSdk.Symbol.TransactionType.Serialize(), and CatSdk.Symbol.TransactionType.TransactionType().
The documentation for this class was generated from the following file:
Symbol/Models.cs