SymbolCsharpDualSDK: CatSdk.Nem.External.TweetnaclNaclFastKeccak Class Reference
CatSdk.Nem.External.TweetnaclNaclFastKeccak Class Reference
Static Public Member Functions
static Dictionary< string, byte[]> FromSeed (byte[] seed)
static void ModL (byte[] r, decimal[] x)
static void Reduce (byte[] r)
static int CryptoSign (byte[] sm, byte[] m, int n, byte[] sk)
static byte[] Sign (byte[] msg, byte[] secretKey)
static byte[] Detached (byte[] msg, byte[] secretKey)
static int Unpackneg (long[][] r, byte[] p)
static int CryptoSignOpen (byte[] m, byte[] sm, int n, byte[] pk)
static bool Verify (byte[] msg, byte[] sig, byte[] publicKey)
Static Private Member Functions
static void ScalarBase (long[][] p, byte[] s)
static void CryptoHash (IList< byte > outArr, byte[] m, int n)
static void CryptoSignKeypair (long[] pk, byte[] sk, bool seeded)
Static Private Attributes
static decimal[] L
static long[] gf0 = NaclCatapult.Gf()
static long[] gf1 = NaclCatapult.Gf(new long[]{1})
static long[] _121665 = NaclCatapult.Gf(new long[]{0xdb41, 1})
static long[] D = NaclCatapult.Gf(new long[]{0x78a3, 0x1359, 0x4dca, 0x75eb, 0xd8ab, 0x4141, 0x0a4d, 0x0070, 0xe898, 0x7779, 0x4079, 0x8cc7, 0xfe73, 0x2b6f, 0x6cee, 0x5203})
static long[] D2 = NaclCatapult.Gf(new long[]{0xf159, 0x26b2, 0x9b94, 0xebd6, 0xb156, 0x8283, 0x149a, 0x00e0, 0xd130, 0xeef3, 0x80f2, 0x198e, 0xfce7, 0x56df, 0xd9dc, 0x2406})
static long[] X = NaclCatapult.Gf(new long[]{0xd51a, 0x8f25, 0x2d60, 0xc956, 0xa7b2, 0x9525, 0xc760, 0x692c, 0xdc5c, 0xfdd6, 0xe231, 0xc0a4, 0x53fe, 0xcd6e, 0x36d3, 0x2169})
static long[] Y = NaclCatapult.Gf(new long[]{0x6658, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666})
static long[] I = NaclCatapult.Gf(new long[]{0xa0b0, 0x4a0e, 0x1b27, 0xc4ee, 0xe478, 0xad2f, 0x1806, 0x2f43, 0xd7a7, 0x3dfb, 0x0099, 0x2b4d, 0xdf0b, 0x4fc1, 0x2480, 0x2b83})
const int crypto_secretbox_KEYBYTES = 32
const int crypto_secretbox_NONCEBYTES = 24
const int crypto_secretbox_ZEROBYTES = 32
const int crypto_secretbox_BOXZEROBYTES = 16
const int crypto_scalarmult_BYTES = 32
const int crypto_scalarmult_SCALARBYTES = 32
const int crypto_box_PUBLICKEYBYTES = 32
const int crypto_box_SECRETKEYBYTES = 32
const int crypto_box_BEFORENMBYTES = 32
const int crypto_box_NONCEBYTES = crypto_secretbox_NONCEBYTES
const int crypto_box_ZEROBYTES = crypto_secretbox_ZEROBYTES
const int crypto_box_BOXZEROBYTES = crypto_secretbox_BOXZEROBYTES
const int crypto_sign_BYTES = 64
const int crypto_sign_PUBLICKEYBYTES = 32
const int crypto_sign_SECRETKEYBYTES = 64
const int crypto_sign_SEEDBYTES = 32
const int crypto_hash_BYTES = 64
Member Function Documentation
CryptoHash()
static void CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoHash (IList< byte > outArr, byte[] m, int n) inline static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen().
CryptoSign()
static int CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign (byte[] sm, byte[] m, int n, byte[] sk) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoHash(), CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.ModL(), CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.Reduce(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Sign().
CryptoSignKeypair()
static void CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair (long[] pk, byte[] sk, bool seeded) inline static private
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoHash(), CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Crypto.Crypto.RandomBytes(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed().
CryptoSignOpen()
static int CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen (byte[] m, byte[] sm, int n, byte[] pk) inline static
References CatSdk.Crypto.NaclCatapult.Add(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoHash(), CatSdk.Crypto.NaclCatapult.CryptoVerify32(), CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Crypto.NaclCatapult.Pack(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.Reduce(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase(), CatSdk.Crypto.NaclCatapult.Scalarmult(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Verify().
Detached()
static byte[] CatSdk.Nem.External.TweetnaclNaclFastKeccak.Detached (byte[] msg, byte[] secretKey) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_BYTES, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Sign().
Referenced by CatSdk.Nem.KeyPair.Sign().
FromSeed()
static Dictionary< string, byte[]> CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed (byte[] seed) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_PUBLICKEYBYTES, CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_SECRETKEYBYTES, CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_SEEDBYTES, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair().
Referenced by CatSdk.Nem.KeyPair.KeyPair().
ModL()
static void CatSdk.Nem.External.TweetnaclNaclFastKeccak.ModL (byte[] r, decimal[] x) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.L.
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Reduce().
Reduce()
static void CatSdk.Nem.External.TweetnaclNaclFastKeccak.Reduce (byte[] r) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.ModL().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen().
ScalarBase()
static void CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase (long p[][], byte[] s) inline static private
References CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.gf1, CatSdk.Crypto.NaclCatapult.M(), CatSdk.Crypto.NaclCatapult.Scalarmult(), CatSdk.Crypto.NaclCatapult.Set25519(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.X, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Y.
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignKeypair(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen().
Sign()
static byte[] CatSdk.Nem.External.TweetnaclNaclFastKeccak.Sign (byte[] msg, byte[] secretKey) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_BYTES, CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_SECRETKEYBYTES, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSign().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Detached().
Unpackneg()
static int CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg (long r[][], byte[] p) inline static
References CatSdk.Crypto.NaclCatapult.A(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.D, CatSdk.Crypto.NaclCatapult.Gf(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.gf0, CatSdk.Nem.External.TweetnaclNaclFastKeccak.gf1, CatSdk.Nem.External.TweetnaclNaclFastKeccak.I, CatSdk.Crypto.NaclCatapult.M(), CatSdk.Crypto.NaclCatapult.Neq25519(), CatSdk.Crypto.NaclCatapult.Par25519(), CatSdk.Crypto.NaclCatapult.Pow2523(), CatSdk.Crypto.NaclCatapult.S(), CatSdk.Crypto.NaclCatapult.Set25519(), CatSdk.Crypto.NaclCatapult.Unpack25519(), and CatSdk.Crypto.NaclCatapult.Z().
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen().
Verify()
static bool CatSdk.Nem.External.TweetnaclNaclFastKeccak.Verify (byte[] msg, byte[] sig, byte[] publicKey) inline static
References CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_BYTES, CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_PUBLICKEYBYTES, and CatSdk.Nem.External.TweetnaclNaclFastKeccak.CryptoSignOpen().
Referenced by CatSdk.Nem.Verifier.Verify().
Member Data Documentation
_121665
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak._121665 = NaclCatapult.Gf(new long[]{0xdb41, 1}) static private
crypto_box_BEFORENMBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_BEFORENMBYTES = 32 static private
crypto_box_BOXZEROBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_BOXZEROBYTES = crypto_secretbox_BOXZEROBYTES static private
crypto_box_NONCEBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_NONCEBYTES = crypto_secretbox_NONCEBYTES static private
crypto_box_PUBLICKEYBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_PUBLICKEYBYTES = 32 static private
crypto_box_SECRETKEYBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_SECRETKEYBYTES = 32 static private
crypto_box_ZEROBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_box_ZEROBYTES = crypto_secretbox_ZEROBYTES static private
crypto_hash_BYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_hash_BYTES = 64 static private
crypto_scalarmult_BYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_scalarmult_BYTES = 32 static private
crypto_scalarmult_SCALARBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_scalarmult_SCALARBYTES = 32 static private
crypto_secretbox_BOXZEROBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_secretbox_BOXZEROBYTES = 16 static private
crypto_secretbox_KEYBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_secretbox_KEYBYTES = 32 static private
crypto_secretbox_NONCEBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_secretbox_NONCEBYTES = 24 static private
crypto_secretbox_ZEROBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_secretbox_ZEROBYTES = 32 static private
crypto_sign_BYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_BYTES = 64 static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Detached(), CatSdk.Nem.External.TweetnaclNaclFastKeccak.Sign(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Verify().
crypto_sign_PUBLICKEYBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_PUBLICKEYBYTES = 32 static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Verify().
crypto_sign_SECRETKEYBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_SECRETKEYBYTES = 64 static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Sign().
crypto_sign_SEEDBYTES
const int CatSdk.Nem.External.TweetnaclNaclFastKeccak.crypto_sign_SEEDBYTES = 32 static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.FromSeed().
D
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.D = NaclCatapult.Gf(new long[]{0x78a3, 0x1359, 0x4dca, 0x75eb, 0xd8ab, 0x4141, 0x0a4d, 0x0070, 0xe898, 0x7779, 0x4079, 0x8cc7, 0xfe73, 0x2b6f, 0x6cee, 0x5203}) static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
D2
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.D2 = NaclCatapult.Gf(new long[]{0xf159, 0x26b2, 0x9b94, 0xebd6, 0xb156, 0x8283, 0x149a, 0x00e0, 0xd130, 0xeef3, 0x80f2, 0x198e, 0xfce7, 0x56df, 0xd9dc, 0x2406}) static private
gf0
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.gf0 = NaclCatapult.Gf() static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
gf1
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.gf1 = NaclCatapult.Gf(new long[]{1}) static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase(), and CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
I
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.I = NaclCatapult.Gf(new long[]{0xa0b0, 0x4a0e, 0x1b27, 0xc4ee, 0xe478, 0xad2f, 0x1806, 0x2f43, 0xd7a7, 0x3dfb, 0x0099, 0x2b4d, 0xdf0b, 0x4fc1, 0x2480, 0x2b83}) static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.Unpackneg().
L
decimal [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.L static private
Initial value:
= {
            0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10
        }
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.ModL().
X
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.X = NaclCatapult.Gf(new long[]{0xd51a, 0x8f25, 0x2d60, 0xc956, 0xa7b2, 0x9525, 0xc760, 0x692c, 0xdc5c, 0xfdd6, 0xe231, 0xc0a4, 0x53fe, 0xcd6e, 0x36d3, 0x2169}) static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase().
Y
long [] CatSdk.Nem.External.TweetnaclNaclFastKeccak.Y = NaclCatapult.Gf(new long[]{0x6658, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666, 0x6666}) static private
Referenced by CatSdk.Nem.External.TweetnaclNaclFastKeccak.ScalarBase().
The documentation for this class was generated from the following file:
TweetnaclNaclFastKeccak.cs