SymbolCsharpDualSDK: CatSdk.Nem.MessageType Class Reference
CatSdk.Nem.MessageType Class Reference
Public Member Functions
MessageType (uint value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static MessageType Deserialize (BinaryReader br)
Static Public Attributes
static readonly MessageType PLAIN = new MessageType(1)
static readonly MessageType ENCRYPTED = new MessageType(2)
Properties
uint Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< uint >
T Value [get]
Constructor & Destructor Documentation
MessageType()
CatSdk.Nem.MessageType.MessageType (uint value = 0) inline
References CatSdk.Nem.MessageType.Value.
Member Function Documentation
Deserialize()
static MessageType CatSdk.Nem.MessageType.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Message.Deserialize().
Serialize()
byte[] CatSdk.Nem.MessageType.Serialize () inline
References CatSdk.Nem.MessageType.Value.
Referenced by CatSdk.Nem.Message.Serialize().
ToString()
override string CatSdk.Nem.MessageType.ToString () inline
Member Data Documentation
ENCRYPTED
readonly MessageType CatSdk.Nem.MessageType.ENCRYPTED = new MessageType(2) static
PLAIN
readonly MessageType CatSdk.Nem.MessageType.PLAIN = new MessageType(1) static
Referenced by CatSdk.Nem.Message.Message().
Property Documentation
Size
uint CatSdk.Nem.MessageType.Size get
Value
uint CatSdk.Nem.MessageType.Value get
Referenced by CatSdk.Nem.MessageType.MessageType(), and CatSdk.Nem.MessageType.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs