SymbolCsharpDualSDK: CatSdk.Symbol.NodeKeyLinkTransaction Class Reference
CatSdk.Symbol.NodeKeyLinkTransaction Class Reference
Public Member Functions
NodeKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static NodeKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.NODE_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
PublicKey LinkedPublicKey [get, set]
LinkAction LinkAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
NodeKeyLinkTransaction()
CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction () inline
References CatSdk.Symbol.NodeKeyLinkTransaction.Deadline, CatSdk.Symbol.NodeKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.NodeKeyLinkTransaction.Fee, CatSdk.Symbol.NodeKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.NodeKeyLinkTransaction.Network, CatSdk.Symbol.NodeKeyLinkTransaction.Signature, CatSdk.Symbol.NodeKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.NodeKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.NodeKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Symbol.NodeKeyLinkTransaction.Type, CatSdk.Symbol.LinkAction.UNLINK, CatSdk.Symbol.NodeKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.NodeKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static NodeKeyLinkTransaction CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.NodeKeyLinkTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.LinkAction.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Fee, CatSdk.Symbol.NodeKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NodeKeyLinkTransaction.Network, CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), CatSdk.Symbol.NodeKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.NodeKeyLinkTransaction.Type, and CatSdk.Symbol.NodeKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.NodeKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.NodeKeyLinkTransaction.Deadline, CatSdk.Symbol.NodeKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.NodeKeyLinkTransaction.Fee, CatSdk.Symbol.NodeKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NodeKeyLinkTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.LinkAction.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.NodeKeyLinkTransaction.Size, CatSdk.Symbol.NodeKeyLinkTransaction.Type, CatSdk.Symbol.NodeKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.NodeKeyLinkTransaction.Version.
ToString()
override string CatSdk.Symbol.NodeKeyLinkTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.NodeKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.NodeKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.NODE_KEY_LINK static
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.NodeKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.NodeKeyLinkTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.NodeKeyLinkTransaction.Deadline get set
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Fee
Amount CatSdk.Symbol.NodeKeyLinkTransaction.Fee get set
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
LinkAction
LinkAction CatSdk.Symbol.NodeKeyLinkTransaction.LinkAction get set
LinkedPublicKey
PublicKey CatSdk.Symbol.NodeKeyLinkTransaction.LinkedPublicKey get set
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.NodeKeyLinkTransaction.Network get set
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Signature
Signature CatSdk.Symbol.NodeKeyLinkTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.NodeKeyLinkTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Size
uint CatSdk.Symbol.NodeKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.NodeKeyLinkTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.NodeKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"LinkedPublicKey", "pod:PublicKey"},
        {"LinkAction", "enum:LinkAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.NodeKeyLinkTransaction.Version get set
Referenced by CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.NodeKeyLinkTransaction(), and CatSdk.Symbol.NodeKeyLinkTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs