SymbolCsharpDualSDK: CatSdk.Symbol.AccountKeyLinkTransaction Class Reference
CatSdk.Symbol.AccountKeyLinkTransaction Class Reference
Public Member Functions
AccountKeyLinkTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static AccountKeyLinkTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.ACCOUNT_KEY_LINK
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
PublicKey LinkedPublicKey [get, set]
LinkAction LinkAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
AccountKeyLinkTransaction()
CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction () inline
References CatSdk.Symbol.AccountKeyLinkTransaction.Deadline, CatSdk.Symbol.AccountKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.AccountKeyLinkTransaction.Fee, CatSdk.Symbol.AccountKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.AccountKeyLinkTransaction.Network, CatSdk.Symbol.AccountKeyLinkTransaction.Signature, CatSdk.Symbol.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.AccountKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AccountKeyLinkTransaction.TRANSACTION_VERSION, CatSdk.Symbol.AccountKeyLinkTransaction.Type, CatSdk.Symbol.LinkAction.UNLINK, CatSdk.Symbol.AccountKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AccountKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize().
Member Function Documentation
Deserialize()
static AccountKeyLinkTransaction CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.LinkAction.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Fee, CatSdk.Symbol.AccountKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.AccountKeyLinkTransaction.Network, CatSdk.Symbol.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.AccountKeyLinkTransaction.Type, and CatSdk.Symbol.AccountKeyLinkTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.AccountKeyLinkTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.AccountKeyLinkTransaction.Deadline, CatSdk.Symbol.AccountKeyLinkTransaction.EntityBodyReserved_1, CatSdk.Symbol.AccountKeyLinkTransaction.Fee, CatSdk.Symbol.AccountKeyLinkTransaction.LinkedPublicKey, CatSdk.Symbol.AccountKeyLinkTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.LinkAction.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.SignerPublicKey, CatSdk.Symbol.AccountKeyLinkTransaction.Size, CatSdk.Symbol.AccountKeyLinkTransaction.Type, CatSdk.Symbol.AccountKeyLinkTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AccountKeyLinkTransaction.Version.
ToString()
override string CatSdk.Symbol.AccountKeyLinkTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.AccountKeyLinkTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.AccountKeyLinkTransaction.TRANSACTION_TYPE = TransactionType.ACCOUNT_KEY_LINK static
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Symbol.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Symbol.AccountKeyLinkTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.AccountKeyLinkTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.AccountKeyLinkTransaction.Deadline get set
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Fee
Amount CatSdk.Symbol.AccountKeyLinkTransaction.Fee get set
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
LinkAction
LinkAction CatSdk.Symbol.AccountKeyLinkTransaction.LinkAction get set
LinkedPublicKey
PublicKey CatSdk.Symbol.AccountKeyLinkTransaction.LinkedPublicKey get set
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.AccountKeyLinkTransaction.Network get set
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Signature
Signature CatSdk.Symbol.AccountKeyLinkTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.AccountKeyLinkTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Size
uint CatSdk.Symbol.AccountKeyLinkTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.AccountKeyLinkTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.AccountKeyLinkTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"LinkedPublicKey", "pod:PublicKey"},
        {"LinkAction", "enum:LinkAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.AccountKeyLinkTransaction.Version get set
Referenced by CatSdk.Symbol.AccountKeyLinkTransaction.AccountKeyLinkTransaction(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.AccountKeyLinkTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs