SymbolCsharpDualSDK: CatSdk.Symbol.MosaicNonce Class Reference
CatSdk.Symbol.MosaicNonce Class Reference
Public Member Functions
MosaicNonce (uint mosaicNonce=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicNonce Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 4
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
MosaicNonce()
CatSdk.Symbol.MosaicNonce.MosaicNonce (uint mosaicNonce = 0) inline
Member Function Documentation
Deserialize()
static MosaicNonce CatSdk.Symbol.MosaicNonce.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicNonce.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.MosaicNonce.SIZE = 4 static
The documentation for this class was generated from the following file:
Symbol/Models.cs