SymbolCsharpDualSDK: CatSdk.Nem.NamespaceId Class Reference
CatSdk.Nem.NamespaceId Class Reference
Public Member Functions
NamespaceId ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static NamespaceId Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
byte[] Name [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
NamespaceId()
CatSdk.Nem.NamespaceId.NamespaceId () inline
References CatSdk.Nem.NamespaceId.Name.
Referenced by CatSdk.Nem.NamespaceId.Deserialize().
Member Function Documentation
Deserialize()
static NamespaceId CatSdk.Nem.NamespaceId.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.NamespaceId.Name, and CatSdk.Nem.NamespaceId.NamespaceId().
Referenced by CatSdk.Nem.MosaicId.Deserialize().
Serialize()
byte[] CatSdk.Nem.NamespaceId.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.NamespaceId.Name.
Referenced by CatSdk.Nem.MosaicId.Serialize().
ToString()
override string CatSdk.Nem.NamespaceId.ToString () inline
Property Documentation
Name
byte [] CatSdk.Nem.NamespaceId.Name get set
Referenced by CatSdk.Nem.NamespaceId.Deserialize(), CatSdk.Nem.NamespaceId.NamespaceId(), and CatSdk.Nem.NamespaceId.Serialize().
Size
uint CatSdk.Nem.NamespaceId.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.NamespaceId.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Name", "bytes_array"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs