SymbolCsharpDualSDK: CatSdk.Symbol.AddressAliasTransaction Class Reference
CatSdk.Symbol.AddressAliasTransaction Class Reference
Public Member Functions
AddressAliasTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static AddressAliasTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.ADDRESS_ALIAS
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
NamespaceId NamespaceId [get, set]
Address Address [get, set]
AliasAction AliasAction [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
AddressAliasTransaction()
CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction () inline
References CatSdk.Symbol.AddressAliasTransaction.Address, CatSdk.Symbol.AddressAliasTransaction.Deadline, CatSdk.Symbol.AddressAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.AddressAliasTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.AddressAliasTransaction.NamespaceId, CatSdk.Symbol.AddressAliasTransaction.Network, CatSdk.Symbol.AddressAliasTransaction.Signature, CatSdk.Symbol.AddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.AddressAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AddressAliasTransaction.TRANSACTION_VERSION, CatSdk.Symbol.AddressAliasTransaction.Type, CatSdk.Symbol.AliasAction.UNLINK, CatSdk.Symbol.AddressAliasTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AddressAliasTransaction.Version.
Referenced by CatSdk.Symbol.AddressAliasTransaction.Deserialize().
Member Function Documentation
Deserialize()
static AddressAliasTransaction CatSdk.Symbol.AddressAliasTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.Address.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.NamespaceId.Deserialize(), CatSdk.Symbol.AliasAction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Fee, CatSdk.Symbol.AddressAliasTransaction.Network, CatSdk.Symbol.AddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.AddressAliasTransaction.Type, and CatSdk.Symbol.AddressAliasTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.AddressAliasTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.AddressAliasTransaction.Deadline, CatSdk.Symbol.AddressAliasTransaction.EntityBodyReserved_1, CatSdk.Symbol.AddressAliasTransaction.Fee, CatSdk.Symbol.AddressAliasTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.Address.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.NamespaceId.Serialize(), CatSdk.Symbol.AliasAction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.SignerPublicKey, CatSdk.Symbol.AddressAliasTransaction.Size, CatSdk.Symbol.AddressAliasTransaction.Type, CatSdk.Symbol.AddressAliasTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AddressAliasTransaction.Version.
ToString()
override string CatSdk.Symbol.AddressAliasTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.AddressAliasTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.AddressAliasTransaction.TRANSACTION_TYPE = TransactionType.ADDRESS_ALIAS static
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), and CatSdk.Symbol.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Symbol.AddressAliasTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.AddressAliasTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
Property Documentation
Address
Address CatSdk.Symbol.AddressAliasTransaction.Address get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction().
AliasAction
AliasAction CatSdk.Symbol.AddressAliasTransaction.AliasAction get set
Deadline
Timestamp CatSdk.Symbol.AddressAliasTransaction.Deadline get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
Fee
Amount CatSdk.Symbol.AddressAliasTransaction.Fee get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
NamespaceId
NamespaceId CatSdk.Symbol.AddressAliasTransaction.NamespaceId get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction().
Network
NetworkType CatSdk.Symbol.AddressAliasTransaction.Network get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
Signature
Signature CatSdk.Symbol.AddressAliasTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.AddressAliasTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
Size
uint CatSdk.Symbol.AddressAliasTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.AddressAliasTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.AddressAliasTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.AddressAliasTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"NamespaceId", "pod:NamespaceId"},
        {"Address", "pod:Address"},
        {"AliasAction", "enum:AliasAction"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.AddressAliasTransaction.Version get set
Referenced by CatSdk.Symbol.AddressAliasTransaction.AddressAliasTransaction(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), and CatSdk.Symbol.AddressAliasTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs