SymbolCsharpDualSDK: CatSdk.Symbol.AggregateBondedTransaction Class Reference
CatSdk.Symbol.AggregateBondedTransaction Class Reference
Public Member Functions
AggregateBondedTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static AggregateBondedTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.AGGREGATE_BONDED
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
Hash256 TransactionsHash [get, set]
IBaseTransaction[] Transactions [get, set]
Cosignature[] Cosignatures [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
readonly int AggregateTransactionHeaderReserved_1
Constructor & Destructor Documentation
AggregateBondedTransaction()
CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction () inline
References CatSdk.Symbol.AggregateBondedTransaction.AggregateTransactionHeaderReserved_1, CatSdk.Symbol.AggregateBondedTransaction.Cosignatures, CatSdk.Symbol.AggregateBondedTransaction.Deadline, CatSdk.Symbol.AggregateBondedTransaction.EntityBodyReserved_1, CatSdk.Symbol.AggregateBondedTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.AggregateBondedTransaction.Network, CatSdk.Symbol.AggregateBondedTransaction.Signature, CatSdk.Symbol.AggregateBondedTransaction.SignerPublicKey, CatSdk.Symbol.AggregateBondedTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AggregateBondedTransaction.TRANSACTION_VERSION, CatSdk.Symbol.AggregateBondedTransaction.Transactions, CatSdk.Symbol.AggregateBondedTransaction.TransactionsHash, CatSdk.Symbol.AggregateBondedTransaction.Type, CatSdk.Symbol.AggregateBondedTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AggregateBondedTransaction.Version.
Referenced by CatSdk.Symbol.AggregateBondedTransaction.Deserialize().
Member Function Documentation
Deserialize()
static AggregateBondedTransaction CatSdk.Symbol.AggregateBondedTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Cosignatures, CatSdk.Symbol.AggregateBondedTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.Cosignature.Deserialize(), CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Fee, CatSdk.Symbol.AggregateBondedTransaction.Network, CatSdk.Symbol.AggregateBondedTransaction.SignerPublicKey, CatSdk.Symbol.AggregateBondedTransaction.Transactions, CatSdk.Symbol.AggregateBondedTransaction.TransactionsHash, CatSdk.Symbol.AggregateBondedTransaction.Type, and CatSdk.Symbol.AggregateBondedTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.AggregateBondedTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.AggregateBondedTransaction.AggregateTransactionHeaderReserved_1, CatSdk.Symbol.AggregateBondedTransaction.Cosignatures, CatSdk.Symbol.AggregateBondedTransaction.Deadline, CatSdk.Symbol.AggregateBondedTransaction.EntityBodyReserved_1, CatSdk.Symbol.AggregateBondedTransaction.Fee, CatSdk.Symbol.AggregateBondedTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.SignerPublicKey, CatSdk.Symbol.AggregateBondedTransaction.Size, CatSdk.Symbol.AggregateBondedTransaction.Transactions, CatSdk.Symbol.AggregateBondedTransaction.TransactionsHash, CatSdk.Symbol.AggregateBondedTransaction.Type, CatSdk.Symbol.AggregateBondedTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AggregateBondedTransaction.Version.
ToString()
override string CatSdk.Symbol.AggregateBondedTransaction.ToString () inline
Member Data Documentation
AggregateTransactionHeaderReserved_1
readonly int CatSdk.Symbol.AggregateBondedTransaction.AggregateTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.AggregateBondedTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.AggregateBondedTransaction.TRANSACTION_TYPE = TransactionType.AGGREGATE_BONDED static
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), and CatSdk.Symbol.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Symbol.AggregateBondedTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.AggregateBondedTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Property Documentation
Cosignatures
Cosignature [] CatSdk.Symbol.AggregateBondedTransaction.Cosignatures get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Deadline
Timestamp CatSdk.Symbol.AggregateBondedTransaction.Deadline get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Fee
Amount CatSdk.Symbol.AggregateBondedTransaction.Fee get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.AggregateBondedTransaction.Network get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Signature
Signature CatSdk.Symbol.AggregateBondedTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.AggregateBondedTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Size
uint CatSdk.Symbol.AggregateBondedTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Transactions
IBaseTransaction [] CatSdk.Symbol.AggregateBondedTransaction.Transactions get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
TransactionsHash
Hash256 CatSdk.Symbol.AggregateBondedTransaction.TransactionsHash get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.AggregateBondedTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.AggregateBondedTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"TransactionsHash", "pod:Hash256"},
        {"Transactions", "array[EmbeddedTransaction]"},
        {"Cosignatures", "array[Cosignature]"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.AggregateBondedTransaction.Version get set
Referenced by CatSdk.Symbol.AggregateBondedTransaction.AggregateBondedTransaction(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), and CatSdk.Symbol.AggregateBondedTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs