SymbolCsharpDualSDK: CatSdk.Symbol.AggregateCompleteTransaction Class Reference
CatSdk.Symbol.AggregateCompleteTransaction Class Reference
Public Member Functions
AggregateCompleteTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static AggregateCompleteTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.AGGREGATE_COMPLETE
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
Hash256 TransactionsHash [get, set]
IBaseTransaction[] Transactions [get, set]
Cosignature[] Cosignatures [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
readonly int AggregateTransactionHeaderReserved_1
Constructor & Destructor Documentation
AggregateCompleteTransaction()
CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction () inline
References CatSdk.Symbol.AggregateCompleteTransaction.AggregateTransactionHeaderReserved_1, CatSdk.Symbol.AggregateCompleteTransaction.Cosignatures, CatSdk.Symbol.AggregateCompleteTransaction.Deadline, CatSdk.Symbol.AggregateCompleteTransaction.EntityBodyReserved_1, CatSdk.Symbol.AggregateCompleteTransaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.AggregateCompleteTransaction.Network, CatSdk.Symbol.AggregateCompleteTransaction.Signature, CatSdk.Symbol.AggregateCompleteTransaction.SignerPublicKey, CatSdk.Symbol.AggregateCompleteTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AggregateCompleteTransaction.TRANSACTION_VERSION, CatSdk.Symbol.AggregateCompleteTransaction.Transactions, CatSdk.Symbol.AggregateCompleteTransaction.TransactionsHash, CatSdk.Symbol.AggregateCompleteTransaction.Type, CatSdk.Symbol.AggregateCompleteTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AggregateCompleteTransaction.Version.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.Deserialize().
Member Function Documentation
Deserialize()
static AggregateCompleteTransaction CatSdk.Symbol.AggregateCompleteTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Cosignatures, CatSdk.Symbol.AggregateCompleteTransaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.Cosignature.Deserialize(), CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Fee, CatSdk.Symbol.AggregateCompleteTransaction.Network, CatSdk.Symbol.AggregateCompleteTransaction.SignerPublicKey, CatSdk.Symbol.AggregateCompleteTransaction.Transactions, CatSdk.Symbol.AggregateCompleteTransaction.TransactionsHash, CatSdk.Symbol.AggregateCompleteTransaction.Type, and CatSdk.Symbol.AggregateCompleteTransaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.AggregateCompleteTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.AggregateCompleteTransaction.AggregateTransactionHeaderReserved_1, CatSdk.Symbol.AggregateCompleteTransaction.Cosignatures, CatSdk.Symbol.AggregateCompleteTransaction.Deadline, CatSdk.Symbol.AggregateCompleteTransaction.EntityBodyReserved_1, CatSdk.Symbol.AggregateCompleteTransaction.Fee, CatSdk.Symbol.AggregateCompleteTransaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.SignerPublicKey, CatSdk.Symbol.AggregateCompleteTransaction.Size, CatSdk.Symbol.AggregateCompleteTransaction.Transactions, CatSdk.Symbol.AggregateCompleteTransaction.TransactionsHash, CatSdk.Symbol.AggregateCompleteTransaction.Type, CatSdk.Symbol.AggregateCompleteTransaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.AggregateCompleteTransaction.Version.
ToString()
override string CatSdk.Symbol.AggregateCompleteTransaction.ToString () inline
Member Data Documentation
AggregateTransactionHeaderReserved_1
readonly int CatSdk.Symbol.AggregateCompleteTransaction.AggregateTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.AggregateCompleteTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.AggregateCompleteTransaction.TRANSACTION_TYPE = TransactionType.AGGREGATE_COMPLETE static
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), and CatSdk.Symbol.TransactionFactory.Deserialize().
TRANSACTION_VERSION
const byte CatSdk.Symbol.AggregateCompleteTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.AggregateCompleteTransaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Property Documentation
Cosignatures
Cosignature [] CatSdk.Symbol.AggregateCompleteTransaction.Cosignatures get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Deadline
Timestamp CatSdk.Symbol.AggregateCompleteTransaction.Deadline get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Fee
Amount CatSdk.Symbol.AggregateCompleteTransaction.Fee get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Network
NetworkType CatSdk.Symbol.AggregateCompleteTransaction.Network get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Signature
Signature CatSdk.Symbol.AggregateCompleteTransaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction().
SignerPublicKey
PublicKey CatSdk.Symbol.AggregateCompleteTransaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Size
uint CatSdk.Symbol.AggregateCompleteTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Transactions
IBaseTransaction [] CatSdk.Symbol.AggregateCompleteTransaction.Transactions get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
TransactionsHash
Hash256 CatSdk.Symbol.AggregateCompleteTransaction.TransactionsHash get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.AggregateCompleteTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.AggregateCompleteTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"TransactionsHash", "pod:Hash256"},
        {"Transactions", "array[EmbeddedTransaction]"},
        {"Cosignatures", "array[Cosignature]"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.AggregateCompleteTransaction.Version get set
Referenced by CatSdk.Symbol.AggregateCompleteTransaction.AggregateCompleteTransaction(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), and CatSdk.Symbol.AggregateCompleteTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs