SymbolCsharpDualSDK: CatSdk.Symbol.Hash256 Class Reference
CatSdk.Symbol.Hash256 Class Reference
Public Member Functions
Hash256 (byte[]? hash256=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Hash256 Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 32
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Hash256()
CatSdk.Symbol.Hash256.Hash256 (byte?[] hash256 = null) inline
Member Function Documentation
Deserialize()
static Hash256 CatSdk.Symbol.Hash256.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.Hash256.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Symbol.DetachedCosignature.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), and CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.Hash256.SIZE = 32 static
The documentation for this class was generated from the following file:
Symbol/Models.cs