SymbolCsharpDualSDK: CatSdk.Symbol.NamespaceId Class Reference
CatSdk.Symbol.NamespaceId Class Reference
Public Member Functions
NamespaceId (ulong namespaceId=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static NamespaceId Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 8
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
NamespaceId()
CatSdk.Symbol.NamespaceId.NamespaceId (ulong namespaceId = 0) inline
Member Function Documentation
Deserialize()
static NamespaceId CatSdk.Symbol.NamespaceId.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.NamespaceId.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), and CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.NamespaceId.SIZE = 8 static
The documentation for this class was generated from the following file:
Symbol/Models.cs