SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedHashLockTransaction Class Reference
CatSdk.Symbol.EmbeddedHashLockTransaction Class Reference
Public Member Functions
EmbeddedHashLockTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedHashLockTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.HASH_LOCK
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
UnresolvedMosaic Mosaic [get, set]
BlockDuration Duration [get, set]
Hash256 Hash [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedHashLockTransaction()
CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction () inline
References CatSdk.Symbol.EmbeddedHashLockTransaction.Duration, CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedHashLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedHashLockTransaction.Hash, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedHashLockTransaction.Network, CatSdk.Symbol.EmbeddedHashLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedHashLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedHashLockTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedHashLockTransaction.Type, and CatSdk.Symbol.EmbeddedHashLockTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedHashLockTransaction CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.BlockDuration.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Duration, CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), CatSdk.Symbol.EmbeddedHashLockTransaction.Hash, CatSdk.Symbol.EmbeddedHashLockTransaction.Network, CatSdk.Symbol.EmbeddedHashLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedHashLockTransaction.Type, and CatSdk.Symbol.EmbeddedHashLockTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedHashLockTransaction.Duration, CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedHashLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedHashLockTransaction.Hash, CatSdk.Symbol.EmbeddedHashLockTransaction.Network, CatSdk.Symbol.BlockDuration.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedHashLockTransaction.Size, CatSdk.Symbol.EmbeddedHashLockTransaction.Type, and CatSdk.Symbol.EmbeddedHashLockTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedHashLockTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedHashLockTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedHashLockTransaction.TRANSACTION_TYPE = TransactionType.HASH_LOCK static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedHashLockTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction().
Property Documentation
Duration
BlockDuration CatSdk.Symbol.EmbeddedHashLockTransaction.Duration get set
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
Hash
Hash256 CatSdk.Symbol.EmbeddedHashLockTransaction.Hash get set
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
Mosaic
UnresolvedMosaic CatSdk.Symbol.EmbeddedHashLockTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.EmbeddedHashLockTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedHashLockTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedHashLockTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedHashLockTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedHashLockTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Mosaic", "struct:UnresolvedMosaic"},
        {"Duration", "pod:BlockDuration"},
        {"Hash", "pod:Hash256"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedHashLockTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.EmbeddedHashLockTransaction(), and CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs