SymbolCsharpDualSDK: CatSdk.Symbol.PublicKey Class Reference
CatSdk.Symbol.PublicKey Class Reference
Public Member Functions
PublicKey (byte[]? publicKey=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static PublicKey Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 32
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
PublicKey()
CatSdk.Symbol.PublicKey.PublicKey (byte?[] publicKey = null) inline
Member Function Documentation
Deserialize()
static PublicKey CatSdk.Symbol.PublicKey.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.EmbeddedTransaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.Cosignature.Deserialize(), CatSdk.Symbol.DetachedCosignature.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.PublicKey.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Symbol.Transaction.Serialize(), CatSdk.Symbol.EmbeddedTransaction.Serialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction.Serialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction.Serialize(), CatSdk.Symbol.Cosignature.Serialize(), CatSdk.Symbol.DetachedCosignature.Serialize(), CatSdk.Symbol.AggregateCompleteTransaction.Serialize(), CatSdk.Symbol.AggregateBondedTransaction.Serialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction.Serialize(), CatSdk.Symbol.HashLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Serialize(), CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Serialize(), CatSdk.Symbol.AddressAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedAddressAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction.Serialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction.Serialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize(), CatSdk.Symbol.TransferTransaction.Serialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.PublicKey.SIZE = 32 static
The documentation for this class was generated from the following file:
Symbol/Models.cs