SymbolCsharpDualSDK: CatSdk.Nem.Timestamp Class Reference
CatSdk.Nem.Timestamp Class Reference
Public Member Functions
Timestamp (uint timestamp=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Timestamp Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 4
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Timestamp()
CatSdk.Nem.Timestamp.Timestamp (uint timestamp = 0) inline
Member Function Documentation
Deserialize()
static Timestamp CatSdk.Nem.Timestamp.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.AccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Deserialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.Timestamp.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Nem.Transaction.Serialize(), CatSdk.Nem.NonVerifiableTransaction.Serialize(), CatSdk.Nem.AccountKeyLinkTransaction.Serialize(), CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize(), CatSdk.Nem.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize(), CatSdk.Nem.MultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1.Serialize(), CatSdk.Nem.MultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Nem.Timestamp.SIZE = 4 static
The documentation for this class was generated from the following file:
Nem/Models.cs