SymbolCsharpDualSDK: CatSdk.Nem.SizePrefixedMosaicProperty Class Reference
CatSdk.Nem.SizePrefixedMosaicProperty Class Reference
Public Member Functions
SizePrefixedMosaicProperty ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static SizePrefixedMosaicProperty Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
MosaicProperty Property [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
SizePrefixedMosaicProperty()
CatSdk.Nem.SizePrefixedMosaicProperty.SizePrefixedMosaicProperty () inline
References CatSdk.Nem.SizePrefixedMosaicProperty.Property.
Referenced by CatSdk.Nem.SizePrefixedMosaicProperty.Deserialize().
Member Function Documentation
Deserialize()
static SizePrefixedMosaicProperty CatSdk.Nem.SizePrefixedMosaicProperty.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MosaicProperty.Deserialize(), CatSdk.Nem.SizePrefixedMosaicProperty.Property, and CatSdk.Nem.SizePrefixedMosaicProperty.SizePrefixedMosaicProperty().
Referenced by CatSdk.Nem.MosaicDefinition.Deserialize().
Serialize()
byte[] CatSdk.Nem.SizePrefixedMosaicProperty.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.SizePrefixedMosaicProperty.Property, CatSdk.Nem.MosaicProperty.Serialize(), and CatSdk.Nem.MosaicProperty.Size.
ToString()
override string CatSdk.Nem.SizePrefixedMosaicProperty.ToString () inline
Property Documentation
Property
MosaicProperty CatSdk.Nem.SizePrefixedMosaicProperty.Property get set
Referenced by CatSdk.Nem.SizePrefixedMosaicProperty.Deserialize(), CatSdk.Nem.SizePrefixedMosaicProperty.Serialize(), and CatSdk.Nem.SizePrefixedMosaicProperty.SizePrefixedMosaicProperty().
Size
uint CatSdk.Nem.SizePrefixedMosaicProperty.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Nem.SizePrefixedMosaicProperty.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Property", "struct:MosaicProperty"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Nem/Models.cs