SymbolCsharpDualSDK: CatSdk.Symbol.UnresolvedAddress Class Reference
CatSdk.Symbol.UnresolvedAddress Class Reference
Public Member Functions
UnresolvedAddress (byte[]? unresolvedAddress=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static UnresolvedAddress Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 24
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
UnresolvedAddress()
CatSdk.Symbol.UnresolvedAddress.UnresolvedAddress (byte?[] unresolvedAddress = null) inline
Member Function Documentation
Deserialize()
static UnresolvedAddress CatSdk.Symbol.UnresolvedAddress.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.UnresolvedAddress.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize(), CatSdk.Symbol.AccountMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedAccountMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicMetadataTransaction.Serialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.TransferTransaction.Serialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.UnresolvedAddress.SIZE = 24 static
The documentation for this class was generated from the following file:
Symbol/Models.cs