SymbolCsharpDualSDK: CatSdk.Symbol.Transaction Class Reference
CatSdk.Symbol.Transaction Class Reference
Public Member Functions
Transaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Transaction Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get, set]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int VerifiableEntityHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
Transaction()
CatSdk.Symbol.Transaction.Transaction () inline
References CatSdk.Symbol.TransactionType.ACCOUNT_KEY_LINK, CatSdk.Symbol.Transaction.Deadline, CatSdk.Symbol.Transaction.EntityBodyReserved_1, CatSdk.Symbol.Transaction.Fee, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.Transaction.Network, CatSdk.Symbol.Transaction.Signature, CatSdk.Symbol.Transaction.SignerPublicKey, CatSdk.Symbol.Transaction.Type, CatSdk.Symbol.Transaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.Transaction.Version.
Referenced by CatSdk.Symbol.Transaction.Deserialize().
Member Function Documentation
Deserialize()
static Transaction CatSdk.Symbol.Transaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Transaction.Deadline, CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.Timestamp.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.Signature.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.Transaction.Fee, CatSdk.Symbol.Transaction.Network, CatSdk.Symbol.Transaction.SignerPublicKey, CatSdk.Symbol.Transaction.Transaction(), CatSdk.Symbol.Transaction.Type, and CatSdk.Symbol.Transaction.Version.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.Transaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.Transaction.Deadline, CatSdk.Symbol.Transaction.EntityBodyReserved_1, CatSdk.Symbol.Transaction.Fee, CatSdk.Symbol.Transaction.Network, CatSdk.Symbol.Amount.Serialize(), CatSdk.Symbol.Timestamp.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Signature.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.Transaction.SignerPublicKey, CatSdk.Symbol.Transaction.Size, CatSdk.Symbol.Transaction.Type, CatSdk.Symbol.Transaction.VerifiableEntityHeaderReserved_1, and CatSdk.Symbol.Transaction.Version.
ToString()
override string CatSdk.Symbol.Transaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Symbol.Transaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
VerifiableEntityHeaderReserved_1
readonly int CatSdk.Symbol.Transaction.VerifiableEntityHeaderReserved_1 private
Referenced by CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
Property Documentation
Deadline
Timestamp CatSdk.Symbol.Transaction.Deadline get set
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
Fee
Amount CatSdk.Symbol.Transaction.Fee get set
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
Network
NetworkType CatSdk.Symbol.Transaction.Network get set
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
Signature
Signature CatSdk.Symbol.Transaction.Signature get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.Transaction.Transaction().
SignerPublicKey
PublicKey CatSdk.Symbol.Transaction.SignerPublicKey get set
Implements CatSdk.Symbol.ITransaction.
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
Size
uint CatSdk.Symbol.Transaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.Transaction.Serialize().
Type
TransactionType CatSdk.Symbol.Transaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
TypeHints
Dictionary<string, string> CatSdk.Symbol.Transaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Signature", "pod:Signature"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.Transaction.Version get set
Referenced by CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.Transaction.Serialize(), and CatSdk.Symbol.Transaction.Transaction().
The documentation for this class was generated from the following file:
Symbol/Models.cs