SymbolCsharpDualSDK: CatSdk.Crypto.Hkdf Class Reference
CatSdk.Crypto.Hkdf Class Reference
Public Member Functions
Hkdf ()
byte[] DeriveKey (byte[] salt, byte[] inputKeyMaterial, byte[] info, int outputLength)
Private Member Functions
byte[] Extract (byte[] salt, byte[] inputKeyMaterial)
byte[] Expand (byte[] prk, byte[] info, int outputLength)
Private Attributes
readonly Func< byte[], byte[], byte[]> keyedHash
Constructor & Destructor Documentation
Hkdf()
CatSdk.Crypto.Hkdf.Hkdf () inline
References CatSdk.Crypto.Hkdf.keyedHash.
Member Function Documentation
DeriveKey()
byte[] CatSdk.Crypto.Hkdf.DeriveKey (byte[] salt, byte[] inputKeyMaterial, byte[] info, int outputLength) inline
References CatSdk.Crypto.Hkdf.Expand(), and CatSdk.Crypto.Hkdf.Extract().
Expand()
byte[] CatSdk.Crypto.Hkdf.Expand (byte[] prk, byte[] info, int outputLength) inline private
References CatSdk.Crypto.Hkdf.keyedHash.
Referenced by CatSdk.Crypto.Hkdf.DeriveKey().
Extract()
byte[] CatSdk.Crypto.Hkdf.Extract (byte[] salt, byte[] inputKeyMaterial) inline private
References CatSdk.Crypto.Hkdf.keyedHash.
Referenced by CatSdk.Crypto.Hkdf.DeriveKey().
Member Data Documentation
keyedHash
readonly Func<byte[],byte[],byte[]> CatSdk.Crypto.Hkdf.keyedHash private
Referenced by CatSdk.Crypto.Hkdf.Expand(), CatSdk.Crypto.Hkdf.Extract(), and CatSdk.Crypto.Hkdf.Hkdf().
The documentation for this class was generated from the following file:
Hkdf.cs