SymbolCsharpDualSDK: CatSdk.Symbol.EmbeddedSecretLockTransaction Class Reference
CatSdk.Symbol.EmbeddedSecretLockTransaction Class Reference
Public Member Functions
EmbeddedSecretLockTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static EmbeddedSecretLockTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.SECRET_LOCK
Properties
Dictionary< string, string > TypeHints [get]
PublicKey SignerPublicKey [get, set]
byte Version [get, set]
NetworkType Network [get, set]
TransactionType Type [get, set]
UnresolvedAddress RecipientAddress [get, set]
Hash256 Secret [get, set]
UnresolvedMosaic Mosaic [get, set]
BlockDuration Duration [get, set]
LockHashAlgorithm HashAlgorithm [get, set]
uint Size [get]
Properties inherited from CatSdk.Symbol.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EmbeddedTransactionHeaderReserved_1
readonly int EntityBodyReserved_1
Constructor & Destructor Documentation
EmbeddedSecretLockTransaction()
CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction () inline
References CatSdk.Symbol.EmbeddedSecretLockTransaction.Duration, CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedSecretLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedSecretLockTransaction.HashAlgorithm, CatSdk.Symbol.NetworkType.MAINNET, CatSdk.Symbol.EmbeddedSecretLockTransaction.Network, CatSdk.Symbol.EmbeddedSecretLockTransaction.RecipientAddress, CatSdk.Symbol.EmbeddedSecretLockTransaction.Secret, CatSdk.Symbol.LockHashAlgorithm.SHA3_256, CatSdk.Symbol.EmbeddedSecretLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedSecretLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.EmbeddedSecretLockTransaction.TRANSACTION_VERSION, CatSdk.Symbol.EmbeddedSecretLockTransaction.Type, and CatSdk.Symbol.EmbeddedSecretLockTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize().
Member Function Documentation
Deserialize()
static EmbeddedSecretLockTransaction CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.BlockDuration.Deserialize(), CatSdk.Symbol.UnresolvedAddress.Deserialize(), CatSdk.Symbol.Hash256.Deserialize(), CatSdk.Symbol.PublicKey.Deserialize(), CatSdk.Symbol.UnresolvedMosaic.Deserialize(), CatSdk.Symbol.NetworkType.Deserialize(), CatSdk.Symbol.TransactionType.Deserialize(), CatSdk.Symbol.LockHashAlgorithm.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Duration, CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), CatSdk.Symbol.EmbeddedSecretLockTransaction.HashAlgorithm, CatSdk.Symbol.EmbeddedSecretLockTransaction.Network, CatSdk.Symbol.EmbeddedSecretLockTransaction.RecipientAddress, CatSdk.Symbol.EmbeddedSecretLockTransaction.Secret, CatSdk.Symbol.EmbeddedSecretLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedSecretLockTransaction.Type, and CatSdk.Symbol.EmbeddedSecretLockTransaction.Version.
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.EmbeddedSecretLockTransaction.Duration, CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedTransactionHeaderReserved_1, CatSdk.Symbol.EmbeddedSecretLockTransaction.EntityBodyReserved_1, CatSdk.Symbol.EmbeddedSecretLockTransaction.HashAlgorithm, CatSdk.Symbol.EmbeddedSecretLockTransaction.Network, CatSdk.Symbol.EmbeddedSecretLockTransaction.RecipientAddress, CatSdk.Symbol.EmbeddedSecretLockTransaction.Secret, CatSdk.Symbol.BlockDuration.Serialize(), CatSdk.Symbol.UnresolvedAddress.Serialize(), CatSdk.Symbol.Hash256.Serialize(), CatSdk.Symbol.PublicKey.Serialize(), CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.NetworkType.Serialize(), CatSdk.Symbol.TransactionType.Serialize(), CatSdk.Symbol.LockHashAlgorithm.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.SignerPublicKey, CatSdk.Symbol.EmbeddedSecretLockTransaction.Size, CatSdk.Symbol.EmbeddedSecretLockTransaction.Type, and CatSdk.Symbol.EmbeddedSecretLockTransaction.Version.
ToString()
override string CatSdk.Symbol.EmbeddedSecretLockTransaction.ToString () inline
Member Data Documentation
EmbeddedTransactionHeaderReserved_1
readonly int CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedTransactionHeaderReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
EntityBodyReserved_1
readonly int CatSdk.Symbol.EmbeddedSecretLockTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Symbol.EmbeddedSecretLockTransaction.TRANSACTION_TYPE = TransactionType.SECRET_LOCK static
Referenced by CatSdk.Symbol.EmbeddedTransactionFactory.Deserialize(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction().
TRANSACTION_VERSION
const byte CatSdk.Symbol.EmbeddedSecretLockTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction().
Property Documentation
Duration
BlockDuration CatSdk.Symbol.EmbeddedSecretLockTransaction.Duration get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
HashAlgorithm
LockHashAlgorithm CatSdk.Symbol.EmbeddedSecretLockTransaction.HashAlgorithm get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
Mosaic
UnresolvedMosaic CatSdk.Symbol.EmbeddedSecretLockTransaction.Mosaic get set
Network
NetworkType CatSdk.Symbol.EmbeddedSecretLockTransaction.Network get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
RecipientAddress
UnresolvedAddress CatSdk.Symbol.EmbeddedSecretLockTransaction.RecipientAddress get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
Secret
Hash256 CatSdk.Symbol.EmbeddedSecretLockTransaction.Secret get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Symbol.EmbeddedSecretLockTransaction.SignerPublicKey get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
Size
uint CatSdk.Symbol.EmbeddedSecretLockTransaction.Size get
Implements CatSdk.ISerializer.
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
Type
TransactionType CatSdk.Symbol.EmbeddedSecretLockTransaction.Type get set
Implements CatSdk.Symbol.IBaseTransaction.
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Symbol.EmbeddedSecretLockTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"SignerPublicKey", "pod:PublicKey"},
        {"Network", "enum:NetworkType"},
        {"Type", "enum:TransactionType"},
        {"RecipientAddress", "pod:UnresolvedAddress"},
        {"Secret", "pod:Hash256"},
        {"Mosaic", "struct:UnresolvedMosaic"},
        {"Duration", "pod:BlockDuration"},
        {"HashAlgorithm", "enum:LockHashAlgorithm"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Symbol.EmbeddedSecretLockTransaction.Version get set
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), and CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs