SymbolCsharpDualSDK: CatSdk.Nem.Transaction Class Reference
CatSdk.Nem.Transaction Class Reference
Public Member Functions
Transaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Transaction Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
Constructor & Destructor Documentation
Transaction()
CatSdk.Nem.Transaction.Transaction () inline
References CatSdk.Nem.Transaction.Deadline, CatSdk.Nem.Transaction.EntityBodyReserved_1, CatSdk.Nem.Transaction.Fee, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.Transaction.Network, CatSdk.Nem.Transaction.Signature, CatSdk.Nem.Transaction.SignatureSize, CatSdk.Nem.Transaction.SignerPublicKey, CatSdk.Nem.Transaction.SignerPublicKeySize, CatSdk.Nem.Transaction.Timestamp, CatSdk.Nem.TransactionType.TRANSFER, CatSdk.Nem.Transaction.Type, and CatSdk.Nem.Transaction.Version.
Referenced by CatSdk.Nem.Transaction.Deserialize().
Member Function Documentation
Deserialize()
static Transaction CatSdk.Nem.Transaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.Transaction.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.Transaction.Fee, CatSdk.Nem.Transaction.Network, CatSdk.Nem.Transaction.SignerPublicKey, CatSdk.Nem.Transaction.Transaction(), CatSdk.Nem.Transaction.Type, and CatSdk.Nem.Transaction.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.Transaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.Transaction.Deadline, CatSdk.Nem.Transaction.EntityBodyReserved_1, CatSdk.Nem.Transaction.Fee, CatSdk.Nem.Transaction.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.Transaction.SignatureSize, CatSdk.Nem.Transaction.SignerPublicKey, CatSdk.Nem.Transaction.SignerPublicKeySize, CatSdk.Nem.Transaction.Type, and CatSdk.Nem.Transaction.Version.
ToString()
override string CatSdk.Nem.Transaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.Transaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
SignatureSize
readonly int CatSdk.Nem.Transaction.SignatureSize private
Referenced by CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
SignerPublicKeySize
readonly int CatSdk.Nem.Transaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
Property Documentation
Deadline
Timestamp CatSdk.Nem.Transaction.Deadline get set
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
Fee
Amount CatSdk.Nem.Transaction.Fee get set
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
Network
NetworkType CatSdk.Nem.Transaction.Network get set
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
Signature
Signature CatSdk.Nem.Transaction.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.Transaction.Transaction().
SignerPublicKey
PublicKey CatSdk.Nem.Transaction.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
Size
uint CatSdk.Nem.Transaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.Transaction.Timestamp get set
Referenced by CatSdk.Nem.Transaction.Transaction().
Type
TransactionType CatSdk.Nem.Transaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
TypeHints
Dictionary<string, string> CatSdk.Nem.Transaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.Transaction.Version get set
Referenced by CatSdk.Nem.Transaction.Deserialize(), CatSdk.Nem.Transaction.Serialize(), and CatSdk.Nem.Transaction.Transaction().
The documentation for this class was generated from the following file:
Nem/Models.cs