SymbolCsharpDualSDK: CatSdk.Symbol.TransactionFactory Class Reference
CatSdk.Symbol.TransactionFactory Class Reference
Static Public Member Functions
static ITransaction Deserialize (BinaryReader br)
static ITransaction Deserialize (string payload)
static ITransaction CreateByName (string entityName)
Member Function Documentation
CreateByName()
static ITransaction CatSdk.Symbol.TransactionFactory.CreateByName (string entityName) inline static
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.Create().
Deserialize() [1/2]
static ITransaction CatSdk.Symbol.TransactionFactory.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Transaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.Deserialize(), CatSdk.Symbol.NodeKeyLinkTransaction.Deserialize(), CatSdk.Symbol.AggregateCompleteTransaction.Deserialize(), CatSdk.Symbol.AggregateBondedTransaction.Deserialize(), CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), CatSdk.Symbol.VrfKeyLinkTransaction.Deserialize(), CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), CatSdk.Symbol.AccountMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicMetadataTransaction.Deserialize(), CatSdk.Symbol.NamespaceMetadataTransaction.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.MultisigAccountModificationTransaction.Deserialize(), CatSdk.Symbol.AddressAliasTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), CatSdk.Symbol.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Symbol.AccountAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountMosaicRestrictionTransaction.Deserialize(), CatSdk.Symbol.AccountOperationRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Deserialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), CatSdk.Symbol.AccountKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.NodeKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AggregateCompleteTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AggregateBondedTransaction.TRANSACTION_TYPE, CatSdk.Symbol.VotingKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.VrfKeyLinkTransaction.TRANSACTION_TYPE, CatSdk.Symbol.HashLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.SecretLockTransaction.TRANSACTION_TYPE, CatSdk.Symbol.SecretProofTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AccountMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.NamespaceMetadataTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicDefinitionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicSupplyRevocationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MultisigAccountModificationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AddressAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicAliasTransaction.TRANSACTION_TYPE, CatSdk.Symbol.NamespaceRegistrationTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AccountAddressRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AccountMosaicRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.AccountOperationRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicAddressRestrictionTransaction.TRANSACTION_TYPE, CatSdk.Symbol.MosaicGlobalRestrictionTransaction.TRANSACTION_TYPE, and CatSdk.Symbol.TransferTransaction.TRANSACTION_TYPE.
Referenced by CatSdk.Symbol.TransactionFactory.Deserialize().
Deserialize() [2/2]
static ITransaction CatSdk.Symbol.TransactionFactory.Deserialize (string payload) inline static
References CatSdk.Symbol.TransactionFactory.Deserialize(), and CatSdk.Utils.Converter.HexToBytes().
The documentation for this class was generated from the following file:
Symbol/Models.cs