SymbolCsharpDualSDK: CatSdk.Utils.Base32 Class Reference
CatSdk.Utils.Base32 Class Reference
Static Public Member Functions
static byte[] Decode (string encoded)
static string Encode (byte[] data, bool padOutput=false)
static string Encode (byte[] data, int offset, int length, bool padOutput=false)
Static Private Member Functions
static int CharToInt (char c)
Static Private Attributes
static readonly char[] _digits = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567".ToCharArray()
const int _mask = 31
const int _shift = 5
Member Function Documentation
CharToInt()
static int CatSdk.Utils.Base32.CharToInt (char c) inline static private
Referenced by CatSdk.Utils.Base32.Decode().
Decode()
static byte[] CatSdk.Utils.Base32.Decode (string encoded) inline static
References CatSdk.Utils.Base32._mask, CatSdk.Utils.Base32._shift, and CatSdk.Utils.Base32.CharToInt().
Referenced by CatSdk.Symbol.Factory.TransactionsFactory.RawAddressToBytes(), and CatSdk.Utils.Converter.StringToAddress().
Encode() [1/2]
static string CatSdk.Utils.Base32.Encode (byte[] data, bool padOutput = false) inline static
References CatSdk.Utils.Base32.Encode().
Referenced by CatSdk.Utils.Converter.AddressToString(), CatSdk.Utils.Base32.Encode(), and CatSdk.Nem.Factory.NemAddress.ToString().
Encode() [2/2]
static string CatSdk.Utils.Base32.Encode (byte[] data, int offset, int length, bool padOutput = false) inline static
References CatSdk.Utils.Base32._digits, CatSdk.Utils.Base32._mask, and CatSdk.Utils.Base32._shift.
Member Data Documentation
_digits
readonly char [] CatSdk.Utils.Base32._digits = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567".ToCharArray() static private
Referenced by CatSdk.Utils.Base32.Encode().
_mask
const int CatSdk.Utils.Base32._mask = 31 static private
Referenced by CatSdk.Utils.Base32.Decode(), and CatSdk.Utils.Base32.Encode().
_shift
const int CatSdk.Utils.Base32._shift = 5 static private
Referenced by CatSdk.Utils.Base32.Decode(), and CatSdk.Utils.Base32.Encode().
The documentation for this class was generated from the following file:
Base32.cs