SymbolCsharpDualSDK: CatSdk.Nem.Address Class Reference
CatSdk.Nem.Address Class Reference
Public Member Functions
Address (byte[]? address=null)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.ByteArray
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static Address Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 40
Additional Inherited Members
Protected Member Functions inherited from CatSdk.ByteArray
ByteArray (byte fixedSize, byte[]? arrayInput)
ByteArray (int fixedSize, string hexstring)
Properties inherited from CatSdk.ByteArray
uint Size [get]
byte[] bytes [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
Address()
CatSdk.Nem.Address.Address (byte?[] address = null) inline
Member Function Documentation
Deserialize()
static Address CatSdk.Nem.Address.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Nem.MosaicLevy.Deserialize(), CatSdk.Nem.MosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Deserialize(), CatSdk.Nem.Cosignature.Deserialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Deserialize(), CatSdk.Nem.TransferTransactionV1.Deserialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Deserialize(), CatSdk.Nem.TransferTransaction.Deserialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Nem.Address.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.ByteArray.bytes.
Referenced by CatSdk.Nem.MosaicLevy.Serialize(), CatSdk.Nem.MosaicDefinitionTransaction.Serialize(), CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction.Serialize(), CatSdk.Nem.Cosignature.Serialize(), CatSdk.Nem.NamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction.Serialize(), CatSdk.Nem.TransferTransactionV1.Serialize(), CatSdk.Nem.NonVerifiableTransferTransactionV1.Serialize(), CatSdk.Nem.TransferTransaction.Serialize(), and CatSdk.Nem.NonVerifiableTransferTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Nem.Address.SIZE = 40 static
The documentation for this class was generated from the following file:
Nem/Models.cs