SymbolCsharpDualSDK: CatSdk.Symbol.MosaicId Class Reference
CatSdk.Symbol.MosaicId Class Reference
Public Member Functions
MosaicId (ulong mosaicId=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MosaicId Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 8
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
MosaicId()
CatSdk.Symbol.MosaicId.MosaicId (ulong mosaicId = 0) inline
Member Function Documentation
Deserialize()
static MosaicId CatSdk.Symbol.MosaicId.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.Mosaic.Deserialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Deserialize(), CatSdk.Symbol.MosaicAliasTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.MosaicId.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.Mosaic.Serialize(), CatSdk.Symbol.UnresolvedMosaic.Serialize(), CatSdk.Symbol.MosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction.Serialize(), CatSdk.Symbol.MosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction.Serialize(), CatSdk.Symbol.MosaicAliasTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAliasTransaction.Serialize(), CatSdk.Symbol.MosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction.Serialize(), CatSdk.Symbol.MosaicGlobalRestrictionTransaction.Serialize(), and CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.MosaicId.SIZE = 8 static
The documentation for this class was generated from the following file:
Symbol/Models.cs