SymbolCsharpDualSDK: CatSdk.Symbol.LockHashAlgorithm Class Reference
CatSdk.Symbol.LockHashAlgorithm Class Reference
Public Member Functions
LockHashAlgorithm (byte value=0)
byte[] Serialize ()
override string ToString ()
Static Public Member Functions
static LockHashAlgorithm Deserialize (BinaryReader br)
Static Public Attributes
static readonly LockHashAlgorithm SHA3_256 = new LockHashAlgorithm(0)
static readonly LockHashAlgorithm HASH_160 = new LockHashAlgorithm(1)
static readonly LockHashAlgorithm HASH_256 = new LockHashAlgorithm(2)
Properties
byte Value [get]
uint Size [get]
Properties inherited from CatSdk.IEnum< byte >
T Value [get]
Constructor & Destructor Documentation
LockHashAlgorithm()
CatSdk.Symbol.LockHashAlgorithm.LockHashAlgorithm (byte value = 0) inline
References CatSdk.Symbol.LockHashAlgorithm.Value.
Member Function Documentation
Deserialize()
static LockHashAlgorithm CatSdk.Symbol.LockHashAlgorithm.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.SecretProofTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedSecretProofTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.LockHashAlgorithm.Serialize () inline
References CatSdk.Symbol.LockHashAlgorithm.Value.
Referenced by CatSdk.Symbol.SecretLockTransaction.Serialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Serialize(), CatSdk.Symbol.SecretProofTransaction.Serialize(), and CatSdk.Symbol.EmbeddedSecretProofTransaction.Serialize().
ToString()
override string CatSdk.Symbol.LockHashAlgorithm.ToString () inline
Member Data Documentation
HASH_160
readonly LockHashAlgorithm CatSdk.Symbol.LockHashAlgorithm.HASH_160 = new LockHashAlgorithm(1) static
HASH_256
readonly LockHashAlgorithm CatSdk.Symbol.LockHashAlgorithm.HASH_256 = new LockHashAlgorithm(2) static
SHA3_256
readonly LockHashAlgorithm CatSdk.Symbol.LockHashAlgorithm.SHA3_256 = new LockHashAlgorithm(0) static
Referenced by CatSdk.Symbol.EmbeddedSecretLockTransaction.EmbeddedSecretLockTransaction(), CatSdk.Symbol.EmbeddedSecretProofTransaction.EmbeddedSecretProofTransaction(), CatSdk.Symbol.SecretLockTransaction.SecretLockTransaction(), and CatSdk.Symbol.SecretProofTransaction.SecretProofTransaction().
Property Documentation
Size
uint CatSdk.Symbol.LockHashAlgorithm.Size get
Value
byte CatSdk.Symbol.LockHashAlgorithm.Value get
Referenced by CatSdk.Symbol.LockHashAlgorithm.LockHashAlgorithm(), and CatSdk.Symbol.LockHashAlgorithm.Serialize().
The documentation for this class was generated from the following file:
Symbol/Models.cs