SymbolCsharpDualSDK: CatSdk.Symbol.FinalizationEpoch Class Reference
CatSdk.Symbol.FinalizationEpoch Class Reference
Public Member Functions
FinalizationEpoch (uint finalizationEpoch=0)
byte[] Serialize ()
Public Member Functions inherited from CatSdk.BaseValue
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static FinalizationEpoch Deserialize (BinaryReader br)
Static Public Attributes
const byte SIZE = 4
Additional Inherited Members
Public Attributes inherited from CatSdk.BaseValue
readonly ulong Value
Protected Member Functions inherited from CatSdk.BaseValue
BaseValue (byte size, ulong value)
Properties inherited from CatSdk.BaseValue
uint Size [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
FinalizationEpoch()
CatSdk.Symbol.FinalizationEpoch.FinalizationEpoch (uint finalizationEpoch = 0) inline
Member Function Documentation
Deserialize()
static FinalizationEpoch CatSdk.Symbol.FinalizationEpoch.Deserialize (BinaryReader br) inline static
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.FinalizationEpoch.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.BaseValue.Value.
Referenced by CatSdk.Symbol.VotingKeyLinkTransaction.Serialize(), and CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction.Serialize().
Member Data Documentation
SIZE
const byte CatSdk.Symbol.FinalizationEpoch.SIZE = 4 static
The documentation for this class was generated from the following file:
Symbol/Models.cs