SymbolCsharpDualSDK: CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction Class Reference
CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction Class Reference
Public Member Functions
NonVerifiableMosaicSupplyChangeTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static NonVerifiableMosaicSupplyChangeTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
MosaicId MosaicId [get, set]
MosaicSupplyChangeAction Action [get, set]
Amount Delta [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get, set]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
Constructor & Destructor Documentation
NonVerifiableMosaicSupplyChangeTransaction()
CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction () inline
References CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Action, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Delta, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Fee, CatSdk.Nem.MosaicSupplyChangeAction.INCREASE, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.MosaicId, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Network, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKeySize, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Timestamp, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.TRANSACTION_TYPE, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.TRANSACTION_VERSION, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Type, and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize().
Member Function Documentation
Deserialize()
static NonVerifiableMosaicSupplyChangeTransaction CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Action, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Delta, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.MosaicId.Deserialize(), CatSdk.Nem.MosaicSupplyChangeAction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Fee, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Network, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Type, and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Version.
Referenced by CatSdk.Nem.NonVerifiableTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Action, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deadline, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Delta, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.EntityBodyReserved_1, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Fee, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.MosaicId.Serialize(), CatSdk.Nem.MosaicSupplyChangeAction.Serialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKeySize, CatSdk.Nem.MosaicId.Size, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Type, and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Version.
ToString()
override string CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE static
Referenced by CatSdk.Nem.NonVerifiableTransactionFactory.Deserialize(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction().
TRANSACTION_VERSION
const byte CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction().
Property Documentation
Action
MosaicSupplyChangeAction CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Action get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
Deadline
Timestamp CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deadline get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
Delta
Amount CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Delta get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
Fee
Amount CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Fee get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
MosaicId
MosaicId CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.MosaicId get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction().
Network
NetworkType CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Network get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.SignerPublicKey get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
Size
uint CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Timestamp get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction().
Type
TransactionType CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"MosaicId", "struct:MosaicId"},
        {"Action", "enum:MosaicSupplyChangeAction"},
        {"Delta", "pod:Amount"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Version get set
Referenced by CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Deserialize(), CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.NonVerifiableMosaicSupplyChangeTransaction(), and CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs