SymbolCsharpDualSDK: CatSdk.Nem.MultisigTransaction Class Reference
CatSdk.Nem.MultisigTransaction Class Reference
Public Member Functions
MultisigTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static MultisigTransaction Deserialize (BinaryReader br)
Static Public Attributes
const byte TRANSACTION_VERSION = 1
static readonly TransactionType TRANSACTION_TYPE = TransactionType.MULTISIG_TRANSACTION
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Signature Signature [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
IBaseTransaction InnerTransaction [get, set]
SizePrefixedCosignature[] Cosignatures [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.ITransaction
Signature Signature [get, set]
PublicKey SignerPublicKey [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
readonly int SignatureSize
Constructor & Destructor Documentation
MultisigTransaction()
CatSdk.Nem.MultisigTransaction.MultisigTransaction () inline
References CatSdk.Nem.MultisigTransaction.Cosignatures, CatSdk.Nem.MultisigTransaction.Deadline, CatSdk.Nem.MultisigTransaction.EntityBodyReserved_1, CatSdk.Nem.MultisigTransaction.Fee, CatSdk.Nem.MultisigTransaction.InnerTransaction, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.MultisigTransaction.Network, CatSdk.Nem.MultisigTransaction.Signature, CatSdk.Nem.MultisigTransaction.SignatureSize, CatSdk.Nem.MultisigTransaction.SignerPublicKey, CatSdk.Nem.MultisigTransaction.SignerPublicKeySize, CatSdk.Nem.MultisigTransaction.Timestamp, CatSdk.Nem.MultisigTransaction.TRANSACTION_TYPE, CatSdk.Nem.MultisigTransaction.TRANSACTION_VERSION, CatSdk.Nem.MultisigTransaction.Type, and CatSdk.Nem.MultisigTransaction.Version.
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize().
Member Function Documentation
Deserialize()
static MultisigTransaction CatSdk.Nem.MultisigTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.MultisigTransaction.Cosignatures, CatSdk.Nem.MultisigTransaction.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.Signature.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.SizePrefixedCosignature.Deserialize(), CatSdk.Nem.NonVerifiableTransactionFactory.Deserialize(), CatSdk.Nem.MultisigTransaction.Fee, CatSdk.Nem.MultisigTransaction.InnerTransaction, CatSdk.Nem.MultisigTransaction.MultisigTransaction(), CatSdk.Nem.MultisigTransaction.Network, CatSdk.Nem.MultisigTransaction.SignerPublicKey, CatSdk.Nem.MultisigTransaction.Type, and CatSdk.Nem.MultisigTransaction.Version.
Referenced by CatSdk.Nem.TransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.MultisigTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.MultisigTransaction.Cosignatures, CatSdk.Nem.MultisigTransaction.Deadline, CatSdk.Nem.MultisigTransaction.EntityBodyReserved_1, CatSdk.Nem.MultisigTransaction.Fee, CatSdk.Nem.MultisigTransaction.InnerTransaction, CatSdk.Nem.MultisigTransaction.Network, CatSdk.ISerializer.Serialize(), CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.Signature.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.MultisigTransaction.SignatureSize, CatSdk.Nem.MultisigTransaction.SignerPublicKey, CatSdk.Nem.MultisigTransaction.SignerPublicKeySize, CatSdk.ISerializer.Size, CatSdk.Nem.MultisigTransaction.Type, and CatSdk.Nem.MultisigTransaction.Version.
ToString()
override string CatSdk.Nem.MultisigTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.MultisigTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
SignatureSize
readonly int CatSdk.Nem.MultisigTransaction.SignatureSize private
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.MultisigTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
TRANSACTION_TYPE
readonly TransactionType CatSdk.Nem.MultisigTransaction.TRANSACTION_TYPE = TransactionType.MULTISIG_TRANSACTION static
Referenced by CatSdk.Nem.TransactionFactory.Deserialize(), and CatSdk.Nem.MultisigTransaction.MultisigTransaction().
TRANSACTION_VERSION
const byte CatSdk.Nem.MultisigTransaction.TRANSACTION_VERSION = 1 static
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction().
Property Documentation
Cosignatures
SizePrefixedCosignature [] CatSdk.Nem.MultisigTransaction.Cosignatures get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
Deadline
Timestamp CatSdk.Nem.MultisigTransaction.Deadline get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
Fee
Amount CatSdk.Nem.MultisigTransaction.Fee get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
InnerTransaction
IBaseTransaction CatSdk.Nem.MultisigTransaction.InnerTransaction get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
Network
NetworkType CatSdk.Nem.MultisigTransaction.Network get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
Signature
Signature CatSdk.Nem.MultisigTransaction.Signature get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction().
SignerPublicKey
PublicKey CatSdk.Nem.MultisigTransaction.SignerPublicKey get set
Implements CatSdk.Nem.ITransaction.
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
Size
uint CatSdk.Nem.MultisigTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.MultisigTransaction.Timestamp get set
Referenced by CatSdk.Nem.MultisigTransaction.MultisigTransaction().
Type
TransactionType CatSdk.Nem.MultisigTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.MultisigTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Signature", "pod:Signature"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"},
        {"InnerTransaction", "struct:NonVerifiableTransaction"},
        {"Cosignatures", "array[SizePrefixedCosignature]"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.MultisigTransaction.Version get set
Referenced by CatSdk.Nem.MultisigTransaction.Deserialize(), CatSdk.Nem.MultisigTransaction.MultisigTransaction(), and CatSdk.Nem.MultisigTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs