SymbolCsharpDualSDK: CatSdk.Nem.NonVerifiableTransaction Class Reference
CatSdk.Nem.NonVerifiableTransaction Class Reference
Public Member Functions
NonVerifiableTransaction ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static NonVerifiableTransaction Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
TransactionType Type [get, set]
byte Version [get, set]
NetworkType Network [get, set]
Timestamp Timestamp [get, set]
PublicKey SignerPublicKey [get, set]
Amount Fee [get, set]
Timestamp Deadline [get, set]
uint Size [get]
Properties inherited from CatSdk.Nem.IBaseTransaction
TransactionType Type [get, set]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Private Attributes
readonly int EntityBodyReserved_1
readonly int SignerPublicKeySize
Constructor & Destructor Documentation
NonVerifiableTransaction()
CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction () inline
References CatSdk.Nem.NonVerifiableTransaction.Deadline, CatSdk.Nem.NonVerifiableTransaction.EntityBodyReserved_1, CatSdk.Nem.NonVerifiableTransaction.Fee, CatSdk.Nem.NetworkType.MAINNET, CatSdk.Nem.NonVerifiableTransaction.Network, CatSdk.Nem.NonVerifiableTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableTransaction.SignerPublicKeySize, CatSdk.Nem.NonVerifiableTransaction.Timestamp, CatSdk.Nem.TransactionType.TRANSFER, CatSdk.Nem.NonVerifiableTransaction.Type, and CatSdk.Nem.NonVerifiableTransaction.Version.
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize().
Member Function Documentation
Deserialize()
static NonVerifiableTransaction CatSdk.Nem.NonVerifiableTransaction.Deserialize (BinaryReader br) inline static
References CatSdk.Nem.NonVerifiableTransaction.Deadline, CatSdk.Nem.Amount.Deserialize(), CatSdk.Nem.Timestamp.Deserialize(), CatSdk.Nem.PublicKey.Deserialize(), CatSdk.Nem.NetworkType.Deserialize(), CatSdk.Nem.TransactionType.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.Fee, CatSdk.Nem.NonVerifiableTransaction.Network, CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), CatSdk.Nem.NonVerifiableTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableTransaction.Type, and CatSdk.Nem.NonVerifiableTransaction.Version.
Referenced by CatSdk.Nem.NonVerifiableTransactionFactory.Deserialize().
Serialize()
byte[] CatSdk.Nem.NonVerifiableTransaction.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Nem.NonVerifiableTransaction.Deadline, CatSdk.Nem.NonVerifiableTransaction.EntityBodyReserved_1, CatSdk.Nem.NonVerifiableTransaction.Fee, CatSdk.Nem.NonVerifiableTransaction.Network, CatSdk.Nem.Amount.Serialize(), CatSdk.Nem.Timestamp.Serialize(), CatSdk.Nem.PublicKey.Serialize(), CatSdk.Nem.NetworkType.Serialize(), CatSdk.Nem.TransactionType.Serialize(), CatSdk.Nem.NonVerifiableTransaction.SignerPublicKey, CatSdk.Nem.NonVerifiableTransaction.SignerPublicKeySize, CatSdk.Nem.NonVerifiableTransaction.Type, and CatSdk.Nem.NonVerifiableTransaction.Version.
ToString()
override string CatSdk.Nem.NonVerifiableTransaction.ToString () inline
Member Data Documentation
EntityBodyReserved_1
readonly int CatSdk.Nem.NonVerifiableTransaction.EntityBodyReserved_1 private
Referenced by CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
SignerPublicKeySize
readonly int CatSdk.Nem.NonVerifiableTransaction.SignerPublicKeySize private
Referenced by CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
Property Documentation
Deadline
Timestamp CatSdk.Nem.NonVerifiableTransaction.Deadline get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
Fee
Amount CatSdk.Nem.NonVerifiableTransaction.Fee get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
Network
NetworkType CatSdk.Nem.NonVerifiableTransaction.Network get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
SignerPublicKey
PublicKey CatSdk.Nem.NonVerifiableTransaction.SignerPublicKey get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
Size
uint CatSdk.Nem.NonVerifiableTransaction.Size get
Implements CatSdk.ISerializer.
Timestamp
Timestamp CatSdk.Nem.NonVerifiableTransaction.Timestamp get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction().
Type
TransactionType CatSdk.Nem.NonVerifiableTransaction.Type get set
Implements CatSdk.Nem.IBaseTransaction.
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
TypeHints
Dictionary<string, string> CatSdk.Nem.NonVerifiableTransaction.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"Type", "enum:TransactionType"},
        {"Network", "enum:NetworkType"},
        {"Timestamp", "pod:Timestamp"},
        {"SignerPublicKey", "pod:PublicKey"},
        {"Fee", "pod:Amount"},
        {"Deadline", "pod:Timestamp"}
    }
Implements CatSdk.IStruct.
Version
byte CatSdk.Nem.NonVerifiableTransaction.Version get set
Referenced by CatSdk.Nem.NonVerifiableTransaction.Deserialize(), CatSdk.Nem.NonVerifiableTransaction.NonVerifiableTransaction(), and CatSdk.Nem.NonVerifiableTransaction.Serialize().
The documentation for this class was generated from the following file:
Nem/Models.cs