SymbolCsharpDualSDK: CatSdk.Symbol.UnresolvedMosaic Class Reference
CatSdk.Symbol.UnresolvedMosaic Class Reference
Public Member Functions
UnresolvedMosaic ()
byte[] Serialize ()
override string ToString ()
byte[] Serialize ()
Static Public Member Functions
static UnresolvedMosaic Deserialize (BinaryReader br)
Properties
Dictionary< string, string > TypeHints [get]
UnresolvedMosaicId MosaicId [get, set]
Amount Amount [get, set]
uint Size [get]
Properties inherited from CatSdk.IStruct
Dictionary< string, string > TypeHints [get]
Properties inherited from CatSdk.ISerializer
uint Size [get]
Constructor & Destructor Documentation
UnresolvedMosaic()
CatSdk.Symbol.UnresolvedMosaic.UnresolvedMosaic () inline
References CatSdk.Symbol.UnresolvedMosaic.Amount.
Referenced by CatSdk.Symbol.UnresolvedMosaic.Deserialize().
Member Function Documentation
Deserialize()
static UnresolvedMosaic CatSdk.Symbol.UnresolvedMosaic.Deserialize (BinaryReader br) inline static
References CatSdk.Symbol.Amount.Deserialize(), CatSdk.Symbol.UnresolvedMosaicId.Deserialize(), and CatSdk.Symbol.UnresolvedMosaic.UnresolvedMosaic().
Referenced by CatSdk.Symbol.HashLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedHashLockTransaction.Deserialize(), CatSdk.Symbol.SecretLockTransaction.Deserialize(), CatSdk.Symbol.EmbeddedSecretLockTransaction.Deserialize(), CatSdk.Symbol.MosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction.Deserialize(), CatSdk.Symbol.TransferTransaction.Deserialize(), and CatSdk.Symbol.EmbeddedTransferTransaction.Deserialize().
Serialize()
byte[] CatSdk.Symbol.UnresolvedMosaic.Serialize () inline
Implements CatSdk.ISerializer.
References CatSdk.Symbol.Amount.Serialize(), and CatSdk.Symbol.MosaicId.Serialize().
ToString()
override string CatSdk.Symbol.UnresolvedMosaic.ToString () inline
Property Documentation
Amount
Amount CatSdk.Symbol.UnresolvedMosaic.Amount get set
Referenced by CatSdk.Symbol.UnresolvedMosaic.UnresolvedMosaic().
MosaicId
UnresolvedMosaicId CatSdk.Symbol.UnresolvedMosaic.MosaicId get set
Size
uint CatSdk.Symbol.UnresolvedMosaic.Size get
Implements CatSdk.ISerializer.
TypeHints
Dictionary<string, string> CatSdk.Symbol.UnresolvedMosaic.TypeHints get
Initial value:
= new Dictionary<string, string>(){
        {"MosaicId", "pod:UnresolvedMosaicId"},
        {"Amount", "pod:Amount"}
    }
Implements CatSdk.IStruct.
The documentation for this class was generated from the following file:
Symbol/Models.cs