SymbolCsharpDualSDK: CatSdk.ISerializer Interface Reference
CatSdk.ISerializer Interface Reference
Public Member Functions
byte[] Serialize ()
Properties
uint Size [get]
Member Function Documentation
Serialize()
byte[] CatSdk.ISerializer.Serialize ()
Implemented in CatSdk.Nem.Amount, CatSdk.Nem.Height, CatSdk.Nem.Timestamp, CatSdk.Nem.Address, CatSdk.Nem.Hash256, CatSdk.Nem.PublicKey, CatSdk.Nem.Signature, CatSdk.Nem.Transaction, CatSdk.Nem.NonVerifiableTransaction, CatSdk.Nem.AccountKeyLinkTransaction, CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction, CatSdk.Nem.NamespaceId, CatSdk.Nem.MosaicId, CatSdk.Nem.Mosaic, CatSdk.Nem.SizePrefixedMosaic, CatSdk.Nem.MosaicLevy, CatSdk.Nem.MosaicProperty, CatSdk.Nem.SizePrefixedMosaicProperty, CatSdk.Nem.MosaicDefinition, CatSdk.Nem.MosaicDefinitionTransaction, CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction, CatSdk.Nem.MosaicSupplyChangeTransaction, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction, CatSdk.Nem.MultisigAccountModification, CatSdk.Nem.SizePrefixedMultisigAccountModification, CatSdk.Nem.MultisigAccountModificationTransactionV1, CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1, CatSdk.Nem.MultisigAccountModificationTransaction, CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction, CatSdk.Nem.Cosignature, CatSdk.Nem.SizePrefixedCosignature, CatSdk.Nem.MultisigTransaction, CatSdk.Nem.NamespaceRegistrationTransaction, CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction, CatSdk.Nem.Message, CatSdk.Nem.TransferTransactionV1, CatSdk.Nem.NonVerifiableTransferTransactionV1, CatSdk.Nem.TransferTransaction, CatSdk.Nem.NonVerifiableTransferTransaction, CatSdk.Symbol.Amount, CatSdk.Symbol.BlockDuration, CatSdk.Symbol.BlockFeeMultiplier, CatSdk.Symbol.Difficulty, CatSdk.Symbol.FinalizationEpoch, CatSdk.Symbol.FinalizationPoint, CatSdk.Symbol.Height, CatSdk.Symbol.Importance, CatSdk.Symbol.ImportanceHeight, CatSdk.Symbol.UnresolvedMosaicId, CatSdk.Symbol.MosaicId, CatSdk.Symbol.Timestamp, CatSdk.Symbol.UnresolvedAddress, CatSdk.Symbol.Address, CatSdk.Symbol.Hash256, CatSdk.Symbol.Hash512, CatSdk.Symbol.PublicKey, CatSdk.Symbol.VotingPublicKey, CatSdk.Symbol.Signature, CatSdk.Symbol.Mosaic, CatSdk.Symbol.UnresolvedMosaic, CatSdk.Symbol.Transaction, CatSdk.Symbol.EmbeddedTransaction, CatSdk.Symbol.AccountKeyLinkTransaction, CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction, CatSdk.Symbol.NodeKeyLinkTransaction, CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction, CatSdk.Symbol.Cosignature, CatSdk.Symbol.DetachedCosignature, CatSdk.Symbol.AggregateCompleteTransaction, CatSdk.Symbol.AggregateBondedTransaction, CatSdk.Symbol.VotingKeyLinkTransaction, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction, CatSdk.Symbol.VrfKeyLinkTransaction, CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction, CatSdk.Symbol.HashLockTransaction, CatSdk.Symbol.EmbeddedHashLockTransaction, CatSdk.Symbol.SecretLockTransaction, CatSdk.Symbol.EmbeddedSecretLockTransaction, CatSdk.Symbol.SecretProofTransaction, CatSdk.Symbol.EmbeddedSecretProofTransaction, CatSdk.Symbol.AccountMetadataTransaction, CatSdk.Symbol.EmbeddedAccountMetadataTransaction, CatSdk.Symbol.MosaicMetadataTransaction, CatSdk.Symbol.EmbeddedMosaicMetadataTransaction, CatSdk.Symbol.NamespaceId, CatSdk.Symbol.NamespaceMetadataTransaction, CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction, CatSdk.Symbol.MosaicNonce, CatSdk.Symbol.MosaicDefinitionTransaction, CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction, CatSdk.Symbol.MosaicSupplyChangeTransaction, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction, CatSdk.Symbol.MosaicSupplyRevocationTransaction, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction, CatSdk.Symbol.MultisigAccountModificationTransaction, CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction, CatSdk.Symbol.AddressAliasTransaction, CatSdk.Symbol.EmbeddedAddressAliasTransaction, CatSdk.Symbol.MosaicAliasTransaction, CatSdk.Symbol.EmbeddedMosaicAliasTransaction, CatSdk.Symbol.NamespaceRegistrationTransaction, CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction, CatSdk.Symbol.AccountAddressRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction, CatSdk.Symbol.AccountMosaicRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction, CatSdk.Symbol.AccountOperationRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction, CatSdk.Symbol.MosaicAddressRestrictionTransaction, CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction, CatSdk.Symbol.MosaicRestrictionKey, CatSdk.Symbol.MosaicGlobalRestrictionTransaction, CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction, CatSdk.Symbol.TransferTransaction, and CatSdk.Symbol.EmbeddedTransferTransaction.
Referenced by CatSdk.Nem.Factory.TransactionsFactory.AttachSignature(), CatSdk.Symbol.Factory.TransactionsFactory.AttachSignature(), CatSdk.Nem.MultisigTransaction.Serialize(), CatSdk.Facade.SymbolFacade.SignTransaction(), and CatSdk.Facade.SymbolFacade.VerifyTransaction().
Property Documentation
Size
uint CatSdk.ISerializer.Size get
Implemented in CatSdk.Nem.Transaction, CatSdk.Nem.NonVerifiableTransaction, CatSdk.Nem.AccountKeyLinkTransaction, CatSdk.Nem.NonVerifiableAccountKeyLinkTransaction, CatSdk.Nem.NamespaceId, CatSdk.Nem.MosaicId, CatSdk.Nem.Mosaic, CatSdk.Nem.SizePrefixedMosaic, CatSdk.Nem.MosaicLevy, CatSdk.Nem.MosaicProperty, CatSdk.Nem.SizePrefixedMosaicProperty, CatSdk.Nem.MosaicDefinition, CatSdk.Nem.MosaicDefinitionTransaction, CatSdk.Nem.NonVerifiableMosaicDefinitionTransaction, CatSdk.Nem.MosaicSupplyChangeTransaction, CatSdk.Nem.NonVerifiableMosaicSupplyChangeTransaction, CatSdk.Nem.MultisigAccountModification, CatSdk.Nem.SizePrefixedMultisigAccountModification, CatSdk.Nem.MultisigAccountModificationTransactionV1, CatSdk.Nem.NonVerifiableMultisigAccountModificationTransactionV1, CatSdk.Nem.MultisigAccountModificationTransaction, CatSdk.Nem.NonVerifiableMultisigAccountModificationTransaction, CatSdk.Nem.Cosignature, CatSdk.Nem.SizePrefixedCosignature, CatSdk.Nem.MultisigTransaction, CatSdk.Nem.NamespaceRegistrationTransaction, CatSdk.Nem.NonVerifiableNamespaceRegistrationTransaction, CatSdk.Nem.Message, CatSdk.Nem.TransferTransactionV1, CatSdk.Nem.NonVerifiableTransferTransactionV1, CatSdk.Nem.TransferTransaction, CatSdk.Nem.NonVerifiableTransferTransaction, CatSdk.Symbol.Mosaic, CatSdk.Symbol.UnresolvedMosaic, CatSdk.Symbol.Transaction, CatSdk.Symbol.EmbeddedTransaction, CatSdk.Symbol.AccountKeyLinkTransaction, CatSdk.Symbol.EmbeddedAccountKeyLinkTransaction, CatSdk.Symbol.NodeKeyLinkTransaction, CatSdk.Symbol.EmbeddedNodeKeyLinkTransaction, CatSdk.Symbol.Cosignature, CatSdk.Symbol.DetachedCosignature, CatSdk.Symbol.AggregateCompleteTransaction, CatSdk.Symbol.AggregateBondedTransaction, CatSdk.Symbol.VotingKeyLinkTransaction, CatSdk.Symbol.EmbeddedVotingKeyLinkTransaction, CatSdk.Symbol.VrfKeyLinkTransaction, CatSdk.Symbol.EmbeddedVrfKeyLinkTransaction, CatSdk.Symbol.HashLockTransaction, CatSdk.Symbol.EmbeddedHashLockTransaction, CatSdk.Symbol.SecretLockTransaction, CatSdk.Symbol.EmbeddedSecretLockTransaction, CatSdk.Symbol.SecretProofTransaction, CatSdk.Symbol.EmbeddedSecretProofTransaction, CatSdk.Symbol.AccountMetadataTransaction, CatSdk.Symbol.EmbeddedAccountMetadataTransaction, CatSdk.Symbol.MosaicMetadataTransaction, CatSdk.Symbol.EmbeddedMosaicMetadataTransaction, CatSdk.Symbol.NamespaceMetadataTransaction, CatSdk.Symbol.EmbeddedNamespaceMetadataTransaction, CatSdk.Symbol.MosaicDefinitionTransaction, CatSdk.Symbol.EmbeddedMosaicDefinitionTransaction, CatSdk.Symbol.MosaicSupplyChangeTransaction, CatSdk.Symbol.EmbeddedMosaicSupplyChangeTransaction, CatSdk.Symbol.MosaicSupplyRevocationTransaction, CatSdk.Symbol.EmbeddedMosaicSupplyRevocationTransaction, CatSdk.Symbol.MultisigAccountModificationTransaction, CatSdk.Symbol.EmbeddedMultisigAccountModificationTransaction, CatSdk.Symbol.AddressAliasTransaction, CatSdk.Symbol.EmbeddedAddressAliasTransaction, CatSdk.Symbol.MosaicAliasTransaction, CatSdk.Symbol.EmbeddedMosaicAliasTransaction, CatSdk.Symbol.NamespaceRegistrationTransaction, CatSdk.Symbol.EmbeddedNamespaceRegistrationTransaction, CatSdk.Symbol.AccountAddressRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountAddressRestrictionTransaction, CatSdk.Symbol.AccountMosaicRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountMosaicRestrictionTransaction, CatSdk.Symbol.AccountOperationRestrictionTransaction, CatSdk.Symbol.EmbeddedAccountOperationRestrictionTransaction, CatSdk.Symbol.MosaicAddressRestrictionTransaction, CatSdk.Symbol.EmbeddedMosaicAddressRestrictionTransaction, CatSdk.Symbol.MosaicGlobalRestrictionTransaction, CatSdk.Symbol.EmbeddedMosaicGlobalRestrictionTransaction, CatSdk.Symbol.TransferTransaction, and CatSdk.Symbol.EmbeddedTransferTransaction.
Referenced by CatSdk.Nem.MultisigTransaction.Serialize().
The documentation for this interface was generated from the following file:
ISerializer.cs